### ISSUE TITLE
佩里科抢劫生成代码不能像v2.9.4.8之前版本一样全部勾选使用

### ISSUE THREAD

**Issue by code871** [CrazyZhang666/GTA5OnlineTools#1]
佩里克岛生成代码在v2.9.4.8版本之后加上了金额设置，但是缺陷是不能像v2.9.4.8以及之前一样全部勾上次要目标就完事方便，而且最开始的时候全部勾上就是次要物品随机刷，但是可卡因大草总量固定（大概是吧），
现在次要目标全部都勾上后变成了每种次要目标都有32种，按P打开地图一看全地图都是密密麻麻的，甚至豪宅内全部是大草。有解决方案吗，或者我使用姿势不对?
现在用的就是最新版本v2.9.5.2

**Comment by CrazyZhang666** [comment]
最新版本已修复此bug

**Comment by CrazyZhang666** [comment]
使用最新版本小助手重置面板，重新次要目标
