### ISSUE TITLE
分红面板改进

### ISSUE THREAD

**Issue by yzkdj** [CrazyZhang666/GTA5OnlineTools#10]
小助手改分红比那些【分红助手】、【赌场助手】之类的操作顺手，这几个月一直都是用小助手改分红。但是自从12.15小岛更新后，改分红比例被挪到了小助手外置菜单界面里，这样操作稍微有点麻烦，最难受的是：小助手外置菜单强行绑定F4-F9热键哪怕我不勾选，和我平时用的收费挂冲突了，这也是我之前不用赌场助手的原因，强行绑定热键太恶心。而且开启外置菜单的时候，似乎会有一定几率导致进出赌场无限黑屏，每次改完分红都得把外置菜单关掉。

希望能把4种抢劫改分红的面板，集成到【GTAHaxCode代码导入编辑器】这个页面，而且最好提供一些常用预设比例%默认值。大概看了下论坛，似乎没几个人能准确说出各种抢劫的收入上限。关于分红上限及比例，我之前花了一些时间研究，总结如下：1.每30分钟内，赌场/末日/小岛的【累计收入上限】分别为360W、255W、255W。以结算时间为准。举例：10:00开始打赌场，10:10打完第一把赌场【最终到手收入】360W。如果立刻开始打第二把赌场，必须把结算时刻控制在10:40分之后，否则不到账。打完赌场后可以打小岛末日，不同类型的抢劫差事CD是分开计算的。算上卡云卡视角时间，一般30分钟最多也只能把赌场、末日2、小岛 各通关一遍，累计可获得870W。这比给别人刷钱袋快的多，刷钱袋才300多W。2.关于比例，其实到不到帐只和你最终拿到手的钱数量有关，和比例没有直接关系；当然，和困难模式、财物类型也没有任何关系。比如，你打赌场黄金，可以只拿1块黄金，价值19000，然后分红比例改成2300%，最终到手359W也能到帐。设置分红比例时，我一般用【分红上限】/【面板玩家收入】算出比例。比如赌场面板上玩家分红写着2200000，那么我用3600000/2200000=163%，进赌场后只拿主要物品，不钻保险柜，不拿小金库，如果是气势汹汹，比例可以稍微调高一点。末日2困难分红为118.75W，那么我就设置255/118.75=214%   小岛设置主要物品为黑豹雕像，比例设置255/167.2=152%，不拿任何次要物品，刚好也是255W  。公寓抢劫还没研究透彻，似乎改分红只对自己有效，其他玩家还是改之前的比例。

小助手的ESP比收费挂好用多了，方框透视可以透过障碍物显示，自瞄是真正意义上的第三视角锁定敌人的那种，打的有感觉也方便演，而不是收费挂那种子弹追踪、自动开枪效果

**Comment by CrazyZhang666** [comment]
收到反馈
