### ISSUE TITLE
GTA5小助手问题

### ISSUE THREAD

**Issue by JMMonkey** [CrazyZhang666/GTA5OnlineTools#107]
![image](https://user-images.githubusercontent.com/87708832/126335678-03d82cd2-6a2c-4f94-a118-6e8ad22afe33.png)
![image](https://user-images.githubusercontent.com/87708832/126336147-be9b7d7d-564b-46dd-bd7f-f954f31cfde0.png)

这个kiddion外置辅助菜单打不开，不知道什么原因，希望大佬可以给解决一下，谢谢！

**Comment by zyxzchxyf** [comment]
kiddion显示"Unable to find required GTA5 offsets (0)"
