### ISSUE TITLE
好像更新之后用不了了

### ISSUE THREAD

**Issue by hjmin16** [CrazyZhang666/GTA5OnlineTools#108]
晚上更新完下载了小助手，不知道为啥全部功能都用不了。显示是正常的，比如sub的无敌明明显示了已启用的白色，实际是没效果的。另外地堡的送货也是，显示已写入，但是交完货之后钱没有变。也不知道是不是我搞错了点啥好像就是用不了，也可能是更新了不稳定？希望老板看一看！

**Comment by CrazyZhang666** [comment]
使用最新版本小助手试试看
