### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by chonerfaer** [CrazyZhang666/GTA5OnlineTools#12]
kiddion发生错误，一直按-显示了又秒不见，按了shift也没用，请问还有什么办法吗，突然就这样了

**Comment by CrazyZhang666** [comment]
多按几次shift+num-试试看

**Comment by chonerfaer** [comment]
你好，作者，我发现了问题的所在，一个键当你快速按两下他就会一直的重复，我应该是连续按了两次0，我现在解决了，只需要再次按两次0就可以了，谢谢作者
