### ISSUE TITLE
gta5线上软件的wt

### ISSUE THREAD

**Issue by MenHuan02** [CrazyZhang666/GTA5OnlineTools#122]
gta5在7.20更新后，线上助手好像就不管用！不知道是不是我电脑的问题。。。。
![QQ图片20210721153731](https://user-images.githubusercontent.com/87751654/126450184-ad5e273c-f1b5-4104-9115-120766dc4ab6.png)

**Comment by als5200** [comment]
不是你电脑问题，游戏更新后所有小助手都不能用了
