### ISSUE TITLE
kiddon和地堡修改辅助器都用不了

### ISSUE THREAD

**Issue by ming-li-9** [CrazyZhang666/GTA5OnlineTools#126]
1.kiddon显示无法找到汉化 打不开了
2.地堡辅助的助手无法读取和写入了 就是点击读取 没反应 还是0 原来读取要么是1要么是5

**Comment by zyxzchxyf** [comment]
我的显示
unable to find required GTA5 offsets

**Comment by CrazyZhang666** [comment]
版本已经更新，请使用最新版本
