### ISSUE TITLE
GTA5线上小工具问题反馈

### ISSUE THREAD

**Issue by yumoushicele** [CrazyZhang666/GTA5OnlineTools#129]
自从7月20日线上更新后小助手大部分功能都不可用，比如修改地堡出货数量，还有佩里科岛跳过前置，还有kiddion辅助也无法运行，GTA5线上已经更新到1.57版本，而辅助大部分功能只在1.54版本适用，在最新版本运行后没有效果，支持作者大大，请求更新辅助

**Comment by 2690396093** [comment]
Hello, author! Since the version of gta5 assistant is v1.57, and gta5 has been updated to about 1.57, you can go and have a look, so the online assistant needs to be updated! I am a Chinese player, I appreciate your help, I wish you an early update, happy every day, live a beautiful life!

**Comment by yumoushicele** [comment]
你的小助手做的非常不错，我在线上用小助手能跳过好多麻烦的任务点，非常支持你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 晚上6:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] GTA5线上小工具问题反馈 (#129)





 
Hello, author! Since the version of gta5 assistant is v1.57, and gta5 has been updated to about 1.57, you can go and have a look, so the online assistant needs to be updated! I am a Chinese player, I appreciate your help, I wish you an early update, happy every day, live a beautiful life!

**Comment by CrazyZhang666** [comment]
已更新，请使用最新版本小助手，感谢大佬支持

**Comment by yumoushicele** [comment]
双人佩里科岛我把猎豹雕像修改成245w队友怎么跟我的不同步，队友那边显示的的还是190w，结算之后我显示我拿了85％的分红，我队友只拿了15％分红，是我操作步骤哪里出问题了吗，希望你在小助手官网出一个双人佩里科岛两个人都能获得245w的教学谢谢！
