### ISSUE TITLE
GTAHaxUI更新了 支持最新版本

### ISSUE THREAD

**Issue by BigTear** [CrazyZhang666/GTA5OnlineTools#139]
https://www.unknowncheats.me/forum/downloads.php?do=file&id=33931

**Comment by shuuuuda** [comment]
这个和小助手功能一样吗？我下载下来显示无法安装，提示让试一下管理员权限安装但依然不行。

**Comment by BigTear** [comment]
> 这个和小助手功能一样吗？我下载下来显示无法安装，提示让试一下管理员权限安装但依然不行。

不用试了 小助手最新版更新了 直接用就行

**Comment by shuuuuda** [comment]
> > 这个和小助手功能一样吗？我下载下来显示无法安装，提示让试一下管理员权限安装但依然不行。
> 
> 不用试了 小助手最新版更新了 直接用就行

更新了但没完全更新，地堡出货试了列表里好几个都不行，其他功能也是有很多问题。
