### ISSUE TITLE
Kiddion无法正常启动

### ISSUE THREAD

**Issue by Virtulee** [CrazyZhang666/GTA5OnlineTools#147]
运行后就会弹窗 Unable to find required GTA5 offsets（0）
已关闭Win10安全中心，无任何杀毒软件
重启后依然如此

![屏幕截图 2021-07-23 100509](https://user-images.githubusercontent.com/87840222/126729743-4a2db512-8da5-408c-a4e0-1311ba914d9c.png)

**Comment by als5200** [comment]
截图中的意思是没有找到GTAV的偏移值，无法使用
