### ISSUE TITLE
第一个工具显示汉化报错

### ISSUE THREAD

**Issue by hui125800** [CrazyZhang666/GTA5OnlineTools#148]
![image](https://user-images.githubusercontent.com/65808545/126738918-dca7a91d-ac91-42da-97ba-eea4b2017481.png)
![Uploading image.png…]()

**Comment by ZGJRIJ** [comment]
前面还有一个报错，来不及截图。

**Comment by qazxswerfv** [comment]
同样的问题

**Comment by kingleohjdk** [comment]
同样的问题

**Comment by CrazyZhang666** [comment]
kiddon现在全网都没更新，大家都无法使用，先使用其他辅助吧
