### ISSUE TITLE
 关于刷钱卖车

### ISSUE THREAD

**Issue by THEpAnGZI** [CrazyZhang666/GTA5OnlineTools#152]
最新版本没有读取车辆价格的选项了

**Comment by CrazyZhang666** [comment]
这个有风险，我把它移除了，需要的话我可以加回来

**Comment by THEpAnGZI** [comment]
这样啊 那就不用啦 辛苦啦 谢谢～

穗乃果 ***@***.***>於 2021年7月25日 週日，16:14寫道：
