### ISSUE TITLE
07.24更新 线上1.57 小助手外置菜单 武器 下面的无限弹药 开启会导致外置菜单闪退

### ISSUE THREAD

**Issue by lwick65** [CrazyZhang666/GTA5OnlineTools#153]
RT 

steam 线上

系统 win10 20h2 19042.1110, 上一个版本的小助手外置菜单旧UI那个就没有问题

**Comment by CrazyZhang666** [comment]
你试试今天更新的版本，看看还闪退吗？

**Comment by lwick65** [comment]
感谢dalao跟进，已经解决问题了，错误原因是 进入游戏后打开无限子弹后 关闭小助手，再重新运行小助手 再点无限子弹就会闪退；重新运行之后只要不点这个就不会导致问题，无限子弹也能用，在新的战局也是无限子弹，只要重新运行小助手后不点这个就没有问题了，再次感谢大佬的跟进！谢谢！支持！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月25日(星期天) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 07.24更新 线上1.57 小助手外置菜单 武器 下面的无限弹药 开启会导致外置菜单闪退 (#153)





 
你试试今天更新的版本，看看还闪退吗？

**Comment by CrazyZhang666** [comment]
> 感谢dalao跟进，已经解决问题了，错误原因是 进入游戏后打开无限子弹后 关闭小助手，再重新运行小助手 再点无限子弹就会闪退；重新运行之后只要不点这个就不会导致问题，无限子弹也能用，在新的战局也是无限子弹，只要重新运行小助手后不点这个就没有问题了，再次感谢大佬的跟进！谢谢！支持！
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2021年7月25日(星期天) 下午3:13
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> 主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 07.24更新 线上1.57 小助手外置菜单 武器 下面的无限弹药 开启会导致外置菜单闪退 (#153)
> 
> 
> 
> 
> 
>  
> 你试试今天更新的版本，看看还闪退吗？
>  
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

我想我知道了问题所在，下载更新尝试修复这个bug

感谢反馈
