### ISSUE TITLE
车友会等级更新后能修改吗？

### ISSUE THREAD

**Issue by winkmessi** [CrazyZhang666/GTA5OnlineTools#155]
如题

**Comment by CrazyZhang666** [comment]
用gtahax可以改，Discord里有人发的有代码

**Comment by jinshilin35** [comment]
> 用gtahax可以改，Discord里有人发的有代码

那能在小助手加上来么。嘿嘿

**Comment by winkmessi** [comment]
dicord地址是啥






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月31日(星期六) 晚上6:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 车友会等级更新后能修改吗？ (#155)





  
用gtahax可以改，Discord里有人发的有代码
  
那能在小助手加上来么。嘿嘿

**Comment by CrazyZhang666** [comment]
> dicord地址是啥
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CrazyZhang666/GTA5OnlineTools" ***@***.***&gt;; 发送时间:&nbsp;2021年7月31日(星期六) 晚上6:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 车友会等级更新后能修改吗？ (#155) 用gtahax可以改，Discord里有人发的有代码 那能在小助手加上来么。嘿嘿 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

https://crazyzhang.cn/gta5/20210725032256.html

**Comment by CrazyZhang666** [comment]
车友会等级升降解锁教程
https://crazyzhang.cn/gta5/20210801121553.html
