### ISSUE TITLE
gta5小助手上载具闪退

### ISSUE THREAD

**Issue by joney32435** [CrazyZhang666/GTA5OnlineTools#159]
**今天一早上开了好几次游戏了 小助手开着的情况下只要一上车 gta5就会崩溃 然后今天中午发布了新版本的小助手也没有解决问题 也只是解决了外置小助手崩溃 没有解决内置  希望作者可以尽快修复

**Comment by CrazyZhang666** [comment]
请使用最新版本小助手试试看，主要看你使用了什么功能导致的，单纯只打开小助手绝对不可能导致游戏崩溃，主要是小助手中的功能
