### ISSUE TITLE
弹出游戏

### ISSUE THREAD

**Issue by DAI606** [CrazyZhang666/GTA5OnlineTools#164]
小助手外置菜单和更新后的第三方辅助刷出来车后  点F上车就弹出游戏，试了三次都是一样的被弹出游戏

**Comment by als5200** [comment]
你用第二个外置不就好了？

**Comment by DAI606** [comment]
> 你用第二个外置不就好了？

？？第三方辅助的第二个辅助？还是小助手自己的外置？小助手自己的外置菜单不是就只有一个嘛。反正这两个都是一样的，刷了车按F就弹出游戏，试了几次

**Comment by als5200** [comment]
> > 你用第二个外置不就好了？
> 
> ？？第三方辅助的第二个辅助？还是小助手自己的外置？小助手自己的外置菜单不是就只有一个嘛。反正这两个都是一样的，刷了车按F就弹出游戏，试了几次

第三方辅助第二个，小助手辅助第一个，第三方的消星不太方便

**Comment by DAI606** [comment]
> > > 你用第二个外置不就好了？
> > 
> > 
> > ？？第三方辅助的第二个辅助？还是小助手自己的外置？小助手自己的外置菜单不是就只有一个嘛。反正这两个都是一样的，刷了车按F就弹出游戏，试了几次
> 
> 第三方辅助第二个，小助手辅助第一个，第三方的消星不太方便
对啊，这两个我都试过，，刷了车后点F上车就闪退，别人我不知道，反正刚刚我试过三次都是一样的闪退，应该是还没完善更新吧，不稳定，还是静等再次更新吧，

**Comment by als5200** [comment]
> > > > 你用第二个外置不就好了？
> > > 
> > > 
> > > ？？第三方辅助的第二个辅助？还是小助手自己的外置？小助手自己的外置菜单不是就只有一个嘛。反正这两个都是一样的，刷了车按F就弹出游戏，试了几次
> > 
> > 
> > 第三方辅助第二个，小助手辅助第一个，第三方的消星不太方便
> > 对啊，这两个我都试过，，刷了车后点F上车就闪退，别人我不知道，反正刚刚我试过三次都是一样的闪退，应该是还没完善更新吧，不稳定，还是静等再次更新吧，

反正我用的时候没有闪退，懒得打字了，小助手出现任何问题，等更新

**Comment by CrazyZhang666** [comment]
请使用最新版本小助手试试看，已更新版本
