### ISSUE TITLE
没有地堡修改数量辅助了

### ISSUE THREAD

**Issue by 18029480768** [CrazyZhang666/GTA5OnlineTools#169]
希望能更新 地堡修改数量辅助 回来，对此你为我们做这个 GTA5线上小助手 让我们做任务挣钱等方面 方便了很多，感谢作者！

**Comment by als5200** [comment]
> 希望能更新 地堡修改数量辅助 回来，对此你为我们做这个 GTA5线上小助手 让我们做任务挣钱等方面 方便了很多，感谢作者！

你猜猜小助手为什么显示部分功能可用？？

**Comment by 18029480768** [comment]
> > 希望能更新 地堡修改数量辅助 回来，对此你为我们做这个 GTA5线上小助手 让我们做任务挣钱等方面 方便了很多，感谢作者！
> 
> 你猜猜小助手为什么显示部分功能可用？？

不知道，可否告诉我

**Comment by als5200** [comment]
> > > 希望能更新 地堡修改数量辅助 回来，对此你为我们做这个 GTA5线上小助手 让我们做任务挣钱等方面 方便了很多，感谢作者！
> > 
> > 
> > 你猜猜小助手为什么显示部分功能可用？？
> 
> 不知道，可否告诉我

部分功能可用，部分，地堡那玩意没有更新好，等更新
