### ISSUE TITLE
已被封号

### ISSUE THREAD

**Issue by gta5plyaer** [CrazyZhang666/GTA5OnlineTools#173]
今天在玩gta5时，想改装PR4时被R星通知被封号
在被封前R星服务器总是无法保存
操作记录：
两次太平洋差事刷钱解锁1500W，共刷了7500W
之后买公寓、地堡、办公室等各种资产
被封之前最后一次操作是把所有载具开入办公室车库改装成顶配
天基炮无冷却开过一次
使用过gtahax修改赌场前置任务
无敌、载具无敌常开

**Comment by jinshilin35** [comment]
八成是跳前置问题

**Comment by gta5plyaer** [comment]
> 八成是跳前置问题

所以小助手也不能保证完全安全。
我刷钱一直用的是“第三方辅助”中“差事刷钱”1500W
我自己寻思是最近用ce修改器修改过赌场兑换筹码数量（觉得一次20000太少）不过问题是R星当时没立即封我，反而在我单人战局时安静正常改车的时候出手了

**Comment by als5200** [comment]
好家伙，1500w你是怎么敢的呀，钱过多直接给你封了

**Comment by als5200** [comment]
> > 八成是跳前置问题
> 
> 所以小助手也不能保证完全安全。
> 我刷钱一直用的是“第三方辅助”中“差事刷钱”1500W
> 我自己寻思是最近用ce修改器修改过赌场兑换筹码数量（觉得一次20000太少）不过问题是R星当时没立即封我，反而在我单人战局时安静正常改车的时候出手了

免费的小助手你还想安全，你干脆买个越贵越好的挂算了

**Comment by 18029480768** [comment]
开无敌基本都没事

**Comment by gta5plyaer** [comment]
> > > 八成是跳前置问题
> > 
> > 所以小助手也不能保证完全安全。
> > 我刷钱一直用的是“第三方辅助”中“差事刷钱”1500W
> > 我自己寻思是最近用ce修改器修改过赌场兑换筹码数量（觉得一次20000太少）不过问题是R星当时没立即封我，反而在我单人战局时安静正常改车的时候出手了
> 
> 免费的小助手你还想安全，你干脆买个越贵越好的挂算了

你说的对，我浏览了下网页gta5的关于外挂评论，人家收费的背后是修改了R星游戏内部函数，并且不断试探R星检测机制的
另外就是外挂如果给你套模型之类的，实则是发送恶意脚本数据到你的电脑上，它是外挂有防R星检测机制，但你是绿色玩家或者小助手就遭殃了，所以遇到挂哥赶紧跑，不然你的号会被R星认定封号


同时建议小助手作者更新更强大的战局防护功能

**Comment by gta5plyaer** [comment]
另外，我还发现，如果你真的想玩绿色gta5，现在有gta5私服，国人自创的比较成熟的有gta5云城私服，可以去b站看一下，挺有意思的，把gta5的犯罪元素+我的世界探索元素+模拟人生休闲元素结合在了一起

**Comment by gta5plyaer** [comment]
> 好家伙，1500w你是怎么敢的呀，钱过多直接给你封了

我看人家都几十亿几十亿刷，然后gta5里面你仔细观察买资产，买军火，买载具的基本计量单位是“百万”，所以就想着赚1500w也是正常的嘛。。。。。

**Comment by jinshilin35** [comment]
> > 八成是跳前置问题
> 
> 所以小助手也不能保证完全安全。
> 我刷钱一直用的是“第三方辅助”中“差事刷钱”1500W
> 我自己寻思是最近用ce修改器修改过赌场兑换筹码数量（觉得一次20000太少）不过问题是R星当时没立即封我，反而在我单人战局时安静正常改车的时候出手了

我在赌场老虎机搞了800，都不敢一下花掉分开画的，你这，哎，不刷钱应该没问题，我就刷车开，一直也没问题

**Comment by gta5plyaer** [comment]
> > > 八成是跳前置问题
> > 
> > 所以小助手也不能保证完全安全。
> > 我刷钱一直用的是“第三方辅助”中“差事刷钱”1500W
> > 我自己寻思是最近用ce修改器修改过赌场兑换筹码数量（觉得一次20000太少）不过问题是R星当时没立即封我，反而在我单人战局时安静正常改车的时候出手了
> 
> 我在赌场老虎机搞了800，都不敢一下花掉分开画的，你这，哎，不刷钱应该没问题，我就刷车开，一直也没问题
> 

问题是不刷钱，你通过正常的差事攒钱，啥时候才能突破穷逼新手期呢。gta5买点东西都是百万起步，官方新出的赌场抢劫和佩里托岛启动资金又不低。
其实有一说一，gta5现在外挂泛滥除了这个游戏本身数据大没法管，还有就是R星游戏机制设计很有问题，比如就这钱的问题，导致前期发育太肝，后期资产全买了以后又太无聊，而且新玩家老玩家实力差距过大不平衡，才让很多人“不得不”走上开挂之路。
如果R星gta6继续这么搞，就算在gta6R星启动了更强大的反作弊机制，也会有更强大的外挂出现，因为你本身的游戏环境就不给正常人好的游戏体验。真正根本整治外挂不是技术上，而是在人的思想上根除

**Comment by als5200** [comment]
> > 好家伙，1500w你是怎么敢的呀，钱过多直接给你封了
> 
> 我看人家都几十亿几十亿刷，然后gta5里面你仔细观察买资产，买军火，买载具的基本计量单位是“百万”，所以就想着赚1500w也是正常的嘛。。。。。

别人都是淘宝的，几十亿，大挂知道吗，1500w还正常，知道少食多餐吗？钱这玩意日积月累的

**Comment by gta5plyaer** [comment]
> > > 好家伙，1500w你是怎么敢的呀，钱过多直接给你封了
> > 
> > 我看人家都几十亿几十亿刷，然后gta5里面你仔细观察买资产，买军火，买载具的基本计量单位是“百万”，所以就想着赚1500w也是正常的嘛。。。。。
> 
> 别人都是淘宝的，几十亿，大挂知道吗，1500w还正常，知道少食多餐吗？钱这玩意日积月累的

唉，我只看到了数量上的差距，却没考虑到我和别人运行环境（小助手和大挂）的区别，看问题太简单太草率了

**Comment by 18029480768** [comment]
第三方辅助"中"差事刷钱 1500W这个,作者已经很明确的说过这个风险很大，不介意使用！

**Comment by jinshilin35** [comment]
> > > > 八成是跳前置问题
> > > 
> > > 
> > > 所以小助手也不能保证完全安全。
> > > 我刷钱一直用的是“第三方辅助”中“差事刷钱”1500W
> > > 我自己寻思是最近用ce修改器修改过赌场兑换筹码数量（觉得一次20000太少）不过问题是R星当时没立即封我，反而在我单人战局时安静正常改车的时候出手了
> > 
> > 
> > 我在赌场老虎机搞了800，都不敢一下花掉分开画的，你这，哎，不刷钱应该没问题，我就刷车开，一直也没问题
> 
> 问题是不刷钱，你通过正常的差事攒钱，啥时候才能突破穷逼新手期呢。gta5买点东西都是百万起步，官方新出的赌场抢劫和佩里托岛启动资金又不低。
> 其实有一说一，gta5现在外挂泛滥除了这个游戏本身数据大没法管，还有就是R星游戏机制设计很有问题，比如就这钱的问题，导致前期发育太肝，后期资产全买了以后又太无聊，而且新玩家老玩家实力差距过大不平衡，才让很多人“不得不”走上开挂之路。
> 如果R星gta6继续这么搞，就算在gta6R星启动了更强大的反作弊机制，也会有更强大的外挂出现，因为你本身的游戏环境就不给正常人好的游戏体验。真正根本整治外挂不是技术上，而是在人的思想上根除

**Comment by CrazyZhang666** [comment]
> 八成是跳前置问题

我想说的是0成是跳前置的问题，恰恰跳前置是最安全的刷钱方式之一，差事刷钱不安全，主要是钱来历不明，gtahxa里的功能基本都是安全的

**Comment by als5200** [comment]
> > 八成是跳前置问题
> 
> 我想说的是0成是跳前置的问题，恰恰跳前置是最安全的刷钱方式之一，差事刷钱不安全，主要是钱来历不明，gtahxa里的功能基本都是安全的

啥时候更新第三方辅助的第一个，地堡，载具没有完善，变成2.9.7.10多好

**Comment by gta5plyaer** [comment]
> > 八成是跳前置问题
> 
> 我想说的是0成是跳前置的问题，恰恰跳前置是最安全的刷钱方式之一，差事刷钱不安全，主要是钱来历不明，gtahxa里的功能基本都是安全的

所以作者大大，地堡刷钱也是安全的吗？除了跳前置刷钱还有哪些是最安全的呢？跳前置后我用分红比例编辑器还安全吗？

**Comment by gta5plyaer** [comment]
还有一个问题就是，为啥R星没有立即封我而是等一段时间再封我呢？我在自己办公室车库升级我的车，改的好好的就被封号了，搞得我还以为是我用gtahax解锁了高等级载具配件才封号的

**Comment by CrazyZhang666** [comment]
> 还有一个问题就是，为啥R星没有立即封我而是等一段时间再封我呢？我在自己办公室车库升级我的车，改的好好的就被封号了，搞得我还以为是我用gtahax解锁了高等级载具配件才封号的

除非你是使用已经被检测到的注入式辅助（这种一旦注入游戏就会立刻封号），否是外置是无法检测到的（不可能立即封号），

你只是R星扫描到你了（程序检测到你有作弊行为或者数据异常，然后人工确认你的确作弊后，程序自动封号），你即使啥事不干也会被封号，即使不进入游戏（只是R星把封号指令传输到你客户端时你刚好在使用办公室车库升级车），

现在封号钱是关键，刷钱就有几率被封号，R星严查钱

**Comment by lwick65** [comment]
> 还有一个问题就是，为啥R星没有立即封我而是等一段时间再封我呢？我在自己办公室车库升级我的车，改的好好的就被封号了，搞得我还以为是我用gtahax解锁了高等级载具配件才封号的

感觉R*封号机制挺神奇的，我好几个朋友都被封了，很多是被挂哥捡钱袋弄封的，还有的是淘宝买刷钱给封了，但我啥出格的事都试过，就没被封，前几天用peddropper 搞了2700W没封, 再之前刷地堡出货刷了快2个以也没事，消费也是更新出啥就各种买买买，解锁弄到顶那种，钱不当钱用，也没事，真的奇怪为啥那么多人被封。现在发现一种新的搞钱方法,j法，就是单刷佩里科岛，GTAHAX改前置，刷出猎豹雕像和可可，用peddroper当NPC秒杀神奇，在潜水进入庄园时把peddroper的杀人数调高到20/s，基本进到庄园就已经没人了，直接躲摄像头偷东西，然后之间溜就好了，时间快的话可以8分钟225W，还能达成精英挑战。

**Comment by gta5plyaer** [comment]
> > 还有一个问题就是，为啥R星没有立即封我而是等一段时间再封我呢？我在自己办公室车库升级我的车，改的好好的就被封号了，搞得我还以为是我用gtahax解锁了高等级载具配件才封号的
> 
> 感觉R*封号机制挺神奇的，我好几个朋友都被封了，很多是被挂哥捡钱袋弄封的，还有的是淘宝买刷钱给封了，但我啥出格的事都试过，就没被封，前几天用peddropper 搞了2700W没封, 再之前刷地堡出货刷了快2个以也没事，消费也是更新出啥就各种买买买，解锁弄到顶那种，钱不当钱用，也没事，真的奇怪为啥那么多人被封。现在发现一种新的搞钱方法,j法，就是单刷佩里科岛，GTAHAX改前置，刷出猎豹雕像和可可，用peddroper当NPC秒杀神奇，在潜水进入庄园时把peddroper的杀人数调高到20/s，基本进到庄园就已经没人了，直接躲摄像头偷东西，然后之间溜就好了，时间快的话可以8分钟225W，还能达成精英挑战。

是的，我感觉R星想控制游戏币这个关键的资源来达到延长游戏耐玩度的目的，同时避免玩家失去兴趣所以出了赌场和小岛DLC
