### ISSUE TITLE
小助手更新后的名称与快捷方式问题

### ISSUE THREAD

**Issue by zeerdeer** [CrazyZhang666/GTA5OnlineTools#174]
每次更新后小助手默认都是中文名字，但是中文名字后面都是版本号，导致每次更新快捷方式都用不了，要么重新添加快捷方式，或者使用小助手变更为英文名字。太麻烦了，建议优化一下，或者记住用户设置。

**Comment by CrazyZhang666** [comment]
不然不加版本号无法区分版本，而且如果文件名不以版本号命名就会出现同名文件，你在更新的时候遇到同名文件就会出现问题

你可建一个文件夹存放小助手，然后把文件夹创建文件夹快捷方式
