### ISSUE TITLE
进游戏打开后，游戏崩溃。。

### ISSUE THREAD

**Issue by ppx869** [CrazyZhang666/GTA5OnlineTools#175]
软件更新后进游戏后就会崩溃

**Comment by ppx869** [comment]
是进游戏打开软件使用第三方辅助后游戏崩溃

**Comment by CrazyZhang666** [comment]
> 是进游戏打开软件使用第三方辅助后游戏崩溃

 具体是使用第三方辅助中哪个辅助中的哪个功能导致崩溃呢？还是什么都不做，然后仅仅是打开就崩溃了
