### ISSUE TITLE
The problem 

### ISSUE THREAD

**Issue by badgirlr** [CrazyZhang666/GTA5OnlineTools#177]
In particular, 8 million money function damage, the impact is particularly serious

**Comment by badgirlr** [comment]
We hope you can fix this feature as soon as possible or find a replacementWe hope you can fix this feature as soon as possible or find a replacement

**Comment by CrazyZhang666** [comment]
8 million is not work, only use 200w job

**Comment by gta5plyaer** [comment]
> We hope you can fix this feature as soon as possible or find a replacementWe hope you can fix this feature as soon as possible or find a replacement
> 

Are you referring to the plugins that make money from gTA5 errands (usually $2 million or $15 million)?

I was banned from using that plugin.
Aren't you banned?

**Comment by gta5plyaer** [comment]
> 8 million is not work, only use 200w job

Is the $2 million option safe?

**Comment by CrazyZhang666** [comment]
I'm not sure. I'm not using this
