### ISSUE TITLE
有考虑小助手开源吗

### ISSUE THREAD

**Issue by allloveend** [CrazyZhang666/GTA5OnlineTools#18]
RT 想学习下你的软件制作。感谢。

**Comment by CrazyZhang666** [comment]
暂时不想开源，倒卖太严重了，我这个实现很简单，你想要源码我可以把旧版小助手源码给你

**Comment by allloveend** [comment]
> 暂时不想开源，倒卖太严重了，我这个实现很简单，你想要源码我可以把旧版小助手源码给你

如果可以的话麻烦发到我的邮箱吧。allloveend@qq.com  非常感谢分享。
