### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by HLMDFK** [CrazyZhang666/GTA5OnlineTools#181]
小助手外置菜单的刷车不能用了，刚更新的

**Comment by CrazyZhang666** [comment]
出来kid的目前不能刷载具，其余均可以，刚刚测试刷载具正常，你用小助手外置辅助切换下战局，然后重启辅助再试试

**Comment by orangejx** [comment]
试了下 都不能刷载具 复活点在机库那个位置, 满平坦的. 换了战局还是不能刷

**Comment by CrazyZhang666** [comment]
请使用最新版本小助手试试看，已更新版本
