### ISSUE TITLE
about kiddion 

### ISSUE THREAD

**Issue by monzw99** [CrazyZhang666/GTA5OnlineTools#182]
why casino cant rig slot anymore??and it stuck at there ..

**Comment by tianjianmeng** [comment]
It's just a new bug of kiddion on. The author of this page has announced that some features of kiddion have invalided cuz of updating of GTAOL.

**Comment by tianjianmeng** [comment]
Author just made a disclaimer on the starting page of cheats which means partially available. But it is in Chinese...

**Comment by monzw99** [comment]
> Author just made a disclaimer on the starting page of cheats which means partially available. But it is in Chinese...

u mean in chinese version kiddion?
