### ISSUE TITLE
修改赌场面板出现BUG

### ISSUE THREAD

**Issue by xiaogun123** [CrazyZhang666/GTA5OnlineTools#183]
修改了第一块面板是空白的,第二快面板是已经选好的
![4Q VCF4IX0` ~E_$T6LAD5](https://user-images.githubusercontent.com/53899925/127686007-e8cbf93a-63d2-4db0-bf20-8dcef9a72e23.png)

**Comment by CrazyZhang666** [comment]
可以考虑重置下面板

````
INT32
$MPx_H3OPT_BITSET1
0
$MPx_H3OPT_BITSET0
0
$MPx_H3OPT_POI
0
$MPx_H3OPT_ACCESSPOINTS
0
$MPx_CAS_HEIST_FLOW
0
```

**Comment by xiaogun123** [comment]
不行,重置后还是一样.我也不是第一次任务就跳的

穗乃果 ***@***.***> 於 2021年8月1日週日 下午1:43寫道：
