### ISSUE TITLE
emmm

### ISSUE THREAD

**Issue by als5200** [CrazyZhang666/GTA5OnlineTools#184]
这是在晚上测试吗？2.9.8.0正常，给我提示更新2.9.8.1，仔细看居然是测试阶段，第三方辅助的刷车好了吗？地堡那些我觉得可以等等，毕竟一个人刷那种一次1w多的差事还是挺不错的（捂嘴痛哭）

**Comment by CrazyZhang666** [comment]
2.9.8.1是目前最新的版本啊，

第三方辅助的刷车我无法修复，毕竟是第三方，我只是转载汉化，

地堡刷钱也可以使用了，严格按照教程来就可以
https://crazyzhang.cn/gta5/20210728224134.html

你也可以使用这个来刷钱，使用传送、移除CD来加快CEO出货
![](https://cdn.jsdelivr.net/gh/CrazyZhang666/BlogImages/Images/Hexo/20210731171744.png)

**Comment by als5200** [comment]
> 2.9.8.1是目前最新的版本啊，
> 
> 第三方辅助的刷车我无法修复，毕竟是第三方，我只是转载汉化，
> 
> 地堡刷钱也可以使用了，严格按照教程来就可以
> https://crazyzhang.cn/gta5/20210728224134.html
> 
> 你也可以使用这个来刷钱，使用传送、移除CD来加快CEO出货
> ![](https://camo.githubusercontent.com/c2b4fc518cb4ee9297c9d143ed20429234c5758e63be62755902fcf583bedd89/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4372617a795a68616e673636362f426c6f67496d616765732f496d616765732f4865786f2f32303231303733313137313734342e706e67)

早说嘛，第三方的有问题，kid的直接不管了吗？还有这个出货价值和数量多少是安全范围内，还有范围限制是多少

**Comment by CrazyZhang666** [comment]
kiddion是一个老外的名字，这个辅助是他设计的，他目前还没有更新，我又无法替他更新

我不是发了教程嘛
https://crazyzhang.cn/gta5/20210728224134.html

再说你在哪里看到是测试版本的？

**Comment by als5200** [comment]
> kiddion是一个老外的名字，这个辅助是他设计的，他目前还没有更新，我又无法替他更新
> 
> 我不是发了教程嘛
> https://crazyzhang.cn/gta5/20210728224134.html
> 
> 再说你在哪里看到是测试版本的？

一点差不多，晚上.点开小助手提示我更新，更半天还以为有什么错误，更新状态显示的测试版本

**Comment by CrazyZhang666** [comment]
那个无关紧要，只是我还没有及时上传最新版本

**Comment by als5200** [comment]
> 那个无关紧要，只是我还没有及时上传最新版本

公开战局卡单可以出地堡那货吗？安全性怎么样？

**Comment by als5200** [comment]
> 2.9.8.1是目前最新的版本啊，
> 
> 第三方辅助的刷车我无法修复，毕竟是第三方，我只是转载汉化，
> 
> 地堡刷钱也可以使用了，严格按照教程来就可以
> https://crazyzhang.cn/gta5/20210728224134.html
> 
> 你也可以使用这个来刷钱，使用传送、移除CD来加快CEO出货
> ![](https://camo.githubusercontent.com/c2b4fc518cb4ee9297c9d143ed20429234c5758e63be62755902fcf583bedd89/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f4372617a795a68616e673636362f426c6f67496d616765732f496d616765732f4865786f2f32303231303733313137313734342e706e67)

你这个链接前面一部分是说运货，后面才是刷钱吧？？

**Comment by CrazyZhang666** [comment]
如果你不修改出货数量就是正常运货，可以使用移除CD或者触发生成，修改了就属于刷钱了

**Comment by als5200** [comment]
> 如果你不修改出货数量就是正常运货，可以使用移除CD或者触发生成，修改了就属于刷钱了

跟以前能用的kid一样吗？

**Comment by CrazyZhang666** [comment]
差不多吧
