### ISSUE TITLE
关于小助手的UAC权限

### ISSUE THREAD

**Issue by j19981106** [CrazyZhang666/GTA5OnlineTools#19]
为什么小助手要UAC权限啊，只是为了读写`C:\ProgramData\GTA5OnlineTools\`吗？如果只是为了读写`C:\ProgramData\GTA5OnlineTools\`，为什么不把这个`GTA5OnlineTools`释放到`%LOCALAPPDATA%\Programs\`下呢？

**Comment by CrazyZhang666** [comment]
读写GTA5内存数据难道不需要管理员权限吗？

**Comment by j19981106** [comment]
> 读写GTA5内存数据难道不需要管理员权限吗？

😓忘了这回事了
