### ISSUE TITLE
小助手bug反馈

### ISSUE THREAD

**Issue by YangLingd** [CrazyZhang666/GTA5OnlineTools#191]
使用外置插件刷出车友会dlc的车会导致游戏闪退

**Comment by CrazyZhang666** [comment]
不只是你说的是哪个

**Comment by YangLingd** [comment]
就是小助手外置菜单里面的刷车，车友会dlc的第一辆车，点了刷出就游戏闪退了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月1日(星期天) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 小助手bug反馈 (#191)

**Comment by CrazyZhang666** [comment]
你看不到图片吗？你看我刷的载具是不是你说的那个

**Comment by YangLingd** [comment]
看不到图片



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月1日(星期天) 晚上9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 小助手bug反馈 (#191)





 
你看不到图片吗？你看我刷的载具是不是你说的那个

**Comment by YangLingd** [comment]
就是叫这个卡利科GTF的这个车



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月1日(星期天) 晚上9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 小助手bug反馈 (#191)





 
你看不到图片吗？你看我刷的载具是不是你说的那个

**Comment by CrazyZhang666** [comment]
我正常刷出，既没有消失也没有崩溃，你切换战局重新尝试

**Comment by YangLingd** [comment]
我游戏下线了，回头我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月1日(星期天) 晚上9:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 小助手bug反馈 (#191)





 
我正常刷出，既没有消失也没有崩溃，你切换战局重新尝试
