### ISSUE TITLE
无限死亡bug

### ISSUE THREAD

**Issue by ZYY5418** [CrazyZhang666/GTA5OnlineTools#192]
![6I$%J9{WN`8DX71JR6P9NFO](https://user-images.githubusercontent.com/81253518/127765800-26a76d76-0305-420e-a79f-d3e7ca55985e.png)
![45GLJ_J35{RG0(AP1`S7YKR](https://user-images.githubusercontent.com/81253518/127765863-e441f225-8bc3-4fe5-a516-bb034b98d879.png)
![52ZC5Q_4_KC6GI6~$(B(Z}U](https://user-images.githubusercontent.com/81253518/127765862-650e8925-b4fd-4a54-ae45-276eda4cac15.png)
为什么会这样？，我没开无敌是这样，开了无敌还是这样。只要死一次就这样。

**Comment by als5200** [comment]
任务里面的？那你可能任务外碰到了大挂，还有，你为什么一开始就不开无敌、呢？

**Comment by ZYY5418** [comment]
> 任务里面的？那你可能任务外碰到了大挂，还有，你为什么一开始就不开无敌、呢？

不是，只要死一次就这样不开任务也一样。

**Comment by als5200** [comment]
> > 任务里面的？那你可能任务外碰到了大挂，还有，你为什么一开始就不开无敌、呢？
> 
> 不是，只要死一次就这样不开任务也一样。

死一次就一直死？重启游戏进线上然后直接开无敌

**Comment by ZYY5418** [comment]
> > > 任务里面的？那你可能任务外碰到了大挂，还有，你为什么一开始就不开无敌、呢？
> > 
> > 
> > 不是，只要死一次就这样不开任务也一样。
> 
> 死一次就一直死？重启游戏进线上然后直接开无敌

有时候开无敌没用会被爆炸炸死，然后就一直死

**Comment by CrazyZhang666** [comment]
你在被别的外挂搞，速速关闭游戏，否则距离封号不远了
