### ISSUE TITLE
关于sub失效问题

### ISSUE THREAD

**Issue by Endless2333** [CrazyZhang666/GTA5OnlineTools#193]
在2.9.8.2版本更新以后，sub无法使用，仅能上下跳动，无法进行确认或者取消，快捷键也全部失效

**Comment by CrazyZhang666** [comment]
![image](https://user-images.githubusercontent.com/28080853/127771768-deecdbce-cdba-4444-a8a8-bf057553761e.png)

**Comment by Endless2333** [comment]
我试了恢复默认配置，并没有用，将软件删除重新下载也还是一样

**Comment by CrazyZhang666** [comment]
请把这个文件夹下的全部文件删除
C:\ProgramData\GTA5OnlineTools

然后把小助手旁边的GTA5OnlineTools_Backup文件夹也删除，然后重启打开小助手

**Comment by Endless2333** [comment]
> 请把这个文件夹下的全部文件删除
> C:\ProgramData\GTA5OnlineTools
> 
> 然后把小助手旁边的GTA5OnlineTools_Backup文件夹也删除，然后重启打开小助手

还是没有用

**Comment by CrazyZhang666** [comment]
那就没办法了，我也没办法解决，或者discord远程，否则你只能自己研究解决

**Comment by Endless2333** [comment]
> 那就没办法了，我也没办法解决，或者discord远程，否则你只能自己研究解决

谢谢大佬的帮助，我刚刚去下载了单独的sub，问题已解决
