### ISSUE TITLE
subVersion在玩GTAOL闪退问题

### ISSUE THREAD

**Issue by wdnmdzbca** [CrazyZhang666/GTA5OnlineTools#194]
刚打开改修改器时没反应，重新打开一遍之后可以用5-15分钟。然后就闪退了。希望可以修改

**Comment by CrazyZhang666** [comment]
SubVersion崩溃的玩家请不要使用sub，sub有人会崩溃，有人不会崩溃，没办法解决（我自己使用没有崩溃过，无法定位bug）

或者你去下载原版sub ，然后使用看下会不会出现崩溃问题
https://github.com/AmazingPP/subVerison_GTAV_Hack/releases
