### ISSUE TITLE
subVersion打开无反应

### ISSUE THREAD

**Issue by wdnmdzbca** [CrazyZhang666/GTA5OnlineTools#196]
在GTA5线上模式时小助手没有任何反应，而且还经常闪退。赌场跳过没有任何反应。

**Comment by CrazyZhang666** [comment]
SubVersion崩溃的玩家请不要使用sub，sub有人会崩溃，有人不会崩溃，没办法解决（我自己使用没有崩溃过，无法定位bug）

或者你去下载原版sub ，然后使用看下会不会出现崩溃问题
https://github.com/AmazingPP/subVerison_GTAV_Hack/releases

**Comment by als5200** [comment]
> SubVersion崩溃的玩家请不要使用sub，sub有人会崩溃，有人不会崩溃，没办法解决（我自己使用没有崩溃过，无法定位bug）
> 
> 或者你去下载原版sub ，然后使用看下会不会出现崩溃问题
> https://github.com/AmazingPP/subVerison_GTAV_Hack/releases

sub无法刷车咋回事？

**Comment by CrazyZhang666** [comment]
下个版本会恢复到原版sub，当然版本sub有点问题
