### ISSUE TITLE
subversions外置辅助菜单最后一项改为杂项

### ISSUE THREAD

**Issue by www123aaa** [CrazyZhang666/GTA5OnlineTools#199]
你好，我是你的忠实粉丝，对于你的做的辅助功能很好，今天的改动为什么把以前线上直接刷出载具的，刷新枪械的，最后一个线上改为了杂项，相信不是我一个，很多人对于这样的改动无非就是有点恼火，很不方便，而且传送现在也不好用，一直传送到地下，要不就是传送不过去，解决一下，我们支持你，有时候投点钱无所谓，但是不能把大家的心血给白费了，好好的改改这个大bug，请把这个线上的最后一项改回来，不要我们支持你的粉丝寒心，另外在改改传送的bug一直传送到地下要不传送不过去，只能重新启动几次才好但还是传送到地下！谢谢

**Comment by als5200** [comment]
> 你好，我是你的忠实粉丝，对于你的做的辅助功能很好，今天的改动为什么把以前线上直接刷出载具的，刷新枪械的，最后一个线上改为了杂项，相信不是我一个，很多人对于这样的改动无非就是有点恼火，很不方便，而且传送现在也不好用，一直传送到地下，要不就是传送不过去，解决一下，我们支持你，有时候投点钱无所谓，但是不能把大家的心血给白费了，好好的改改这个大bug，请把这个线上的最后一项改回来，不要我们支持你的粉丝寒心，另外在改改传送的bug一直传送到地下要不传送不过去，只能重新启动几次才好但还是传送到地下！谢谢

这个辅助变成了原版的，有点问题很正常

**Comment by CrazyZhang666** [comment]
> 你好，我是你的忠实粉丝，对于你的做的辅助功能很好，今天的改动为什么把以前线上直接刷出载具的，刷新枪械的，最后一个线上改为了杂项，相信不是我一个，很多人对于这样的改动无非就是有点恼火，很不方便，而且传送现在也不好用，一直传送到地下，要不就是传送不过去，解决一下，我们支持你，有时候投点钱无所谓，但是不能把大家的心血给白费了，好好的改改这个大bug，请把这个线上的最后一项改回来，不要我们支持你的粉丝寒心，另外在改改传送的bug一直传送到地下要不传送不过去，只能重新启动几次才好但还是传送到地下！谢谢

主要是这个问题，以前版本的sub是我改过的，会出现按键失灵现象，有不少网友反应，我自己使用也遇到了，所以为了稳定性考虑，我换成了原版sub，原版sub传送的确会出现在地下，菜单布局不是很方便，我在研究研究看下，感谢反馈
