### ISSUE TITLE
关于透视自瞄功能的一些建议和新版F6传送的BUG反馈

### ISSUE THREAD

**Issue by wyggg** [CrazyZhang666/GTA5OnlineTools#2]
作者您好，新年快乐，十分感谢您开发了这一款免费且好用的国人辅助，实用性比老外开发的那些强太多了，自己开个战局做个任务养老挺舒服的，我之前在微信上向您提出过Tab切换分红输入框的建议，在此向您提出一些自己的想法供您参考

### 一. 自瞄功能建议

1.按住Ctrl后开启自瞄，机制当杀死一个敌人后视角会瞬间移动到离准星最近的一个单位，自瞄这个功能很棒，但是个人感觉使用过程中有一些不方便的地方，比如经常遇到的一个问题是经常会锁到自己不想要打的敌人身上，那个敌人可能在最远处，可能在墙后边，在此有个建议是否可以给出杀死敌人后下一个目标判定顺序的选项，在此我想到了这几种，[移动到离准星最近的敌人，移动到离玩家最近的敌人，移动到离玩家最远的敌人，移动到血量最少的敌人]

2.墙后敌人的过滤，我个人感觉这个功能实现起来可能会很复杂，因为我也是一名程序员，但是实际体验应该会很棒

3.自动瞄准模式，当对着NPC开枪的时候，如果检测到准星内有敌人，就自动瞄准到头部，击杀NPC后，不会自动找下一个NPC，这样相当于省去按住Ctrl的一个步骤，我能想象到如果有这个功能的话拿着加特林狂扫一群NPC然后全是爆头的场景了，真的很棒呢

4.另外建议移除透视玩家和自瞄玩家的选项

### 二.  F6传送BUG
时间2021年2月13号，目标版本：v2.9.5.1

更新后的F6传送功能,任务中按下F6后
徒步状态:角色会在地下自由落体,然后回到最初的位置
开车状态:车会直接飞到地下然后自由落体,如果不开无敌的话角色会直接死掉,开无敌的话会落一会然后回到目标点周围,也有可能死掉

### 三. 载具收藏夹功能和刷出载具快捷键
我一个朋友提的,他感觉这样会更方便

### 四: SendText 战局快捷喊话BUG
这个功能好像相当于一个键盘脚本,低配电脑使用过程中并不能把一句话发完整,有时候甚至是几个字或几个字母,是否可以调整每个字打出的时间，和是否自动按回车的选项

### 五：战局聊天列表
我不知道能不能实现，但是感觉会很好用，就是一键读取当前战局内聊天框的内容到小助手，每句话还可以有一个一键翻译的按钮，感觉可以跟SendText一起使用，和老外交流方便多了，谷歌好像有免费的翻译接口：http://translate.google.cn/translate_a/single?client=gtx&dt=t&dj=1&ie=UTF-8&sl=auto&tl=zh_TW&q=calculate

感谢，BUG的视频可以加我QQ给您复现一下  QQ：773678819

2021年2月13日 01:52:31

**Comment by CrazyZhang666** [comment]
我无法添加你的QQ，来Discord里吧

**Comment by wyggg** [comment]
> 我无法添加你的QQ，来Discord里吧

不好意思 现在已经更改了权限
