### ISSUE TITLE
小助手作者你好

### ISSUE THREAD

**Issue by SixGODXX** [CrazyZhang666/GTA5OnlineTools#200]
你好,最新版本小助手感觉有BUG,自瞄ESP设置中鼠标右键启用自瞄似乎不行,还有车友会经验倍率似乎也不起作用,无论是车友会挂机还是街头竞速结算经验都是原来的

**Comment by als5200** [comment]
> 你好,最新版本小助手感觉有BUG,自瞄ESP设置中鼠标右键启用自瞄似乎不行,还有车友会经验倍率似乎也不起作用,无论是车友会挂机还是街头竞速结算经验都是原来的

车友会的经验倍率今天才出来，有问题很正常，慢慢来

**Comment by CrazyZhang666** [comment]
> 你好,最新版本小助手感觉有BUG,自瞄ESP设置中鼠标右键启用自瞄似乎不行,还有车友会经验倍率似乎也不起作用,无论是车友会挂机还是街头竞速结算经验都是原来的

感谢反馈

右键启用自瞄的确不起作用，下个版本更新修复

车友会倍率貌似不起作用，我这里也是这样，暂时先不用这个，我再研究研究看看
