### ISSUE TITLE
崩客户端

### ISSUE THREAD

**Issue by LMorigin** [CrazyZhang666/GTA5OnlineTools#201]
版本： 正版最新版本gta5  小助手也是最新版本2.9.8.4
对象：subversion外置辅助菜单
现象：
1.多处功能不可用 例如 喷射冷却 快速换弹
2.所有功能在进入一个任务的时候不可用 需要重新开启辅助程序才能启用
例如 在进入任务前开启无敌 但是进入任务后 无敌失效 需要重新开启辅助程序
3.无论在不在任务中，载具无敌失效。更严重的是，当我坐上去的载具 被摧毁时会导致客户端崩溃
（自己判断是 服务器已经造成伤害 本地内存加载应该是无敌 相冲突导致的）
4.在进入游戏的时候 多次重启辅助程序会导致客户端崩溃
5.解锁与恢复功能 不可用 例如直接开启佩里克岛的终章任务 不可用
总体来说第三方辅助sub功能比较全面，但是已经不能使用的功能开始增多 很庆幸小助手有了自己的外置菜单 但是功能太少 和sub比起来少很多 其次sub是第三方辅助，更新不一定能到位 所以以下是建议
建议：
1.增加小助手外置菜单的功能
2.增加小助手可以使用小键盘可以上下左右选择功能的快捷键 用鼠标点击实在不方便
3.尽快与sub作者联系 反馈问题 希望尽快更新

**Comment by CrazyZhang666** [comment]
sub这个辅助怎么说呢，我用倒是出现过这些问题，有的人崩溃，有的人正常使用。难以发现问题，现在kid也更新了，不一定非要使用sub，可以选择其他功能使用

**Comment by CrazyZhang666** [comment]
你可以来discord，然后我可以帮你远程看下，因为我自己电脑sub没有出现过崩溃问题，我想找个出现过问题的看看能不能找到bug所在

**Comment by LMorigin** [comment]
感谢能够回复我的问题
我也打算去试试kid
对于你想要找出bug我也希望配合
但是discord这个软件我找不到
如果需要远程控制的话 我自己有个向日葵远程控制软件 不知道可不可以
再次感谢能够回复我的问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 中午12:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 崩客户端 (#201)





 
你可以来discord，然后我可以帮你远程看下，因为我自己电脑sub没有出现过崩溃问题，我想找个出现过问题的看看能不能找到bug所在
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
> 感谢能够回复我的问题 我也打算去试试kid 对于你想要找出bug我也希望配合 但是discord这个软件我找不到 如果需要远程控制的话 我自己有个向日葵远程控制软件 不知道可不可以 再次感谢能够回复我的问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CrazyZhang666/GTA5OnlineTools" ***@***.***&gt;; 发送时间:&nbsp;2021年8月4日(星期三) 中午12:20 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 崩客户端 (#201) 你可以来discord，然后我可以帮你远程看下，因为我自己电脑sub没有出现过崩溃问题，我想找个出现过问题的看看能不能找到bug所在 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

discord教程，用steam++加速
https://crazyzhang.cn/gta5/20210725032256.html

**Comment by LMorigin** [comment]
我的discord账号 LMOrigin#8742


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 崩客户端 (#201)





  
感谢能够回复我的问题 我也打算去试试kid 对于你想要找出bug我也希望配合 但是discord这个软件我找不到 如果需要远程控制的话 我自己有个向日葵远程控制软件 不知道可不可以 再次感谢能够回复我的问题
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CrazyZhang666/GTA5OnlineTools" @.&gt;; 发送时间:&nbsp;2021年8月4日(星期三) 中午12:20 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 崩客户端 (#201) 你可以来discord，然后我可以帮你远程看下，因为我自己电脑sub没有出现过崩溃问题，我想找个出现过问题的看看能不能找到bug所在 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
discord教程，用steam++加速
 https://crazyzhang.cn/gta5/20210725032256.html
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
