### ISSUE TITLE
emmmm

### ISSUE THREAD

**Issue by als5200** [CrazyZhang666/GTA5OnlineTools#202]
kid更新了？刷车能用了？地堡呢用了？kid更新了？？

**Comment by CrazyZhang666** [comment]
你啥时候从火星回来的啊？

**Comment by als5200** [comment]
> 你啥时候从火星回来的啊？
> 
> 那边通网了吗？

在火星上刚通网，然后试了一下能用了，更何况更新时有点问题，更新2.9.8.6，小助手里显示最新版本2.9.8.5，更新日志也是，看见kid封面变了我才知道更新了，咋，不行吗？？

**Comment by CrazyZhang666** [comment]
你手动下载最新版本，网络缓存导致的，等一会就好了

**Comment by als5200** [comment]
> 你手动下载最新版本，网络缓存导致的，等一会就好了

更新建议容易显示测试版本：）

**Comment by CrazyZhang666** [comment]
![image](https://user-images.githubusercontent.com/28080853/128128879-3c55a4e9-3554-4a35-b6f1-e57fe6cc9b5a.png)

![image](https://user-images.githubusercontent.com/28080853/128128865-bf8d3999-3ddd-4c1e-bee8-b0ad84cec619.png)

**Comment by als5200** [comment]
嗯嗯嗯
