### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by SixGODXX** [CrazyZhang666/GTA5OnlineTools#205]
似乎车友会倍率还是有问题呀,刚才试了重置1级 切战局 调1000倍 挂机经验还是20 20的加 重开游戏 切战局 重新调倍率还是一样呢

**Comment by SixGODXX** [comment]
试了一轮竞赛有效,不过其他的辅助都没开,不知道是不是其他辅助开了会影响倍率代码生效,购买服装和挂机的经验还是没有翻倍的

**Comment by SixGODXX** [comment]
还有一个问题想请教一下,是不是REP倍率每次都必须重置1级车友会等级呢,还是说重置一次后之后都可以继承等级继续1000倍刷的呢

**Comment by CrazyZhang666** [comment]
这个重置等级是任意的，你看你那些等级没解锁，就重置到距离他低一级的等级，不一定非要是1级
