### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Crazy-jinx** [CrazyZhang666/GTA5OnlineTools#206]
Gta Casino resets bug, how to solve the problem
![6dac7c094b36acafad8d8e486bd98d1000e99cdc](https://user-images.githubusercontent.com/82858028/128303665-802cc535-a110-4c5f-bbd5-03ba7a6e54b3.jpg)
![1612f2198618367ac0e4676939738bd4b21ce5dc-1](https://user-images.githubusercontent.com/82858028/128303675-a1eefd3c-e6c5-4b74-b14a-06ca28ee5aae.jpg)

**Comment by CrazyZhang666** [comment]
去做一个前置任务就会恢复了
