### ISSUE TITLE
。

### ISSUE THREAD

**Issue by ShenMI8** [CrazyZhang666/GTA5OnlineTools#208]
使用GTAHax代码导入编辑器导入赌场第一面板的时候赌场重置了，并且游戏厅所有设施包括车库也消失了

**Comment by ShenMI8** [comment]
能帮一下吗，球球了xdm

**Comment by CrazyZhang666** [comment]
去做一下前置任务，就会恢复的

**Comment by ShenMI8** [comment]
哥，主要是做不了啊，拍主要入口拍不了

**Comment by ShenMI8** [comment]
@CrazyZhang666 前置做不了，让拍主要入口拍了没反应

**Comment by CrazyZhang666** [comment]
https://crazyzhang.cn/gta5/20210728215321.html#%E5%89%8D%E7%BD%AE%E4%BB%BB%E5%8A%A1%E6%97%A0%E6%B3%95%E6%8B%8D%E7%85%A7
