### ISSUE TITLE
功能 车友会等级倍率依旧无法使用

### ISSUE THREAD

**Issue by MaxCat233** [CrazyZhang666/GTA5OnlineTools#209]
steam版的gta5，写入后换不换战局都无法生效，功能页面却显示写入成功

**Comment by CrazyZhang666** [comment]
经过测试，steam版依然可用，请看最新教程
https://crazyzhang.cn/gta5/20210806092250.html

**Comment by MaxCat233** [comment]
> 经过测试，steam版依然可用，请看最新教程
> https://crazyzhang.cn/gta5/20210806092250.html

感谢大佬的关注和解答
