### ISSUE TITLE
小助手bug

### ISSUE THREAD

**Issue by gbslayer** [CrazyZhang666/GTA5OnlineTools#212]
1.小助手的传送功能快键键 F5 和F6 无响应，只能小键盘显示菜单手动传送到导航点
2.在陆地上，进了载具之后无法传送
（使用subVersion最新版时的问题）

**Comment by gbslayer** [comment]
> 1.小助手的传送功能快键键 F5 和F6 无响应，只能小键盘显示菜单手动传送到导航点
> 2.在陆地上，进了载具之后无法传送
> （subVersion的问题）

**Comment by gbslayer** [comment]
> 1.小助手的传送功能快键键F5和F6无响应,只能小键盘显示菜单手动传送到导航点
> 2.在陆地上,进了载具之后无法传送
> (使用subVersion最新版遇到的问题)

**Comment by CrazyZhang666** [comment]
subversions是第三方辅助，这个无能为力
