### ISSUE TITLE
ESP覆盖问题。

### ISSUE THREAD

**Issue by zoe544** [CrazyZhang666/GTA5OnlineTools#215]
无边框窗口无法选择目标，只能先将随机目标打死才会随机选择下一个目标。
ESP选项几乎都没有用，只有一个显示npc和玩家这两项选择了之后才能选中随机目标。

**Comment by CrazyZhang666** [comment]
经过大量测试，以上问题均不存在，你自己研究下，看看是不是自己的使用方式有问题

**Comment by zoe544** [comment]
都没问题，是一个小问题，双屏显示的时候一定要在主屏幕运行游戏，esp覆盖才不会出现上面那种情况

**Comment by CrazyZhang666** [comment]
抱歉，没有双屏环境测试，没考虑到这个，我是单显示器的
