### ISSUE TITLE
快速佩理科岛245W在乘坐船或站在船上时传送无效

### ISSUE THREAD

**Issue by liulangshaonian** [CrazyZhang666/GTA5OnlineTools#218]
希望可以传送，这样方便带萌新，要不然每次都要上岸传送

**Comment by liulangshaonian** [comment]
希望可以开着船带人传送到佩岛豪宅正门前，连队友带船都传送过去

**Comment by CrazyZhang666** [comment]
还是要上岸才可以测试，外置测试原理是修改三维坐标，你开载具加速，几下就上岸了

小助手外置菜单》常用》载具附加功能》加速

![image](https://user-images.githubusercontent.com/28080853/128604131-92076741-a572-4c02-8467-a205fb5af33c.png)

**Comment by liulangshaonian** [comment]
那能不能将快速佩岛的载具修改为长崎，我试过，站在巡逻舰上无法传送，但站在长崎上是可以直接传送的

**Comment by CrazyZhang666** [comment]
> 那能不能将快速佩岛的载具修改为长崎，我试过，站在巡逻舰上无法传送，但站在长崎上是可以直接传送的

感谢建议，下个版本就改

**Comment by Leonye001** [comment]
这个方法不能刷钱了，我昨天封号了。
