### ISSUE TITLE
小助手外置菜单无限弹药

### ISSUE THREAD

**Issue by wanzdhan** [CrazyZhang666/GTA5OnlineTools#219]
小助手外置菜单无限子弹勾选后，在取消勾选武器，原有子弹数量会直接清零

**Comment by CrazyZhang666** [comment]
我也发现了这个问题，还在研究中

**Comment by CrazyZhang666** [comment]
添加了经典版本的无限弹药和无需换弹

**Comment by wanzdhan** [comment]
干得漂亮，十分感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月9日(周一) 中午11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 小助手外置菜单无限弹药 (#219)




 
添加了经典版本的无限弹药和无需换弹
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
