### ISSUE TITLE
【必看】如何正确反馈bug指南

### ISSUE THREAD

**Issue by CrazyZhang666** [CrazyZhang666/GTA5OnlineTools#22]
## 反馈bug请具体到某个功能，并且有截图

反馈问题要说详细，不要就说过什么打不开，什么没效果，这样没有人能帮你解决问题。如果不好描述最好的办法就是截图

## 第三方辅助
这个我只能保证汉化没有问题，其他的无法解决（使用sub导致游戏无响应暂时无法解决）

而且正常使用是没有问题的，最起码90%以上的玩家都是正常使用的

![image](https://user-images.githubusercontent.com/28080853/130950438-82222a4b-d720-404e-85c0-33c9d140c533.png)

## 小助手辅助

有问题一定要具体到功能的名字以及问题截图，这样我才好解决问题

其实功能经过反复测试过，99.9%的功能都是正常使用的，出现问题大部分都是玩家自己不清楚功能如何使用或者被杀毒拦截照成的

![image](https://user-images.githubusercontent.com/28080853/130950493-e6b69549-fbac-4649-a5e5-18b72e8c72ee.png)

**Comment by CrazyZhang666** [comment]
请不要在这里回复，谢谢大家

**Comment by SHADUKE** [comment]
kiddion 9.1 版本的线上载具刷出功能好像出问题了,个人载具全部不显示了

**Comment by chuanti** [comment]
人物的速度咋降下来？上插件走路都是飞的。。。
