### ISSUE TITLE
小助手更新之后更新版本打不开

### ISSUE THREAD

**Issue by ztxfeeggg** [CrazyZhang666/GTA5OnlineTools#220]
小助手更新之后的版本打不开，旧版本可以打开，更新之后的小助手根本打不开界面，删除的时候还在显示已经启动，提示关闭再删除，可是根本就没有打开，界面就没有显示，请问怎么解决

**Comment by CrazyZhang666** [comment]
你说的是哪个版本啊，你直接去小助手网站下载最新版本

**Comment by ztxfeeggg** [comment]
发自我的荣耀手机-------- 原始邮件 --------发件人： 穗乃果 ***@***.***>日期： 2021年8月7日周六 晚上10:47收件人： CrazyZhang666/GTA5OnlineTools ***@***.***>抄送： ztxfeeggg ***@***.***>, Author ***@***.***>主    题： Re: [CrazyZhang666/GTA5OnlineTools] 小助手更新之后更新版本打不开 (#220)

你说的是哪个版本啊，你直接去小助手网站下载最新版本

**Comment by ztxfeeggg** [comment]
实在不好意思再一次打扰你，我尽量描述详细一点，之前用的v2.9.8.8版本，然后需要更新就用推荐手动更新下载了v2.9.9.9版本，我鼠标双击它就一直转圈圈，之后圈圈不转了，但是它的界面更本就没有打开，电脑屏幕下面任务栏也没有出现我想删除新版，电脑就会显示操作无法完成，因为文件已在GTA5小助手中打开，请关闭该文件并重试，可是根本就没有界面打开我怎么去关闭，任务栏也没有，但是旧版是完全可以打开也可以用，我试过电脑重启重新官网重新下载，问题还是如此，之后的更新版本在官网下载v2.9.9.0，v2.9.9.1还是这样的问题打不开，麻烦你分析一下可能的情况。发自我的荣耀手机-------- 原始邮件 --------发件人： 穗乃果 ***@***.***>日期： 2021年8月7日周六 晚上10:47收件人： CrazyZhang666/GTA5OnlineTools ***@***.***>抄送： ztxfeeggg ***@***.***>, Author ***@***.***>主    题： Re: [CrazyZhang666/GTA5OnlineTools] 小助手更新之后更新版本打不开 (#220)

你说的是哪个版本啊，你直接去小助手网站下载最新版本

**Comment by CrazyZhang666** [comment]
我知道了，可能是加壳的原因

**Comment by ztxfeeggg** [comment]
那请问怎么解决呢？我刚才把所有杀毒软件防火墙都关闭了再重新官网下载试了一下还是打不开的。发自我的荣耀手机-------- 原始邮件 --------发件人： 穗乃果 ***@***.***>日期： 2021年8月7日周六 半夜11:59收件人： CrazyZhang666/GTA5OnlineTools ***@***.***>抄送： ztxfeeggg ***@***.***>, Author ***@***.***>主    题： Re: [CrazyZhang666/GTA5OnlineTools] 小助手更新之后更新版本打不开 (#220)

我知道了，可能是加壳的原因

**Comment by CrazyZhang666** [comment]
明天你有时间吧，加我QQ 1763575579 我给你发测试版本 看看哪个可以使用 加QQ备注“Github小助手打不开”这个词，我好知道是你

**Comment by CrazyZhang666** [comment]
你电脑是什么系统啊？

**Comment by ztxfeeggg** [comment]
我是win10系统 ，你的QQ号我刚才查询了，没查询到，是不是你号码给错了，要不你加一下我吧QQ1473289452，麻烦你了发自我的荣耀手机-------- 原始邮件 --------发件人： 穗乃果 ***@***.***>日期： 2021年8月8日周日 上午9:26收件人： CrazyZhang666/GTA5OnlineTools ***@***.***>抄送： ztxfeeggg ***@***.***>, Author ***@***.***>主    题： Re: [CrazyZhang666/GTA5OnlineTools] 小助手更新之后更新版本打不开 (#220)

你电脑是什么系统啊？
