### ISSUE TITLE
远程服务器错误

### ISSUE THREAD

**Issue by jinshilin35** [CrazyZhang666/GTA5OnlineTools#228]
刚打开就显示服务器错误，咋回事啊
![屏幕截图 2021-08-09 110132](https://user-images.githubusercontent.com/69503019/128656281-7a42335f-5478-4310-b070-aa01d548c3c5.png)

**Comment by jinshilin35** [comment]
手动更新可解决

**Comment by CrazyZhang666** [comment]
![image](https://user-images.githubusercontent.com/28080853/128657171-df40f7bb-8d37-4ce5-baac-4c7e1e73567c.png)
