### ISSUE TITLE
外置菜单天气功能紊乱

### ISSUE THREAD

**Issue by polarabbit0** [CrazyZhang666/GTA5OnlineTools#231]
![image](https://user-images.githubusercontent.com/86583346/128675270-4af87329-f147-45b4-8424-b5e0650c5371.png)
![image](https://user-images.githubusercontent.com/86583346/128675473-cad81e6a-4739-4b10-a82f-c4ef0671222a.png)
小助手功能→小助手外置菜单→世界→本地天气中，打开“圣诞节”功能后实际上是“万圣节”，打开“万圣节”功能则会一片漆黑,"大雾"无明显效果，“阴天”实际上为下雨,“下雪”为“暴雪”，“暴雪”为小雪，"小雪"为圣诞。

**Comment by CrazyZhang666** [comment]
感谢反馈，已找到问题所在，下个版本修复

**Comment by CrazyZhang666** [comment]
已修复，请更新版本
