### ISSUE TITLE
传送bug多，subversion武器子弹bug多

### ISSUE THREAD

**Issue by www123aaa** [CrazyZhang666/GTA5OnlineTools#232]
这个传送的subversion的bug太多了。每次启动完传送一次就卡了。不管用了，还得重启一下软件才可以，要不有时间在软件里面开启别的东西也有时候无法传送，再有一个就是武器子弹的设置，在里面开完爆炸子弹有时候 别的东西不管用需要退出，这个爆炸子弹无法取消，重新进助手也不能解决，或者子弹编辑里面也是，有时候无法设置，或者设置上了无法使用，要不就是和爆炸子弹一样，无法取消。
在一个就是subversion这个软件里面的刷等级，刷了等级就改不回来了，搞的我现在是一个一级的号，技术人员排查排查

**Comment by CrazyZhang666** [comment]
没办法，subverion是第三方辅助，我无法修复这个问题

**Comment by devonshan** [comment]
小助手外置菜单里面的传送如果坐在车里有80%左右概率会直接死亡，请问会更新吗

**Comment by CrazyZhang666** [comment]
请按下W

**Comment by devonshan** [comment]
> 请按下W

先按W然后按F5传送吗

**Comment by CrazyZhang666** [comment]
> > 请按下W
> 
> 先按W然后按F5传送吗

当然不是，

你坐上载具，按F5传送，然后载具在地下，你按W载具就会到地面

**Comment by devonshan** [comment]
我是这样操作的，但是按W，载具落地之后人物会直接死亡，不知道为什么

**Comment by CrazyZhang666** [comment]
> 我是这样操作的，但是按W，载具落地之后人物会直接死亡，不知道为什么

刚刚测试了下，传送正常，没有问题，

请重启游戏或者电脑再试试
