### ISSUE TITLE
ShowMeTheMoney没有用

### ISSUE THREAD

**Issue by MicrophoneBoy** [CrazyZhang666/GTA5OnlineTools#234]
打开游戏过后启动ShowMeTheMoney是有声音的但是就是不会加钱，是因为版本的原因吗？因为在这次版本更新之前都是可以用的

**Comment by CrazyZhang666** [comment]
没办法，ShowMeTheMoney是第三方辅助，到目前为止还处于1.54版本状态，一直没有更新，不推荐使用

**Comment by MicrophoneBoy** [comment]
> 没办法，ShowMeTheMoney是第三方辅助，到目前为止还处于1.54版本状态，一直没有更新，不推荐使用

**Comment by MicrophoneBoy** [comment]
> 没办法，ShowMeTheMoney是第三方辅助，到目前为止还处于1.54版本状态，一直没有更新，不推荐使用

那就只有等它出新的吗？

**Comment by CrazyZhang666** [comment]
我也不知道，为啥这么喜欢差事刷钱呢？我从来没用过，我都几乎删除这个了，刷钱又不是只有这一个
