### ISSUE TITLE
分享一个刷夜总会400W的方法 

### ISSUE THREAD

**Issue by lwick65** [CrazyZhang666/GTA5OnlineTools#235]
先把要用到东西放上来
夜总会
// Cargo Price
Global_262145.f_24054 = 5000 Sporting Goods
Global_262145.f_24055 = 20000 American Import
Global_262145.f_24056 = 8500 Pharmaceutical Research
Global_262145.f_24057 = 1500 Organic Produce
Global_262145.f_24058 = 1000 Printing And Copying
Global_262145.f_24059 = 3500 Cash Creation
Global_262145.f_24060 = 10000 Shipment and Cargo
// Max Units
Global_262145.f_24061 = 100; // Sporting Goods
Global_262145.f_24062 = 10; // South American Imports
Global_262145.f_24063 = 20; // Pharmaceutical Research
Global_262145.f_24064 = 80; // Organic Produce
Global_262145.f_24065 = 60; // Printing and Copying
Global_262145.f_24066 = 40; // Cash Creation
Global_262145.f_24067 = 50; // Cargo and Shipments
// Time to Produce 1 Unit (i dont know how this timing works but if you want to instant refill, just set it to 1)
Global_262145.f_24046 = 4800000; // Sporting Goods
Global_262145.f_24047 = 14400000; // South American Imports
Global_262145.f_24048 = 7200000; // Pharmaceutical Research
Global_262145.f_24049 = 2400000; // Organic Produce
Global_262145.f_24050 = 1800000; // Printing and Copying
Global_262145.f_24051 = 3600000; // Cash Creation
Global_262145.f_24052 = 8400000; // Cargo and Shipments

说个思路，首先你得有夜总会，和摩托帮。卡个单人公共战局，注册摩托帮。去夜总会控制台把所有员工撤下，货物全卖掉清0。 接着打开GTAHAX  输入 Global_262145.f_24055 = 20000 American Import（南美货物进口），把2W改成41W，或者40.9w （夜总会一次性卖货最多410W包含10W的手续费，所有最多到手是400W，但有时候会奖励你多1w，401W的话就会显示数据无效，所以可以卡个390W）。

接着改 Global_262145.f_24047 = 14400000; // South American Imports， 把这个数据改成1，意思是产生1个单位货物所用的时间，1即1秒1个。 

回到游戏后，打开夜总会仓库管理控制面板，派1个人去生产南美货物，其他的货物不要生产，就南美货物，触发生产。 回到 出售货物 那里可以看到南美货物那里1秒增加1个单位，如果没增加就加个人生产其他东西触发一下，然后把那个人撤回来，如果还没动，右下角一直转圈，那就是网卡了。 等南美货物生产完 10/10，就点全部出售。 然后用小助手或者其他外置修改器按 F6 F5瞬移完成简单的运货任务，完成后 400W就到账了，用手机打开银行查看交易记录，有记录就成功了。 然后F5导航瞬移回夜总会中控 可发现第二批 10个南美货物又生产完了，接着继续送货。 任务做熟练了基本可以实现3 4分钟完成运货，回来没有CD，可以直接继续送完再继续送。

**Comment by lwick65** [comment]
这个方法的好处就是 在设置好GTAHAX的数据后 配合 外置修改器或者小助手 瞬移无敌，不用频繁打开修改器点出发生产或者改钱的数据，或者切出桌面点其他修改器，直接在游戏内操作简单的任务就可以达到刷钱的效果，而且没有CD。

**Comment by lwick65** [comment]
这个方法的好处就是 在设置好GTAHAX的数据后 配合 外置修改器或者小助手 瞬移无敌，不用频繁打开修改器点出发生产或者改钱的数据，或者切出桌面点其他修改器，直接在游戏内操作简单的任务就可以达到刷钱的效果，而且没有CD。

**Comment by CrazyZhang666** [comment]
如果按照这个方式的话，理论上CEO货物，地堡货物。机库货物都可以改物品弹夹，但是就是怕不安全，我一般只改进出货CD的，货物加载一般没怎么改过，不过理论上应该风险不大

比如CEO货物单箱最高2W，我可以改成10W或者更高吗？这样出货不就可以拿到更高的钱吗，而且还比夜总会简单些，不过这个目前还在理论阶段，我没有改过

**Comment by lwick65** [comment]
> 如果按照这个方式的话，理论上CEO货物，地堡货物。机库货物都可以改物品弹夹，但是就是怕不安全，我一般只改进出货CD的，货物加载一般没怎么改过，不过理论上应该风险不大
> 
> 比如CEO货物单箱最高2W，我可以改成10W或者更高吗？这样出货不就可以拿到更高的钱吗，而且还比夜总会简单些，不过这个目前还在理论阶段，我没有改过

是的，CEO货物如果能找到最新的global值也可这么尝试一下，理论上来说每一种出货任务都有金额上限，像地堡210W，夜总会400W，CEO货物应该最高上限会更高一些，只要有1个货物，修改相应的货物价值，就能以金额上限的价格出售，有相应的GLOBAL值进行修改可以尝试！但目前实验来看CEO货物运输很多都要至少两名以上玩家运输，效率不高，很多时候还是在海上放货的，瞬移容易失效，夜总会任务很多都是在陆地上的，可以实现F6直接瞬移交货，但如果能像KIDDON菜单的地堡一键交货，估计效率能更高。之前我用夜总会刷货物是直接用kiddon菜单补满体育用品货物，改价格出。但用多两次就显示无效了，大概率是因为凭空出现的货物不符合交易机制吧，改成减生产时间CD之后再弄就没这问题了，所以个人感觉还是得在货物生产减CD这做文章

**Comment by lwick65** [comment]
> 如果按照这个方式的话，理论上CEO货物，地堡货物。机库货物都可以改物品弹夹，但是就是怕不安全，我一般只改进出货CD的，货物加载一般没怎么改过，不过理论上应该风险不大
> 
> 比如CEO货物单箱最高2W，我可以改成10W或者更高吗？这样出货不就可以拿到更高的钱吗，而且还比夜总会简单些，不过这个目前还在理论阶段，我没有改过

https://www.unknowncheats.me/forum/3197796-post11951.html

刚刚根据这个帖子改了一下试了试，CEO货物最高价格可以以600W出售，但那些运输任务真的太麻烦了，开船，开飞机过点投放，开飞机得消灭天上的敌方飞机，还得反复回办公室进货，效率不如夜总会送货高。

**Comment by CrazyZhang666** [comment]
行 我有时间研究下

**Comment by jxjdnsm46** [comment]
大佬 我改差事收入变成为记录收入了 请问 为记录收入代码是什么啊
https://crazyzhang.cn/gta5/20210806173210.html#%E8%81%8C%E4%B8%9A%E7%94%9F%E6%B6%AF

**Comment by Huang1035** [comment]
可以教教我怎麼更改嗎 我不太會用GTAHax

**Comment by A1pine** [comment]
更新一下合约DLC以后的值

    Global_262145.f_24142 = 5000; // Sporting Goods
    Global_262145.f_24143 = 20000; // South American Imports
    Global_262145.f_24144 = 8500; // Pharmaceutical Research
    Global_262145.f_24145 = 1500; // Organic Produce
    Global_262145.f_24146 = 1000; // Printing and Copying
    Global_262145.f_24147 = 3500; // Cash Creation
    Global_262145.f_24148 = 10000; // Cargo and Shipments
