### ISSUE TITLE
BigBaseV2 注入失敗

### ISSUE THREAD

**Issue by Matutoyo** [CrazyZhang666/GTA5OnlineTools#236]
启动Xenos64注入工具，设置已经自动配置好了，我们只需要点击“Inject”注入

按下去顯示 注入圖像失敗 C;/Programdata\GTASonlineTools\BigBaseV2.dll      錯誤代碼 OxCO000135

這問題如何改善

**Comment by CrazyZhang666** [comment]
更换支持AVX2指令集的CPU

**Comment by Matutoyo** [comment]
> 不支持AVX2指令集的CPU

請問有教學嗎

**Comment by CrazyZhang666** [comment]
AVX2指令集是硬件支持，就好比1060显卡没有光线追踪，而3060有光线追踪一样

**Comment by Matutoyo** [comment]
我的CPU是 i7-7700所以沒有AVX2指令集?

**Comment by CrazyZhang666** [comment]
你自己研究吧

https://www.unknowncheats.me/forum/grand-theft-auto-v/431470-bread-stat-editor-basic-unlocks-24.html

![image](https://user-images.githubusercontent.com/28080853/128868333-33b2a8c0-4c45-4b9f-b84a-711195b021ee.png)

**Comment by Matutoyo** [comment]
> 你自己研究吧
> 
> https://www.unknowncheats.me/forum/grand-theft-auto-v/431470-bread-stat-editor-basic-unlocks-24.html
> 
> ![圖像](https://user-images.githubusercontent.com/28080853/128868333-33b2a8c0-4c45-4b9f-b84a-711195b021ee.png)

有看了一下 但不是很懂，所以這問題點是無解的嗎?

**Comment by Matutoyo** [comment]
> 你自己研究吧


我看了一下 但不是很懂 所以這問題點是無解嗎?
