### ISSUE TITLE
gta5小助手用过后移动速度加快

### ISSUE THREAD

**Issue by awfawtyj** [CrazyZhang666/GTA5OnlineTools#242]
换战局 重进移速都没变回正常

**Comment by awfawtyj** [comment]
> 换战局重进移速都没变回正常

![$~DRRM45TGRJ(@9@LVDG9KA](https://user-images.githubusercontent.com/88866558/129294731-00286035-2dd0-4898-928a-439978683646.png)
进游戏后奔跑和游泳速度都变快了 没开小助手也是一样 我想知道是什么原因

**Comment by awfawtyj** [comment]
而且线下角色的移动速度也变快了 麻烦尽快解决这个问题

**Comment by CrazyZhang666** [comment]
删除角色，你解锁了角色隐藏属性
