### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 224414** [CrazyZhang666/GTA5OnlineTools#243]
昨天车友会等级还可以快速升级的，今天就不能用了，昨天基本上是7分钟10级，今天就算点开了也是正常速度升级。很慢，而且重启多次也没用。

**Comment by CrazyZhang666** [comment]
要重启游戏才可以

而且使用前先用小助手切换一下战局，然后比赛 前 中 后 都按一下 repx1000

**Comment by 224414** [comment]
上中下是什么？------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月13日(星期五) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] Bug (#243)
