### ISSUE TITLE
外部ESP覆盖 建议添加手柄控制

### ISSUE THREAD

**Issue by 1459236018** [CrazyZhang666/GTA5OnlineTools#246]
用手柄控制

**Comment by CrazyZhang666** [comment]
手柄控制是指？

**Comment by 1459236018** [comment]
就是有手柄的LT键控制AimBot



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月15日(周日) 下午2:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 外部ESP覆盖 建议添加手柄控制 (#246)




 
手柄控制是指？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
这个暂时弄不了，手柄的键位我不了解

**Comment by 1459236018** [comment]
没事只是希望能有 望你们能考虑考虑以后推荐上



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月15日(周日) 下午2:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 外部ESP覆盖 建议添加手柄控制 (#246)




 
这个暂时弄不了，手柄的键位我不了解
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
手柄有辅助瞄准啊，Kiddion就可以开启，不会影响到战局匹配的

**Comment by 1459236018** [comment]
对所以我希望能添加嘛 自由瞄准 没法用辅助瞄准



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月15日(周日) 下午2:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 外部ESP覆盖 建议添加手柄控制 (#246)




 
手柄有辅助瞄准啊，Kiddion就可以开启，不会影响到战局匹配的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
> 对所以我希望能添加嘛 自由瞄准 没法用辅助瞄准
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月15日(周日) 下午2:12 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [CrazyZhang666/GTA5OnlineTools] 外部ESP覆盖 建议添加手柄控制 (#246) 手柄有辅助瞄准啊，Kiddion就可以开启，不会影响到战局匹配的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Kid可以改瞄准模式的，即使是自由瞄准
