### ISSUE TITLE
CrazyZhang666

### ISSUE THREAD

**Issue by POSDSS** [CrazyZhang666/GTA5OnlineTools#249]
GTA线上小助手的 金钱和经验 脚本中的 更改车友会经验倍数 经常时灵时不灵

**Comment by CrazyZhang666** [comment]
每次切换战局或者加载场景都会被系统强制重置，所以要在任务的前中后分别点击一次，并不是失灵

**Comment by POSDSS** [comment]
但是我在挂机时也按了，除了一开始触发了一次，后续都没有触发过1000倍经验



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 15, 2021 13:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CrazyZhang666/GTA5OnlineTools] CrazyZhang666 (#249)




 
每次切换战局或者加载场景都会被系统强制重置，所以要在任务的前中后分别点击一次，并不是失灵
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
https://crazyzhang.cn/gta5/20210805104945.html#%E8%BD%A6%E5%8F%8B%E4%BC%9A%E7%BB%8F%E9%AA%8C%E8%8E%B7%E5%8F%96%E6%96%B9%E5%BC%8F

仔细看看教程吧

别人早就1000级全部解锁了
