### ISSUE TITLE
Kiddion

### ISSUE THREAD

**Issue by cmk2046** [CrazyZhang666/GTA5OnlineTools#25]
我建议可以改下Kiddion里的丢钱选项，在线上服务里，把钱袋的钱改为更高，200万或500万，这应该是可以改的

**Comment by CrazyZhang666** [comment]
这个你去unc联系kid吧

**Comment by cmk2046** [comment]
我现在用小助手被封号了，封了一个月，小助手到底安不安全

穗乃果 ***@***.***> 于 2021年3月6日周六 上午9:50写道：
