### ISSUE TITLE
雷达影踪

### ISSUE THREAD

**Issue by xiaxiaoshaokao** [CrazyZhang666/GTA5OnlineTools#250]
雷达影踪没用啊作者，还有隐身也是。

**Comment by CrazyZhang666** [comment]
使用最新版本小助手

**Comment by xiaxiaoshaokao** [comment]
> 使用最新版本小助手

是最新版本啊，难道是要管理员权限吗？

**Comment by CrazyZhang666** [comment]
我不清楚你是怎么使用的，我这里测试都是没问题的，你自己研究下吧

**Comment by xiaxiaoshaokao** [comment]
> 我不清楚你是怎么使用的，我这里测试都是没问题的，你自己研究下吧
你们是怎么用的啊，这2个功能有特殊要求吗

**Comment by CrazyZhang666** [comment]
没有任何要求，用鼠标点击，你看看其他功能是否正常，有的功能切换战局需要重新开启，或者直接重启小助手

**Comment by xiaxiaoshaokao** [comment]
> 没有任何要求，用鼠标点击，你看看其他功能是否正常，有的功能切换战局需要重新开启，或者直接重启小助手
哦，那我找找办法吧
