### ISSUE TITLE
被封了怎么办

### ISSUE THREAD

**Issue by 203284289** [CrazyZhang666/GTA5OnlineTools#252]

**Comment by CrazyZhang666** [comment]
GTA5、R星账号换绑、账号解封、账号数据重置（Epic版）
https://www.bilibili.com/read/cv12544969
GTA5、R星账号换绑、账号解封、账号数据重置（Steam版）
https://www.bilibili.com/read/cv12269051

**Comment by CrazyZhang666** [comment]
百度搜索的
