### ISSUE TITLE
建议添加一个功能

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [CrazyZhang666/GTA5OnlineTools#256]
建议添加自动解锁佩里科岛和赌场的指纹，可以参考https://gitee.com/fissssssh/GTAFingerprinter

**Comment by RRGS666** [comment]
我有一个解锁赌场的脚本，没用过，不过应该可以用
https://wwe.lanzoui.com/iU2xpsxp6uh
运行时，关闭杀毒，用管理员模式运行。并安装运行库

**Comment by RRGS666** [comment]
我有一个解锁赌场的脚本，没用过，不过应该可以用
https://wwe.lanzoui.com/iU2xpsxp6uh
运行时，关闭杀毒，用管理员模式运行。并安装运行库

**Comment by CrazyZhang666** [comment]
我一般都是F4坐标微调进去的，不用指纹
