### ISSUE TITLE
刷等级封号

### ISSUE THREAD

**Issue by SilentRoads** [CrazyZhang666/GTA5OnlineTools#257]
发现刷等级会有较大概率封号，无论是代码导入编辑器还是RP*1000的方式都有较大风险，目前根据几个朋友的经历来看基本封号的集中在50级以下，75级以上基本上不会封，关于刷级问题还有待解决，不过车友会刷级不会有问题

**Comment by TomCheung00** [comment]
我也是，一个小号之前刷了30级，然后封了
