### ISSUE TITLE
GTA5线上小助手

### ISSUE THREAD

**Issue by okey9845** [CrazyZhang666/GTA5OnlineTools#258]
作者我这个小助手总是检测不到gta5是在打开的状态是怎么啦
我的电脑版本是win7不知道是系统原因还是其他原因

**Comment by CrazyZhang666** [comment]
杀毒拦截了，右键管理员运行

**Comment by okey9845** [comment]
我尝试过了用管理员打开，并且我关闭了防火墙与所有的杀毒软件还是如此，他右下角显示GTA：ON可是我使用外置显示我gta没有打开



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 穗乃果 ***@***.***&gt;
发送时间: 2021年8月19日 12:17
收件人: CrazyZhang666/GTA5OnlineTools ***@***.***&gt;
抄送: okey9845 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[CrazyZhang666/GTA5OnlineTools] GTA5线上小助手 (#258)





 
杀毒拦截了，右键管理员运行
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
C:\ProgramData\GTA5OnlineTools

到这里手动打开Kid看看

**Comment by okey9845** [comment]
还是这样的


但是我的笔记本可以用的，就是有点卡，但是我还是谢谢作者了，非常感谢

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 穗乃果 ***@***.***&gt;
发送时间: 2021年8月19日 12:37
收件人: CrazyZhang666/GTA5OnlineTools ***@***.***&gt;
抄送: okey9845 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[CrazyZhang666/GTA5OnlineTools] GTA5线上小助手 (#258)





 
C:\ProgramData\GTA5OnlineTools
 
到这里手动打开Kid看看
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
