### ISSUE TITLE
无法使用GTAHAX解锁全部公寓抢劫任务

### ISSUE THREAD

**Issue by RRGS666** [CrazyZhang666/GTA5OnlineTools#259]
把如下代码输入完后
**$MPPLY_AWD_COMPLET_HEIST_1STPER
true
$MPPLY_AWD_COMPLET_HEIST_MEM
true
$MPPLY_AWD_FLEECA_FIN
true
$MPPLY_AWD_PRISON_FIN
true
$MPPLY_AWD_HUMANE_FIN
true
$MPPLY_AWD_SERIESA_FIN
true
$MPPLY_AWD_PACIFIC_FIN
true
$MPPLY_AWD_HST_ORDER
true
$MPPLY_AWD_HST_SAME_TEAM
true
$MPPLY_AWD_HST_ULT_CHAL
true
$MPPLY_HEIST_ACH_TRACKER
-1**
只能解锁了相对应的成就，并没有出现任务选择面板，并且打电话给莱斯特也只能重开你完成过的老抢劫（比如我完成了全福和越狱，那之后就只能做这两给公寓抢劫）
如果玩家正在做一个抢劫分红关，这几行代码也没有跳过这个分红关
另外如果要跳过前置，最好还是用STAT自动化脚本
希望能对别的玩家有所帮助

**Comment by CrazyZhang666** [comment]
看教程
https://crazyzhang.cn/gta5/20210801223107.html

**Comment by RRGS666** [comment]
原来是用bigbase,我用的GTAHAX

**Comment by ustinianJJ** [comment]
跳过了奖章都给完成了，犯罪之神都做不了了呃呃呃
