### ISSUE TITLE
使用GTA5HAX刷洛圣都地下车友会等级

### ISSUE THREAD

**Issue by RRGS666** [CrazyZhang666/GTA5OnlineTools#260]
洛圣都地下车友行经验值(int)

**$MP0_CAR_CLUB_REP
99**

_注意:比如你想升至2级 你不能直接注入int值为100 你需要注入一个少一点的数值 比如99 然后自己升即可完成解锁 否则不会解锁东西_

2  = 100
3  = 200
4  = 305
5  = 415
6  = 530
7  = 650
8  = 775
9  = 905
10 = 1040
11 = 1180
12 = 1325
13 = 1475
14 = 1630
15 = 1790
16 = 1955
17 = 2125
18 = 2300
19 = 2480
20 = 2665
21 = 2855
22 = 3050
23 = 3250
24 = 3455
25 = 3665
26 = 3880
27 = 4100
28 = 4325
29 = 4555
30 = 4790
31 = 5030
32 = 5275
33 = 5525
34 = 5780
35 = 6040
36 = 6305
37 = 6575
38 = 6850
39 = 7130
40 = 7415
41 = 7705
42 = 8000
43 = 8300
44 = 8605
45 = 8915
46 = 9230
47 = 9550
48 = 9875
49 = 10205
50 = 10540
51 = 10880
52 = 11225
53 = 11575
54 = 11930
55 = 12290
56 = 12655
57 = 13025
58 = 13400
59 = 13780
60 = 14165
61 = 14555
62 = 14950
63 = 15350
64 = 15755
65 = 16165
66 = 16580
67 = 17000
68 = 17425
69 = 17855
70 = 18290
71 = 18730
72 = 19175
73 = 19625
74 = 20080
75 = 20540
76 = 21005
77 = 21475
78 = 21950
79 = 22430
80 = 22915
81 = 23405
82 = 23900
83 = 24400
84 = 24905
85 = 25415
86 = 25930
87 = 26450
88 = 26975
89 = 27505
90 = 28040
91 = 28580
92 = 29125
93 = 29675
94 = 30230
95 = 30790
96 = 31355
97 = 31925
98 = 32500
99 = 33080
100 = 33665
101 = 34255
102 = 34850
103 = 35450
104 = 36055
105 = 36665
106 = 37280
107 = 37900
108 = 38525
109 = 39155
110 = 39790
111 = 40430
112 = 41075
113 = 41725
114 = 42380
115 = 43040
116 = 43705
117 = 44375
118 = 45050
119 = 45730
120 = 46415
121 = 47105
122 = 47800
123 = 48500
124 = 49205
125 = 49915
126 = 50630
127 = 51350
128 = 52075
129 = 52805
130 = 53540
131 = 54280
132 = 55025
133 = 55775
134 = 56530
135 = 57290
136 = 58055
137 = 58825
138 = 59600
139 = 60380
140 = 61165
141 = 61955
142 = 62750
143 = 63550
144 = 64355
145 = 65165
146 = 65980
147 = 66800
148 = 67625
149 = 68455
150 = 69290
151 = 70130
152 = 70975
153 = 71825
154 = 72680
155 = 73540
156 = 74405
157 = 75275
158 = 76150
159 = 77030
160 = 77915
161 = 78805
162 = 79700
163 = 80600
164 = 81505
165 = 82415
166 = 83330
167 = 84250
168 = 85175
169 = 86105
170 = 87040
171 = 87980
172 = 88925
173 = 89875
174 = 90830
175 = 91790
176 = 92755
177 = 93725
178 = 94700
179 = 95680
180 = 96665
181 = 97655
182 = 98650
183 = 99650
184 = 100655
185 = 101665
186 = 102680
187 = 103700
188 = 104725
189 = 105755
190 = 106790
191 = 107830
192 = 108875
193 = 109925
194 = 110980
195 = 112040
196 = 113105
197 = 114175
198 = 115250
199 = 116330
200 = 117430
201 = 118530
202 = 119630
203 = 120730
204 = 121830
205 = 122930
206 = 124030
207 = 125130
208 = 126230
209 = 127330
210 = 128430
211 = 129530
212 = 130630
213 = 131730
214 = 132830
215 = 133930
216 = 135030
217 = 136130
218 = 137230
219 = 138330
220 = 139430
221 = 140530
222 = 141630
223 = 142730
224 = 143830
225 = 144930
226 = 146030
227 = 147130
228 = 148230
229 = 149330
230 = 150430
231 = 151530
232 = 152630
233 = 153730
234 = 154830
235 = 155930
236 = 157030
237 = 158130
238 = 159230
239 = 160330
240 = 161430
241 = 162530
242 = 163630
243 = 164730
244 = 165830
245 = 166930
246 = 168030
247 = 169130
248 = 170230
249 = 171330
250 = 172430
251 = 173530
252 = 174630
253 = 175730
254 = 176830
255 = 177930
256 = 179030
257 = 180130
258 = 181230
259 = 182330
260 = 183430
261 = 184530
262 = 185630
263 = 186730
264 = 187830
265 = 188930
266 = 190030
267 = 191130
268 = 192230
269 = 193330
270 = 194430
271 = 195530
272 = 196630
273 = 197730
274 = 198830
275 = 199930
276 = 201030
277 = 202130
278 = 203230
279 = 204330
280 = 205430
281 = 206530
282 = 207630
283 = 208730
284 = 209830
285 = 210930
286 = 212030
287 = 213130
288 = 214230
289 = 215330
290 = 216430
291 = 217530
292 = 218630
293 = 219730
294 = 220830
295 = 221930
296 = 223030
297 = 224130
298 = 225230
299 = 226330
300 = 227430
301 = 228530
302 = 229630
303 = 230730
304 = 231830
305 = 232930
306 = 234030
307 = 235130
308 = 236230
309 = 237330
310 = 238430
311 = 239530
312 = 240630
313 = 241730
314 = 242830
315 = 243930
316 = 245030
317 = 246130
318 = 247230
319 = 248330
320 = 249430
321 = 250530
322 = 251630
323 = 252730
324 = 253830
325 = 254930
326 = 256030
327 = 257130
328 = 258230
329 = 259330
330 = 260430
331 = 261530
332 = 262630
333 = 263730
334 = 264830
335 = 265930
336 = 267030
337 = 268130
338 = 269230
339 = 270330
340 = 271430
341 = 272530
342 = 273630
343 = 274730
344 = 275830
345 = 276930
346 = 278030
347 = 279130
348 = 280230
349 = 281330
350 = 282430
351 = 283530
352 = 284630
353 = 285730
354 = 286830
355 = 287930
356 = 289030
357 = 290130
358 = 291230
359 = 292330
360 = 293430
361 = 294530
362 = 295630
363 = 296730
364 = 297830
365 = 298930
366 = 300030
367 = 301130
368 = 302230
369 = 303330
370 = 304430
371 = 305530
372 = 306630
373 = 307730
374 = 308830
375 = 309930
376 = 311030
377 = 312130
378 = 313230
379 = 314330
380 = 315430
381 = 316530
382 = 317630
383 = 318730
384 = 319830
385 = 320930
386 = 322030
387 = 323130
388 = 324230
389 = 325330
390 = 326430
391 = 327530
392 = 328630
393 = 329730
394 = 330830
395 = 331930
396 = 333030
397 = 334130
398 = 335230
399 = 336330
400 = 337430
401 = 338530
402 = 339630
403 = 340730
404 = 341830
405 = 342930
406 = 344030
407 = 345130
408 = 346230
409 = 347330
410 = 348430
411 = 349530
412 = 350630
413 = 351730
414 = 352830
415 = 353930
416 = 355030
417 = 356130
418 = 357230
419 = 358330
420 = 359430
421 = 360530
422 = 361630
423 = 362730
424 = 363830
425 = 364930
426 = 366030
427 = 367130
428 = 368230
429 = 369330
430 = 370430
431 = 371530
432 = 372630
433 = 373730
434 = 374830
435 = 375930
436 = 377030
437 = 378130
438 = 379230
439 = 380330
440 = 381430
441 = 382530
442 = 383630
443 = 384730
444 = 385830
445 = 386930
446 = 388030
447 = 389130
448 = 390230
449 = 391330
450 = 392430
451 = 393530
452 = 394630
453 = 395730
454 = 396830
455 = 397930
456 = 399030
457 = 400130
458 = 401230
459 = 402330
460 = 403430
461 = 404530
462 = 405630
463 = 406730
464 = 407830
465 = 408930
466 = 410030
467 = 411130
468 = 412230
469 = 413330
470 = 414430
471 = 415530
472 = 416630
473 = 417730
474 = 418830
475 = 419930
476 = 421030
477 = 422130
478 = 423230
479 = 424330
480 = 425430
481 = 426530
482 = 427630
483 = 428730
484 = 429830
485 = 430930
486 = 432030
487 = 433130
488 = 434230
489 = 435330
490 = 436430
491 = 437530
492 = 438630
493 = 439730
494 = 440830
495 = 441930
496 = 443030
497 = 444130
498 = 445230
499 = 446330
500 = 447430
501 = 448530
502 = 449630
503 = 450730
504 = 451830
505 = 452930
506 = 454030
507 = 455130
508 = 456230
509 = 457330
510 = 458430
511 = 459530
512 = 460630
513 = 461730
514 = 462830
515 = 463930
516 = 465030
517 = 466130
518 = 467230
519 = 468330
520 = 469430

**Comment by CrazyZhang666** [comment]
我网站写了好多篇车友会等级教程，对应的工具也早就制作好了，你这是干嘛我没看懂
![image](https://user-images.githubusercontent.com/28080853/130081276-400cc23e-347c-45dd-a22b-688752b5c0f8.png)

**Comment by RRGS666** [comment]
2  = 100
3  = 200
4  = 305
5  = 415
6  = 530
7  = 650
8  = 775
9  = 905
10 = 1040
11 = 1180
12 = 1325
13 = 1475
14 = 1630
15 = 1790
16 = 1955
17 = 2125
18 = 2300
19 = 2480
20 = 2665
21 = 2855
22 = 3050
23 = 3250
24 = 3455
25 = 3665
26 = 3880
27 = 4100
28 = 4325
29 = 4555
30 = 4790
31 = 5030
32 = 5275
33 = 5525
34 = 5780
35 = 6040
36 = 6305
37 = 6575
38 = 6850
39 = 7130
40 = 7415
41 = 7705
42 = 8000
43 = 8300
44 = 8605
45 = 8915
46 = 9230
47 = 9550
48 = 9875
49 = 10205
50 = 10540
51 = 10880
52 = 11225
53 = 11575
54 = 11930
55 = 12290
56 = 12655
57 = 13025
58 = 13400
59 = 13780
60 = 14165
61 = 14555
62 = 14950
63 = 15350
64 = 15755
65 = 16165
66 = 16580
67 = 17000
68 = 17425
69 = 17855
70 = 18290
71 = 18730
72 = 19175
73 = 19625
74 = 20080
75 = 20540
76 = 21005
77 = 21475
78 = 21950
79 = 22430
80 = 22915
81 = 23405
82 = 23900
83 = 24400
84 = 24905
85 = 25415
86 = 25930
87 = 26450
88 = 26975
89 = 27505
90 = 28040
91 = 28580
92 = 29125
93 = 29675
94 = 30230
95 = 30790
96 = 31355
97 = 31925
98 = 32500
99 = 33080
100 = 33665
101 = 34255
102 = 34850
103 = 35450
104 = 36055
105 = 36665
106 = 37280
107 = 37900
108 = 38525
109 = 39155
110 = 39790
111 = 40430
112 = 41075
113 = 41725
114 = 42380
115 = 43040
116 = 43705
117 = 44375
118 = 45050
119 = 45730
120 = 46415
121 = 47105
122 = 47800
123 = 48500
124 = 49205
125 = 49915
126 = 50630
127 = 51350
128 = 52075
129 = 52805
130 = 53540
131 = 54280
132 = 55025
133 = 55775
134 = 56530
135 = 57290
136 = 58055
137 = 58825
138 = 59600
139 = 60380
140 = 61165
141 = 61955
142 = 62750
143 = 63550
144 = 64355
145 = 65165
146 = 65980
147 = 66800
148 = 67625
149 = 68455
150 = 69290
151 = 70130
152 = 70975
153 = 71825
154 = 72680
155 = 73540
156 = 74405
157 = 75275
158 = 76150
159 = 77030
160 = 77915
161 = 78805
162 = 79700
163 = 80600
164 = 81505
165 = 82415
166 = 83330
167 = 84250
168 = 85175
169 = 86105
170 = 87040
171 = 87980
172 = 88925
173 = 89875
174 = 90830
175 = 91790
176 = 92755
177 = 93725
178 = 94700
179 = 95680
180 = 96665
181 = 97655
182 = 98650
183 = 99650
184 = 100655
185 = 101665
186 = 102680
187 = 103700
188 = 104725
189 = 105755
190 = 106790
191 = 107830
192 = 108875
193 = 109925
194 = 110980
195 = 112040
196 = 113105
197 = 114175
198 = 115250
199 = 116330
200 = 117430
201 = 118530
202 = 119630
203 = 120730
204 = 121830
205 = 122930
206 = 124030
207 = 125130
208 = 126230
209 = 127330
210 = 128430
211 = 129530
212 = 130630
213 = 131730
214 = 132830
215 = 133930
216 = 135030
217 = 136130
218 = 137230
219 = 138330
220 = 139430
221 = 140530
222 = 141630
223 = 142730
224 = 143830
225 = 144930
226 = 146030
227 = 147130
228 = 148230
229 = 149330
230 = 150430
231 = 151530
232 = 152630
233 = 153730
234 = 154830
235 = 155930
236 = 157030
237 = 158130
238 = 159230
239 = 160330
240 = 161430
241 = 162530
242 = 163630
243 = 164730
244 = 165830
245 = 166930
246 = 168030
247 = 169130
248 = 170230
249 = 171330
250 = 172430
251 = 173530
252 = 174630
253 = 175730
254 = 176830
255 = 177930
256 = 179030
257 = 180130
258 = 181230
259 = 182330
260 = 183430
261 = 184530
262 = 185630
263 = 186730
264 = 187830
265 = 188930
266 = 190030
267 = 191130
268 = 192230
269 = 193330
270 = 194430
271 = 195530
272 = 196630
273 = 197730
274 = 198830
275 = 199930
276 = 201030
277 = 202130
278 = 203230
279 = 204330
280 = 205430
281 = 206530
282 = 207630
283 = 208730
284 = 209830
285 = 210930
286 = 212030
287 = 213130
288 = 214230
289 = 215330
290 = 216430
291 = 217530
292 = 218630
293 = 219730
294 = 220830
295 = 221930
296 = 223030
297 = 224130
298 = 225230
299 = 226330
300 = 227430
301 = 228530
302 = 229630
303 = 230730
304 = 231830
305 = 232930
306 = 234030
307 = 235130
308 = 236230
309 = 237330
310 = 238430
311 = 239530
312 = 240630
313 = 241730
314 = 242830
315 = 243930
316 = 245030
317 = 246130
318 = 247230
319 = 248330
320 = 249430
321 = 250530
322 = 251630
323 = 252730
324 = 253830
325 = 254930
326 = 256030
327 = 257130
328 = 258230
329 = 259330
330 = 260430
331 = 261530
332 = 262630
333 = 263730
334 = 264830
335 = 265930
336 = 267030
337 = 268130
338 = 269230
339 = 270330
340 = 271430
341 = 272530
342 = 273630
343 = 274730
344 = 275830
345 = 276930
346 = 278030
347 = 279130
348 = 280230
349 = 281330
350 = 282430
351 = 283530
352 = 284630
353 = 285730
354 = 286830
355 = 287930
356 = 289030
357 = 290130
358 = 291230
359 = 292330
360 = 293430
361 = 294530
362 = 295630
363 = 296730
364 = 297830
365 = 298930
366 = 300030
367 = 301130
368 = 302230
369 = 303330
370 = 304430
371 = 305530
372 = 306630
373 = 307730
374 = 308830
375 = 309930
376 = 311030
377 = 312130
378 = 313230
379 = 314330
380 = 315430
381 = 316530
382 = 317630
383 = 318730
384 = 319830
385 = 320930
386 = 322030
387 = 323130
388 = 324230
389 = 325330
390 = 326430
391 = 327530
392 = 328630
393 = 329730
394 = 330830
395 = 331930
396 = 333030
397 = 334130
398 = 335230
399 = 336330
400 = 337430
401 = 338530
402 = 339630
403 = 340730
404 = 341830
405 = 342930
406 = 344030
407 = 345130
408 = 346230
409 = 347330
410 = 348430
411 = 349530
412 = 350630
413 = 351730
414 = 352830
415 = 353930
416 = 355030
417 = 356130
418 = 357230
419 = 358330
420 = 359430
421 = 360530
422 = 361630
423 = 362730
424 = 363830
425 = 364930
426 = 366030
427 = 367130
428 = 368230
429 = 369330
430 = 370430

**Comment by RRGS666** [comment]
我这才看到作者也更教程了
[](https://crazyzhang.cn/gta5/20210801121553.html#%E6%95%99%E7%A8%8B)
