### ISSUE TITLE
GTAHAX解锁奖章代码大全

### ISSUE THREAD

**Issue by RRGS666** [CrazyZhang666/GTA5OnlineTools#261]
这里名钻的奖章代码不全
小助手中还没有解锁奖章的功能，这里把HAX代码放出来

$MP0_AWD_5STAR_WANTED_AVOIDANCE           瞒天过海
50

$MP0_AWD_FMSHOOTDOWNCOPHELI               当猪也会飞时
25

$MP0_PLAYER_HEADSHOTS                     呼啸而过
500

$MP0_AWD_VEHICLES_JACKEDR                 偷车贼
500

$MP0_AWD_HOLD_UP_SHOPS                    武装劫匪
20

$MP0_AWD_100_KILLS_SMG                 冲锋狂人
500

$MP0_AWD_20_KILLS_MELEE                近战杀手
50

$MP0_SAWNOFF_ENEMY_KILLS               霰弹蓝调
500

$MP0_SNIPERRFL_ENEMY_KILLS             登高望远
500

$MP0_AWD_25_KILLS_STICKYBOMBS          惊爆危机
50

$MP0_AWD_TIME_IN_HELICOPTER            云霄之上
4

$MP0_AIR_LAUNCHES_OVER_40M             飞行
25

$MP0_AWD_CARS_EXPORTED                 出口大王
50

$MP0_AWD_FM_SHOOTRANG_CT_WON           虚晃掩护
25

$MP0_AWD_FM_SHOOTRANG_RT_WON           射手
25

$MP0_AWD_WIN_LAST_TEAM_STANDINGS       屹立不倒
50

$MP0_AWD_ONLY_PLAYER_ALIVE_LTS         独一无二
50

$MPPLY_AWD_GANGOPS_CRIMMASMD           犯罪之神4

$MPPLY_AWD_GANGOPS_LOYALTY2            忠诚伙伴2

$MP0_AWD_FIRST_TIME1                   解救陈陶

$MP0_AWD_FIRST_TIME2                   日常杂务

$MP0_AWD_SURVIVALIST                   运气运气

**Comment by RRGS666** [comment]
办公室统计数据代码(int)

$MP0_LIFETIME_BUY_UNDERTAKEN           取货次数
1000

$MP0_LIFETIME_BUY_COMPLETE             已完成取货次数
1000

$MP0_LIFETIME_SELL_UNDERTAKEN          销售次数
100

$MP0_LIFETIME_SELL_COMPLETE            成功销售次数
100

$MP0_LIFETIME_CONTRA_EARNINGS          总收入
20000000

**Comment by SoulYelling** [comment]
关于游戏厅的断袖诅咒游戏机，有相关的三个奖章，其中一个奖章是零钱包，解锁代码是？
