### ISSUE TITLE
奖章

### ISSUE THREAD

**Issue by ustinianJJ** [CrazyZhang666/GTA5OnlineTools#263]
奖章代码如何用

**Comment by RRGS666** [comment]
打开hax 注意最下方可输入的两个文本框
假如我想解锁“瞒天过海”这个奖章
上面输入
**$MP0_AWD_5STAR_WANTED_AVOIDANCE**
下面输入
**50**
其它奖章同理
再点击int锁定就ok了
一般int代码修改成功后游戏里会弹出一个成就就成功了
_小助手里也有这个功能_
