### ISSUE TITLE
关于上岛快速245万的bug

### ISSUE THREAD

**Issue by suixin5201** [CrazyZhang666/GTA5OnlineTools#267]
您好，我在使用您开发的小助手内置的佩里克岛速通245万的工具时，发现上岛人数为1时一切正常。当人数大于1时，我在"切到小助手，我现在是1人，我们点一下1人，右下角会有成功提示，如果是2人玩家就点一下2人，依次类推"这一步时，当我战局有3人，我选择人数3，我会从分红界面直接退出，回到正常游戏内。当我人数为2时，我选择2，则可以正常开启上岛任务。
但是，不论是几人，只要游戏人数大于1，当我在速通245w工具内选择了对应的人数后，游戏内的分红仅有我会变成100%，其余人一律是135%的分红，当我们完成一把后，我是245万的分红，其余人是330万的分红（当然，这个钱数到不了账）。
我全程都是按照您的网站教程来的，但是我一晚上和队友上了4此，每次都是这种情况。当人数为3时，无法开启直接退出；当人数为2时，可以正常开始。当人数大于1时，分红会不正常。
麻烦您研究研究，感谢！

**Comment by CrazyZhang666** [comment]
这是正常的，因为只有分红比例你改了其他玩家也会改，主要目标价值和倒卖费用你改了别的玩家还是原来的，只有你自己是改了，145%分红别的玩家才能拿到245w，否则190W x100%x(1-0.12)=130w左右，你倒着推算，只能把100%分红提高到145%才可以让其他玩家拿到245w，否则就要去拿次要目标，你自己研究一下原理

**Comment by ssrs2357883858** [comment]
这个问题我之前也遇到过，我猜你应该是在拿到主要目标后没有再次点击对应分红人数，你只需要在拿到主要目标后点击对应人数即可
