### ISSUE TITLE
办公室铺满钱和小金人没有成功（自动化脚本里的）

### ISSUE THREAD

**Issue by whitelist638** [CrazyZhang666/GTA5OnlineTools#268]

**Comment by CrazyZhang666** [comment]
这个还需要CEO进出货一次

**Comment by YukikazeDA** [comment]
> 这个还需要CEO进出货一次

办公室都是钱这个有办法再取消吗 弄上之后感觉太难看了

**Comment by CrazyZhang666** [comment]
导入到GTAHax

```
INT32
$MPx_LIFETIME_BUY_UNDERTAKEN
0
$MPx_LIFETIME_BUY_COMPLETE
0
$MPx_LIFETIME_SELL_UNDERTAKEN
0
$MPx_LIFETIME_SELL_COMPLETE
0
$MPx_LIFETIME_CONTRA_EARNINGS
0
```

**Comment by YukikazeDA** [comment]
> 哥特哈克斯
> 
> ```
> INT32
> $MPx_LIFETIME_BUY_UNDERTAKEN
> 0
> $MPx_LIFETIME_BUY_COMPLETE
> 0
> $MPx_LIFETIME_SELL_UNDERTAKEN
> 0
> $MPx_LIFETIME_SELL_COMPLETE
> 0
> $MPx_LIFETIME_CONTRA_EARNINGS
> 0
> ```

![image](https://user-images.githubusercontent.com/89716381/131240622-e889a36b-6cc0-417f-bfdc-082d32e9ea6b.png)
 感谢 
少了很多  不过还有几堆

**Comment by YukikazeDA** [comment]
> 哥特哈克斯
> 
> ```
> INT32
> $MPx_LIFETIME_BUY_UNDERTAKEN
> 0
> $MPx_LIFETIME_BUY_COMPLETE
> 0
> $MPx_LIFETIME_SELL_UNDERTAKEN
> 0
> $MPx_LIFETIME_SELL_COMPLETE
> 0
> $MPx_LIFETIME_CONTRA_EARNINGS
> 0
> ```

![image](https://user-images.githubusercontent.com/89716381/131240655-d1e1a486-ca37-4296-ab28-ffd4cf45d3c2.png)
感谢帮助
少了很多 不过还有一些
