### ISSUE TITLE
BUG反馈2021年3月11日-关于跳过赌场前置

### ISSUE THREAD

**Issue by xiaolvqq51** [CrazyZhang666/GTA5OnlineTools#27]
作者你好，个人在使用中发现以下一些问题:
1.赌场前置第一块面板跳过之后，在第二块面板按照教程勾选，选好导入gtaahax完成切回去也会黑屏，但是黑屏之后第三块面板并不会有东西，发现是因为第二块面板的武器逃亡载具和黑客都没有选择（即使在工具里勾选了），需要手动选择好才行
2.当新岛屿抢劫任务结束后单独勾选跳过冷却好像没有用，必须要一同勾选重置才行

**Comment by CrazyZhang666** [comment]
> 作者你好，个人在使用中发现以下一些问题:
> 1.赌场前置第一块面板跳过之后，在第二块面板按照教程勾选，选好导入gtaahax完成切回去也会黑屏，但是黑屏之后第三块面板并不会有东西，发现是因为第二块面板的武器逃亡载具和黑客都没有选择（即使在工具里勾选了），需要手动选择好才行
> 2.当新岛屿抢劫任务结束后单独勾选跳过冷却好像没有用，必须要一同勾选重置才行

这个我其实也没办法，毕竟跳过赌场就是那些代码，这是游戏内部固定的，
如果没效果或者效果不理想就切换战局重新导入，或者手动做几个任务，或者让莱斯特重新开启任务

**Comment by CrazyZhang666** [comment]
> 作者你好，个人在使用中发现以下一些问题:
> 1.赌场前置第一块面板跳过之后，在第二块面板按照教程勾选，选好导入gtaahax完成切回去也会黑屏，但是黑屏之后第三块面板并不会有东西，发现是因为第二块面板的武器逃亡载具和黑客都没有选择（即使在工具里勾选了），需要手动选择好才行
> 2.当新岛屿抢劫任务结束后单独勾选跳过冷却好像没有用，必须要一同勾选重置才行

可以使用此代码重置赌场面板
INT32
$MPx_H3OPT_BITSET1
0
$MPx_H3OPT_BITSET0
0
$MPx_H3OPT_POI
0
$MPx_H3OPT_ACCESSPOINTS
0
$MPx_CAS_HEIST_FLOW
0
