### ISSUE TITLE
BigBaseV2注入工具的界面跟教程完全不一样了

### ISSUE THREAD

**Issue by Prodemode** [CrazyZhang666/GTA5OnlineTools#273]
工具的界面变成两个 第一个能够正常使用 但在我重启游戏后第一个界面就不见了 第二个界面没有见过 没法使用 重装小助手和验证游戏文件都没法解决

**Comment by Prodemode** [comment]
注入工具的选项变成了Bread和Packed Stat Editor    Bread无法打开 Packed Stat Editor第一次打开的时候使用界面跟第一次使用大概相同，但在我重启之后没法在正常利用注入工具修改 第一个界面在经过各种修复之后也没法再显示出来 第二个界面教程里没有见过 所以也没法使用

**Comment by Prodemode** [comment]
第二个界面是个可以拉下和隐藏的列表 退出也会导致游戏直接闪退 第一个界面和更新前一模一样并且可以使用 我用它修改了行走数据且已经保存 但在重启游戏过后第一个可以使用的界面便不见了 同时在启动注入工具的时候那段黑屏也不再自动输入代码 而是空的

**Comment by 755146450** [comment]
汉化一下Packed stat editor就好了
