### ISSUE TITLE
游戏厅

### ISSUE THREAD

**Issue by ustinianJJ** [CrazyZhang666/GTA5OnlineTools#274]
啥情况呀这是，做任务也不能给莱斯特拍照
![Grand Theft Auto V Screenshot 2021 08 24 - 22 36 13 01](https://user-images.githubusercontent.com/89016902/130636422-742d609f-5720-4b37-892b-ad7834b9d0ff.png)

**Comment by CrazyZhang666** [comment]
使用这个重置下
![image](https://user-images.githubusercontent.com/28080853/131256224-132fd940-99f1-4407-af8f-4be8512f0d2a.png)
