### ISSUE TITLE
245W失效

### ISSUE THREAD

**Issue by jinshilin35** [CrazyZhang666/GTA5OnlineTools#278]
我今天邀请战局（小助手过去的）开了两次小岛，间隔一小时以上，按照教程要求完成了所有步骤，最后结算也是245，但是最终钱并没有到账，银行里有退款记录。尝试两次都失败了，然后我正常进行了一次，钱就到账了，不知道是什么问题，反馈一下。

**Comment by CrazyZhang666** [comment]
可能吧，我也不太清楚
