### ISSUE TITLE
小助手安装完成，点击打开后程序自动消失

### ISSUE THREAD

**Issue by muxiawuyun** [CrazyZhang666/GTA5OnlineTools#281]
已经按照网站上的文章操作，已经把所有杀毒报错的都关闭了且已安装运行库与微软常用运行库合集，打开之后程序依旧自动消失

**Comment by muxiawuyun** [comment]
@CrazyZhang666

**Comment by CrazyZhang666** [comment]
小助手不需要安装，请使用最新版本小助手

**Comment by muxiawuyun** [comment]
> 小助手无需安装，请使用最新版本的小助手

就是最新版本的小助手 打开以后自动消失。。。
