### ISSUE TITLE
3.16更新之后部分功能无效

### ISSUE THREAD

**Issue by Aprilsay** [CrazyZhang666/GTA5OnlineTools#29]
1·kiddion无法打开
2·小助手外置菜单中消除警星无效，高级功能无效，战局玩家无法读取

**Comment by Szzz313** [comment]
我这也无法打开了

**Comment by Szzz313** [comment]
![Uploading 4389542228a3fd0b.png…]()

**Comment by CrazyZhang666** [comment]
已更新，请使用最新版本小助手
Updated, please use the latest version of GTA5OnlineTools
