### ISSUE TITLE
小助手bug反馈

### ISSUE THREAD

**Issue by polixiang** [CrazyZhang666/GTA5OnlineTools#294]
小助手使用过程中出现闪退现象，具体表现是进游戏游玩后，使用小助手后闪退几率增大，仅仅是普通的无敌传送啥的，其中有一次是进游戏后没有使用助手功能夜闪退，有一半的闪退发生在佩里克岛任务期间，一次发生在地堡出货期间，一次发生在没有任何操作期间，也就是挂机，希望能解决，

**Comment by gta5plyaer** [comment]
我也是，莫名闪退次数暴增

**Comment by gta5plyaer** [comment]
以前的版本这个bug不多，现在闪退次数暴增

**Comment by gta5plyaer** [comment]
以前这个问题我提出过，但是被认为不是小助手的问题。
那时候闪退次数并不多
但是现在最新版本闪退次数暴增，导致我不得不退游

**Comment by gta5plyaer** [comment]
刚才实测了一下，使用旧版小助手3.0.0.1版本崩溃概率为0
