### ISSUE TITLE
开启助手后游戏卡退问题

### ISSUE THREAD

**Issue by sxp521** [CrazyZhang666/GTA5OnlineTools#3]
自更新2.9.5.2和2.5.9.3小助手版本后 在gta5在线模式中 打开小助手后10分钟内就会出现卡退问题，没有任何征兆 直接掉出游戏 这在之前的版本从来没有出现过 是否可以告知解决办法

**Comment by CrazyZhang666** [comment]
你要详细描述下你打开小助手然后做了什么（包括使用的任何功能，点击的任何按钮），还是仅仅只是打开小助手？

**Comment by wyggg** [comment]
我有遇到过相似的情况，当外置菜单和kid同时开启的时候有可能会照成游戏不稳定，所以我一般都只用外置菜单

**Comment by sxp521** [comment]
我是打开辅助栏第二个窗口 开无敌，和无限体力，然后时间一久自己就掉了 也就是更新的这两个版本才会这样 以前都是正常的。

**Comment by CrazyZhang666** [comment]
你说下你使用sub正常的小助手最后一个版本号，历史版本天翼云盘有，不能随便说版本号，否则我无法定位问题所在

**Comment by sxp521** [comment]
最后可以正常使用的是2.5.9.1  在此之后更新的版本就会出现掉线问题

**Comment by CrazyZhang666** [comment]
但是sub这个软件已经很久没有改动了，你可以试试原版sub看看，看下有没有问题https://github.com/CrazyZhang666/subVerison_GTAV_Hack，这个主要和玩家系统环境有关
