### ISSUE TITLE
3.16辅助菜单部分功能失效

### ISSUE THREAD

**Issue by Szzz313** [CrazyZhang666/GTA5OnlineTools#30]
kiddion打不开
![4389542228a3fd0b](https://user-images.githubusercontent.com/80799721/111404418-b2412000-8709-11eb-9d7e-4fe2e8ecbe8a.png)

**Comment by pessimist824** [comment]
我的也是，用不了了

**Comment by pessimist824** [comment]
你解决了吗

**Comment by Szzz313** [comment]
没

**Comment by Szzz313** [comment]
等开发大佬吧

**Comment by Szzz313** [comment]
昨天还能用

**Comment by pessimist824** [comment]
好吧，应该是游戏更新用不了了

**Comment by pessimist824** [comment]
我都是只玩线下的

**Comment by CrazyZhang666** [comment]
已更新，请使用最新版本小助手
Updated, please use the latest version of GTA5OnlineTools
