### ISSUE TITLE
小助手外置菜单载具刷出选项无反应

### ISSUE THREAD

**Issue by wanzdhan** [CrazyZhang666/GTA5OnlineTools#305]
小助手外置菜单中“刷出线上载具A”和“刷出线上载具B”都不能用，点击无反应

**Comment by CrazyZhang666** [comment]
你先用小助手切换下战局，然后再刷一下载具，或者直接使用kiddion的刷载具

**Comment by 2loveGitHub** [comment]
大佬救救我们吧   游戏更新了T.T 好多功能用不了  

来自你的粉丝留言

**Comment by 2loveGitHub** [comment]
> 你先用小助手切换下战局，然后再刷一下载具，或者直接使用kiddion的刷载具

大佬救救我们吧 游戏更新了T.T 好多功能用不了

来自你的粉丝留言
