### ISSUE TITLE
[！！！两次跳前置不要间隔太短！！！]使用小助手已经被封了四个号-封号都是在两天以内-[已经进行自我排查并发现问题]

### ISSUE THREAD

**Issue by Suntz246** [CrazyZhang666/GTA5OnlineTools#307]
四个号封号总结：小岛前置跳的过于频繁，比如我我15分钟一把小岛，然后就立马继续跳前置，并且一把240w+大家引以为戒

=============================
使用的功能有：
**1.使用GTAHax代码导入期跳过小岛前置赌场前置
2.使用单人金钱经验里的单人战局拉货
3.使用小助手的无敌传送无限子弹无物理碰撞
4.使用kiddion传送纪念品
5.使用kiddion解锁特殊衣服武器**

没有和任何人撕逼，没有用小助手刷钱，公开战局秒切换单人战局，没有用小助手以外的任何辅助

系统是win10-21H1-19043.1320
没有安装360，使用的火绒
加速器使用的UU

**Comment by CrazyZhang666** [comment]
4.使用kiddion传送纪念品
5.使用kiddion解锁特殊衣服武器

这个解锁也是有一定风险的，尤其是解锁限定物品

**Comment by Suntz246** [comment]
> 4.使用kiddion传送纪念品 5.使用kiddion解锁特殊衣服武器
> 
> 这个解锁也是有一定风险的，尤其是解锁限定物品
