### ISSUE TITLE
3月16日更新后地堡出货数量修改

### ISSUE THREAD

**Issue by MapleXP** [CrazyZhang666/GTA5OnlineTools#31]
触发地堡研究和生产无法使用
![Image](https://user-images.githubusercontent.com/25141783/111411134-fc7bce80-8714-11eb-9a6c-a6f4c35d14bf.png)

**Comment by MapleXP** [comment]
点了有提示但游戏没有任何反应
![Image](https://user-images.githubusercontent.com/25141783/111411306-406ed380-8715-11eb-857b-546624e170d0.png)

**Comment by Herrycao** [comment]
昨天试了一下 可以2次 但后面 一直都刷新不上了 不知道是什么回事

**Comment by ajie63** [comment]
你还好能刷两次我一次都刷不了

**Comment by CrazyZhang666** [comment]
我测试是可以使用的，如果不行就出一次货试试看或者手动偷取一次原料，我是epic版本测试的

**Comment by Herrycao** [comment]
我现在能刷了 刷武器比出货那个收益更高

從我的 iPhone 傳送
