### ISSUE TITLE
什么时候更新呢？ GTA5更新 小助手好多功能不能用了。

### ISSUE THREAD

**Issue by 793329316** [CrazyZhang666/GTA5OnlineTools#331]

**Comment by Williamwang-wh** [comment]
我也是同样的问题

**Comment by ZhangBeihai-github** [comment]
小助手没法用了😭

**Comment by buddse** [comment]
什么时候才更新

**Comment by huxiaoyu520** [comment]
更新了1.58很多东西都无法使用了，怎么办呀，作者什么时候来更新哈嘛
、

**Comment by qwertyuiopaz095** [comment]
不知道了，我使用只使用外置菜单的，不过菜单也有好多失效了

**Comment by 793329316** [comment]
反馈，&nbsp; &nbsp;小助手有个BUG&nbsp; 打开第三方辅助里面的第一个，在游戏里用&nbsp;有时候会出现无法开枪，奔跑加鼠标右键会卡住不能开枪，切换枪也不行，上车下车才可以。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月18日(星期六) 上午10:52
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 什么时候更新呢？ GTA5更新 小助手好多功能不能用了。 (Issue #331)





 
不知道了，我使用只使用外置菜单的，不过菜单也有好多失效了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
