### ISSUE TITLE
老哥，老哥，gta5更新了，大多数功能都失效啦

### ISSUE THREAD

**Issue by louisyqh819** [CrazyZhang666/GTA5OnlineTools#338]
老哥，加油！！！

**Comment by JovanyJoestar** [comment]
> 老哥，加油！！！

确实，这个老哥可能现在开始肝代码了，等几天吧

**Comment by qwertyuiopaz095** [comment]
张总加油

**Comment by qwertyuiopaz095** [comment]
大哥，生病了😷，好久没来玩了，看最近菜单大更新了，今天看了一下，好多载具的东西也修复了，不过我很好奇，就问下，那个新出的注入式菜单有什么功能呢，问下，当然我自己不敢使用



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月21日 18:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 老哥，老哥，gta5更新了，大多数功能都失效啦 (Issue #338) |

Closed #338.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
> 大哥，生病了😷，好久没来玩了，看最近菜单大更新了，今天看了一下，好多载具的东西也修复了，不过我很好奇，就问下，那个新出的注入式菜单有什么功能呢，问下，当然我自己不敢使用
> 
> 
> 
> ---- 回复的原邮件 ----
> | 发件人 | ***@***.***> |
> | 日期 | 2021年12月21日 18:23 |
> | 收件人 | ***@***.***> |
> | 抄送至 | ***@***.******@***.***> |
> | 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 老哥，老哥，gta5更新了，大多数功能都失效啦 (Issue #338) |
> 
> Closed #338.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you commented.Message ID: ***@***.***>

我那个注入式菜单可以放心使用，全部用指针实现的，没有调用本地函数，不过功能目前比较单一，只有esp功能
