### ISSUE TITLE
GTAOL bug report

### ISSUE THREAD

**Issue by qwertyuiopaz095** [CrazyZhang666/GTA5OnlineTools#347]
张总，很感谢你这次的紧急更新呢，不过，随着新版本的到来，原有的小助手功能外置菜单也开始有bug了呢，虽然说你知道会有bug，但是我还是来向你反馈一些，1.一个很久的bug，就是飞机载具列表里的“任务道具客机”，它的尾部是缺失一部分的，虽然说不影响什么：），2.飞机载具随新版本出现的问题，所有的飞行载具在刷新的时候起落架被改为了收起，所以在刷新的时候会受重力下落，然后坠毁，这个很头疼啊，希望修复，3.还有一直以来很久的紧急车辆，部分车辆上面是没有警报灯的，挺影响美观的，还有喇叭能改成原厂的么，老是听的怪怪的，是普通车改了没什么，警车没警笛没灵魂了，4.修复载具按钮失效了，一直会刷新牛鲨睾酮效果却迟迟无法修复，5.刷武器失效，经过测试任何武器均已经无法刷出，6哈哈哈希望更新合约任务载具玩玩，还有部分枪械并没有出现在刷武器列表里，按理来说应该更新下了吧，与时俱进，哦哦哦，还有，能不能做载具刷出颜色随机，总是只有那一种颜色，还有外置菜单栏似乎删掉了些什么。。。。好了，我的反馈就到这里了，非常感谢你制作的小助手，方便了我们在GTAOL中苟活，至少免受大哥之苦 @CrazyZhang666

**Comment by CrazyZhang666** [comment]
感谢支持
1，2，3这个还没研究怎么修复，有时间看看
4，这个功能目前移除了
5，已经修复了
6，新载具还未添加，下次更新加入新载具和武器
目前刷出的载具颜色是随机的，以后会陆续加入自定义功能

**Comment by qwertyuiopaz095** [comment]
唔?不是吧，修复功能移除了？啊啊啊，对于我这种经常要点修复载具功能的人就是灾难😭，不过，最近又发现了一些针对外置菜单的新问题


1.切换战局功能失效，点击此区的任何按钮都是返回线下 2.其实是很久的了，就是飞行类载具，玻璃透明度可以设置为淡一点吗，都是改成了“礼车”程度，所以只能地三人称开飞机 3.不算bug，就是希望可做优化一下，就是新版本(v1.58)，电击枪回复速度非常慢，可以针对其制作一个加快回复的吗 4.贿赂当局或贿赂警车等按钮(此区全部六键，功能全部失效) 5.哈，既然移除了修复功能，下次可以做载具无敌加强版吗，就是载具的全部都不会损坏(包括窗户，车灯等)，既然可以做自定义改色，自定义配件应该可以吧？看过一人，他的单车上空顶着出租车灯牌，哈哈，要是能改个警灯在车顶上，帅爆，k，上次一大哥，我开着警车，突然把我警车颜色改成红色，离谱
以上就是最新发现的问题，有些可能忘记了没想起来，不过谢谢可以做这样一个安全，稳定的辅助功能
玩笑:GTA在线刷金，一元一亿，人工刷金安全稳定，现在下单还送1-5亿
[人工代练，大表哥2金条，低价解封，安全稳定]有意请加wx:xxxxxx






---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月20日 17:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] GTAOL bug report (Issue #347) |

感谢支持
1，2，3这个还没研究怎么修复，有时间看看
4，这个功能目前移除了
5，已经修复了
6，新载具还未添加，下次更新加入新载具和武器
目前刷出的载具颜色是随机的，以后会陆续加入自定义功能

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrazyZhang666** [comment]
1. 切换战局功能正常啊
2.这个还没时间弄
3.没注意这个
4.CEO能力功能有效果，没效果需要切换战局
5.目前载具无敌是载具血量不会掉，载具外观是分开的
6.不做刷钱广告

**Comment by qwertyuiopaz095** [comment]
6.你误会了哈哈哈，只是玩笑



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月21日 13:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] GTAOL bug report (Issue #347) |

切换战局功能正常啊
2.这个还没时间弄
3.没注意这个
4.CEO能力功能有效果，没效果需要切换战局
5.目前载具无敌是载具血量不会掉，载具外观是分开的
6.不做刷钱广告

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
