### ISSUE TITLE
小助手抢劫任务代码导入无反应

### ISSUE THREAD

**Issue by WEjnx3** [CrazyZhang666/GTA5OnlineTools#348]
在赌场豪杰导入编辑器打勾后，进入游戏无反应，不会像以前黑一下屏幕，前置任务还是要自己做，你们看下具体是我一个人的问题，还是哟u其他人也在反馈

**Comment by CrazyZhang666** [comment]
已经更新了，重启小助手即可收到更新推送

**Comment by WEjnx3** [comment]
我试了很多次重启了电脑和小助手，还是这样只显示INT32，进游戏面板也不会变黑，但是第一块面板是正常的，出现问题是2022年10月20号更新以后才出现的，之前是正常的，希望能解决一下，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月21日(星期二) 晚上6:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 小助手抢劫任务代码导入无反应 (Issue #348)





 
Closed #348.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
