### ISSUE TITLE
上岛的249万无效

### ISSUE THREAD

**Issue by qq625970512** [CrazyZhang666/GTA5OnlineTools#349]
实际只有110万单人

**Comment by SplendorAnLin** [comment]
等修复

**Comment by SplendorAnLin** [comment]
> 实际只有110万单人

等修复！

**Comment by CrazyZhang666** [comment]
已经更新了，重启小助手即可收到更新推送

**Comment by CrazyZhang666** [comment]
> 刚试了一次还是只入账114W

分红比例为218%，注意修改，114是100%分红

**Comment by HarleyQuinn0201** [comment]
> > 刚试了一次还是只入账114 W
> 
> 分红比例为218%，注意修改，114是100%分红

可以麻烦教一下如何修改分红比例吗 万分感谢
