### ISSUE TITLE
更新gta5线上小助手

### ISSUE THREAD

**Issue by thor794** [CrazyZhang666/GTA5OnlineTools#351]

**Comment by CrazyZhang666** [comment]
已经更新了，重启小助手即可收到更新推送

**Comment by thor794** [comment]
你们好久更新其他两个



| |
thoth796
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月20日 17:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 更新gta5线上小助手 (Issue #351) |

已经更新了，重启小助手即可收到更新推送

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
