### ISSUE TITLE
大哥！该更新了！

### ISSUE THREAD

**Issue by ywdajb** [CrazyZhang666/GTA5OnlineTools#353]
大哥！该更新了！大哥！该更新了！大哥！该更新了！

**Comment by CrazyZhang666** [comment]
已经更新了，重启小助手即可收到更新推送

**Comment by ywdajb** [comment]
> 已经更新了，重启小助手即可收到更新推送

大哥，地堡刷钱什么时候更新呀

**Comment by CrazyZhang666** [comment]
> > 已经更新了，重启小助手即可收到更新推送
> 
> 大哥，地堡刷钱什么时候更新呀

地堡刷钱已经更新了啊

**Comment by ywdajb** [comment]
> > > 已经更新了，重启小助手即可收到更新推送
> > 
> > 
> > 大哥，地堡刷钱什么时候更新呀
> 
> 地堡刷钱已经更新了啊

大哥，是那个第三方辅助里的地堡刷钱

**Comment by CrazyZhang666** [comment]
第三方辅助我也不知道啥时候更新，听别人说kiddion要等到明年才更新

**Comment by ywdajb** [comment]
> 第三方辅助我也不知道啥时候更新，听别人说kiddion要等到明年才更新

那个佩里克岛快速249W的传送进目标点就挂了是咋回事
