### ISSUE TITLE
可以汉化一下吗？

### ISSUE THREAD

**Issue by TT-IPIP** [CrazyZhang666/GTA5OnlineTools#354]
https://github.com/xhz8s/pHake
求大佬汉化一下这个

**Comment by CrazyZhang666** [comment]
这个没啥特别的呀

**Comment by TT-IPIP** [comment]
https://github.com/HatchesPls/GrandTheftAutoV-Cheat

那这个可以汉化吗

可以加到小助手里

多个选择嘛
