### ISSUE TITLE
kiddion bug问题

### ISSUE THREAD

**Issue by here8858** [CrazyZhang666/GTA5OnlineTools#361]
在故事模式打开小助手再进入线上模式进入后不能开火能调出武器轮盘但是调出武器后不能开火只能瞄准人物在更新以前会不定时的抽搐但是更新以后不知道是否是修复了人物不抽搐了但是不可以开火想开火只能使用手枪近战攻击敌人后才能使用手枪开火

**Comment by CrazyZhang666** [comment]
kidddion没有更新
