### ISSUE TITLE
小助手在win10 21h2中闪退

### ISSUE THREAD

**Issue by wenqing93** [CrazyZhang666/GTA5OnlineTools#362]
我的电脑中已经装了.NET Framework 4.8 运行库，一开始我系统版本是21h1是可以打开小助手的，然后更新到21h2后重新打开小助手后发现过了载入条后软件面板整个都是白的不显示任何功能区和菜单栏，然后就自动退出。我为此还重新装了系统，发现只要是21h2版本就会出现这个问题。已经确定的是我已经提前关闭Windows安全中心并且安装了.NET Framework 4.8。拜托作者能核查一下是不是兼容性bug。

**Comment by CrazyZhang666** [comment]
打开小助手前，先关闭微星小飞机程序
