### ISSUE TITLE
ceo特殊货物

### ISSUE THREAD

**Issue by anan9527** [CrazyZhang666/GTA5OnlineTools#366]
CEO特殊货物点了后游戏中没有反应 还是普通货物  请作者大大及时更新

**Comment by CrazyZhang666** [comment]
你需要退出电脑重新加入

**Comment by anan9527** [comment]
不行的 
这次更新DLC之前我都可以用的 
我之前的操作是 没坐到电脑前 先点小助手里的特殊物品 在开电脑点特殊货物 在点仓库 购买里就有特殊货物了
请问 现在怎么操作？

> 你需要退出电脑重新加入

不行的 
这次更新DLC之前我都可以用的 
我之前的操作是 没坐到电脑前 先点小助手里的特殊物品 在开电脑点特殊货物 在点仓库 购买里就有特殊货物了
请问 现在怎么操作？

**Comment by anan9527** [comment]
> 你需要退出电脑重新加入
怎么个退出电脑重新加入？
在这次更新之前，还能用，我之前的操作是：1.小哑巴没坐到电脑前，就点小助手里的特殊物品了。2.坐到电脑前操作打开仓库后就看见有特殊物品的的购买选项了。
按你说的退出电脑重新加入，我试的操作是：1.按上面说的更新前的操作方法后打开仓库没有特殊物品。2.退出电脑，在进仓库还是没有。3.退出电脑，小哑巴起身在坐下，打开仓库还是没有。

**Comment by CrazyZhang666** [comment]
有时间我研究下
