### ISSUE TITLE
sub外置辅助功能无法正常使用

### ISSUE THREAD

**Issue by wgg1998** [CrazyZhang666/GTA5OnlineTools#367]
![image](https://user-images.githubusercontent.com/96620711/147351218-7f08bc2d-86e3-434d-9026-bbca016e8f60.png)
在游戏中无法正常使用sub功能，刚下载的时候是可以使用的。后来更新过版本后无法使用，并且回溯版本也无法使用。

**Comment by CrazyZhang666** [comment]
这个没有更新，可以使用kiddion，今天更新了
