### ISSUE TITLE
kiddion今天更新不能用

### ISSUE THREAD

**Issue by hzj3366397156** [CrazyZhang666/GTA5OnlineTools#37]
kiddion今天更新不能用
![QQ图片20210318113911](https://user-images.githubusercontent.com/51468147/111570042-ecc8bc80-87de-11eb-89b0-a81c8ebdd138.png)

**Comment by averyaveryavery** [comment]
我也是

**Comment by CrazyZhang666** [comment]
已更新版本

**Comment by averyaveryavery** [comment]
3q
