### ISSUE TITLE
注入式菜单BUG

### ISSUE THREAD

**Issue by MCxingX** [CrazyZhang666/GTA5OnlineTools#378]
[进入注入式菜单点击注入之后，菜单打开，没功能，还有end按键无反应，ins打开或者关闭
![1RERUBD$W{XW43NGZZ ~46G](https://user-images.githubusercontent.com/96986991/147879969-1ff19e95-5c33-4f44-83f2-cae7b3872b83.png)

**Comment by CrazyZhang666** [comment]
窗口用鼠标调整大小 挡住了

**Comment by MCxingX** [comment]
>
感谢作者，可以了
