### ISSUE TITLE
小助手注入式外置菜单bug反馈

### ISSUE THREAD

**Issue by w3427** [CrazyZhang666/GTA5OnlineTools#382]
我今天打开注入器，注入后发现游戏崩溃了，希望能解决一下这个问题，这样会更好。我也理解这个bug因为这只是初期
感谢！

I opened the injector today and found that the game crashed after injection. I hope I can solve this problem, which will be better. I also understand the bug because this is just the beginning.
Thanks！

**Comment by CrazyZhang666** [comment]
收到反馈

**Comment by polarabbit0** [comment]
在选择线上模式和故事模式的界面注入，然后先进线下后进线上，之前Luna也是这么手动注入的
