### ISSUE TITLE
辅助

### ISSUE THREAD

**Issue by youbenbi** [CrazyZhang666/GTA5OnlineTools#384]
希望可以出一个删除武器的功能，圣诞节强制送的烟花发射器子弹打完了还在，丢也丢不了，武器库也找不到隐藏选项，太碍事了
感谢

**Comment by liu7A** [comment]
老哥，这个功能貌似不该小助手提供吧。。。

**Comment by gmy771810930** [comment]
丢不掉的，因为给了就永久解锁了，而且商店可以补子弹
