### ISSUE TITLE
GTAHax代码导入器的，修改外星人纹身代码无效。

### ISSUE THREAD

**Issue by adawndog** [CrazyZhang666/GTA5OnlineTools#385]
正常操作了几次，用GTAHax修改外星人纹身，但是没有作用，以前使用此功能都可以的，是不是有bug，希望修复一下谢谢

**Comment by adawndog** [comment]
![image](https://user-images.githubusercontent.com/97245030/148417723-fd4ef1a2-078b-4bdb-b16a-6d0b475de132.png)
就是此项功能写入游戏之后显示成功了，但是游戏里并没有成功出现外星人纹身

**Comment by CrazyZhang666** [comment]
你切换下角色看看

**Comment by adawndog** [comment]
> 你切换下角色看看

试了没有用，写入成功后游戏左下角有提示奖章，但没有出现纹身，以前写入成功后自杀就会出现纹身现在没用了
