### ISSUE TITLE
3.0.0.8版本可以打开,之后的版本打开提示有病毒

### ISSUE THREAD

**Issue by fulaisky2000** [CrazyZhang666/GTA5OnlineTools#388]
3.0.0.8版本可以打开,之后的版本打开提示有病毒,电脑没安装任何杀毒软件,WIN10系统,3.0.0.8正常使用

**Comment by fulaisky2000** [comment]
![image](https://user-images.githubusercontent.com/75131040/148807037-38382ae3-6858-4798-a98c-db6d39d5bd6b.png)

**Comment by fulaisky2000** [comment]
![image](https://user-images.githubusercontent.com/75131040/148807095-9cfaa30e-2589-4ef1-a5d6-6b7186c76543.png)

**Comment by fulaisky2000** [comment]
![image](https://user-images.githubusercontent.com/75131040/148807298-485b7131-5552-42c0-9b8f-96b3388c4e35.png)

**Comment by fulaisky2000** [comment]
![image](https://user-images.githubusercontent.com/75131040/148807418-3920ac9d-6104-45fc-8f26-3c5923415efa.png)

**Comment by Kurohoshi-aiba** [comment]
它就是有垃圾程序在挖矿
![图片](https://user-images.githubusercontent.com/46209911/149147385-06573200-6c71-47db-b905-18e97e43e013.png)
![图片](https://user-images.githubusercontent.com/46209911/149147632-11981589-4394-4708-a770-acac3d64e94a.png)

**Comment by CrazyZhang666** [comment]
> 它就是有垃圾程序在挖矿 ![图片](https://user-images.githubusercontent.com/46209911/149147385-06573200-6c71-47db-b905-18e97e43e013.png) ![图片](https://user-images.githubusercontent.com/46209911/149147632-11981589-4394-4708-a770-acac3d64e94a.png)

小助手没有加壳，直接反编译就可以看到源码，有没有问题请查看代码而不是胡说，我的程序经得起大家的检验

**Comment by CrazyZhang666** [comment]
再说挖矿用CPU挖？请有一些计算机常识好吗？

**Comment by Kurohoshi-aiba** [comment]
> 再说挖矿用CPU挖？请有一些计算机常识好吗？

那我是不是应该奖励自己一个3990x来用你的小助手

**Comment by CrazyZhang666** [comment]
> > 再说挖矿用CPU挖？请有一些计算机常识好吗？
> 
> 那我是不是应该奖励自己一个3990x来用你的小助手

请直接删除小助手，不要使用了，小助手cpu资源占有率不到1%，我不清楚你是用了什么办法让他占有率那么高，而且也就你一个人是这样，不要为了黑而黑，

**Comment by CrazyZhang666** [comment]
![image](https://user-images.githubusercontent.com/28080853/150092748-a353cc8d-6a49-492f-8f8d-5503a2ad93bb.png)

**Comment by Kurohoshi-aiba** [comment]
> > > 再说挖矿用CPU挖？请有一些计算机常识好吗？
> > 
> > 
> > 那我是不是应该奖励自己一个3990x来用你的小助手
> 
> 请直接删除小助手，不要使用了，小助手cpu资源占有率不到1%，我不清楚你是用了什么办法让他占有率那么高，而且也就你一个人是这样，不要为了黑而黑，

请你理智一点,我为什么要为了黑你而来GitHub的issue呢?想要黑你大把地方可以去,而不必来为了报告bug的地方跟你说.这当然是正常的开个游戏发现卡崩才看的任务管理器,所以你应该去找找程序的问题.当然我跟大众肯定不一样,用的不是盗版系统,是正版受害者,你可以考虑一下这个原因

**Comment by CrazyZhang666** [comment]
> 

如果只是打开小助手程序（不启用任何功能的情况），小助手有个计时器，1秒钟运行一次，用来判断GTA5是否运行和第三方辅助是否运行和小助手运行时间，这个理论上不占用电脑资源，我测试过，cpu占用在1%左右浮动，小助手显卡占用是因为小助手是用WPF设计的，WPF的UI部分是采用DirectX绘图，而不是传统的CPU绘图（GDI），你打开QQ、QQ音乐等程序也可以看到他也有GPU占用（因为这些程序的UI也是DirectX绘图）。

如果你打开小助手辅助里的ESP功能，可能会导致小助手占用变高，因为要小助手要高速绘制EPS图形以保证ESP帧数

我自己电脑是9700K+2070S，我刚才打开小助手 CPU占有率如下
一般情况下是不会导致小助手突然占用变高的，你可以打开这个箭头看看具体是那个模块占用
或者重启一下小助手，这个占用高问题是频繁发生吗？
![image](https://user-images.githubusercontent.com/28080853/150093977-74490228-0433-4161-9723-75aeb631d22e.png)

![image](https://user-images.githubusercontent.com/28080853/150093907-8641fdf6-0f09-4ad4-8017-6de31a38ff0b.png)

**Comment by Kurohoshi-aiba** [comment]
不开游戏都是这么高,甚至是初始化都奇慢,以前都是0.1秒左右,每次开启都是这样
别的程序我就开了QQ,开黑啦,Steam,UU加速器,火狐浏览器.剩下的后台都是家用机常挂的进程
![QQ图片20220119174514](https://user-images.githubusercontent.com/46209911/150095713-5a9f3d35-075c-4851-b010-1aa430157ceb.png)
![QQ图片20220119180128](https://user-images.githubusercontent.com/46209911/150097944-d954a0f5-b8c0-4777-80d8-24ded8cd9512.png)
U是AMD 3900X
显卡是2060s
![QQ图片20220119181020](https://user-images.githubusercontent.com/46209911/150100063-2eed0be1-e89d-4539-89e9-f20673a5e5af.png)

**Comment by CrazyZhang666** [comment]
> 不开游戏都是这么高,甚至是初始化都奇慢,以前都是0.1秒左右,每次开启都是这样 别的程序我就开了QQ,开黑啦,Steam,UU加速器,火狐浏览器.剩下的后台都是家用机常挂的进程 ![QQ图片20220119174514](https://user-images.githubusercontent.com/46209911/150095713-5a9f3d35-075c-4851-b010-1aa430157ceb.png) ![QQ图片20220119180128](https://user-images.githubusercontent.com/46209911/150097944-d954a0f5-b8c0-4777-80d8-24ded8cd9512.png) U是AMD 3900X 显卡是2060s ![QQ图片20220119181020](https://user-images.githubusercontent.com/46209911/150100063-2eed0be1-e89d-4539-89e9-f20673a5e5af.png)

初始化是因为要检测版本更新，节点是阿里云的，在国内，应该不会慢，一般1秒内就能初始化完毕
初始化慢是因为网络等待时间长

你或者重新一下电脑，然后再打开小助手试试看

你或者把小助手删除，然后重新下载看看，https://crazyzhang.lanzoui.com/b04md71ve

也可以试试历史版本，看看哪个版本没有问题
https://crazyzhang.lanzoui.com/b04n07ymb
![image](https://user-images.githubusercontent.com/28080853/150104447-4190b755-5b77-4a77-8a05-94fd4df6cd24.png)

**Comment by CrazyZhang666** [comment]
> > > > 再说挖矿用CPU挖？请有一些计算机常识好吗？
> > > 
> > > 
> > > 那我是不是应该奖励自己一个3990x来用你的小助手
> > 
> > 
> > 请直接删除小助手，不要使用了，小助手cpu资源占有率不到1%，我不清楚你是用了什么办法让他占有率那么高，而且也就你一个人是这样，不要为了黑而黑，
> 
> 请你理智一点,我为什么要为了黑你而来GitHub的issue呢?想要黑你大把地方可以去,而不必来为了报告bug的地方跟你说.这当然是正常的开个游戏发现卡崩才看的任务管理器,所以你应该去找找程序的问题.当然我跟大众肯定不一样,用的不是盗版系统,是正版受害者,你可以考虑一下这个原因

小助手已经开源，你可以下载源码自己编译
https://github.com/CrazyZhang666/GTA5OnlineTools

**Comment by CrazyZhang666** [comment]
> 3.0.0.8版本可以打开,之后的版本打开提示有病毒,电脑没安装任何杀毒软件,WIN10系统,3.0.0.8正常使用

小助手已经开源，你可以下载源码自己编译
https://github.com/CrazyZhang666/GTA5OnlineTools
