### ISSUE TITLE
关于线上小助手可编辑栏的一些建议~

### ISSUE THREAD

**Issue by s410399713** [CrazyZhang666/GTA5OnlineTools#39]
希望作者大大能把小数点的倍率也开放进去
![image](https://user-images.githubusercontent.com/51051156/111584206-881a5b80-87f8-11eb-8b39-b8564deb8a0d.png)，目前只能是整数倍率修改，无法使用小数点倍率呢。。整数倍率修改差别太大，不太好使用

**Comment by s410399713** [comment]
希望能出微调小数点倍率的可编辑栏就好了！~

**Comment by CrazyZhang666** [comment]
已采纳，最新版本小助手支持小数点
