### ISSUE TITLE
我用您给的病毒检测链接检测，它告诉我有病毒

### ISSUE THREAD

**Issue by JessieX123** [CrazyZhang666/GTA5OnlineTools#391]
如题
我非常信任这个软件，也非常信任你，未来我也会继续用小助手
但是，检测结果是这个样子
希望作者大大能看看
![无标题1](https://user-images.githubusercontent.com/97375062/149474007-4ae146a6-ee44-4ce7-8c52-c06494933619.png)

![无标题](https://user-images.githubusercontent.com/97375062/149473866-40ebb9fe-49a8-44d8-a9cd-937ec4b5a093.png)

**Comment by CrazyZhang666** [comment]
软件没有加壳，请自行反编译查看源码

**Comment by CrazyZhang666** [comment]
我也不清楚为啥会报毒，软件是用WPF写的，NET4.8版本，没有加壳，可以使用dnSpy或ILSpy等反编译工具查看源代码，下次更新我会直接把小助手代码开源的

**Comment by JessieX123** [comment]
我只是个普通的玩家，不会啊😂

**Comment by CrazyZhang666** [comment]
小助手已经开源，你可以下载源码自己编译
https://github.com/CrazyZhang666/GTA5OnlineTools
