### ISSUE TITLE
小助手停止运行

### ISSUE THREAD

**Issue by chiyibin** [CrazyZhang666/GTA5OnlineTools#393]
我的电脑是win7 64位 下载的是3.0.1的版本，一直停止运行。
详细问题是问题签名

**Comment by CrazyZhang666** [comment]
https://crazyzhang.lanzoui.com/b04md71ve
你下载最新版本试试看

以前能运行的最新的版本是哪个版本呢？

**Comment by CrazyZhang666** [comment]
> 我的电脑是win7 64位 下载的是3.0.1的版本，一直停止运行。 详细问题是问题签名

这个问题已经在 v3.0.1.4 得到解决，重新下载最新版本即可
