### ISSUE TITLE
发现一个更新问题

### ISSUE THREAD

**Issue by kycnb666** [CrazyZhang666/GTA5OnlineTools#394]
更新节点中有一个是失效了的，作者大大可以把这个节点去
![wt](https://user-images.githubusercontent.com/85140774/150731010-7d37f923-ab58-4b6a-b91f-21446e541774.png)
掉

**Comment by kycnb666** [comment]
使用这个节点更新时会出现服务器500错误

**Comment by CrazyZhang666** [comment]
> 使用这个节点更新时会出现服务器500错误

感谢反馈😊
