### ISSUE TITLE
小助手功能不对照

### ISSUE THREAD

**Issue by DDragonZheng** [CrazyZhang666/GTA5OnlineTools#395]
“小助手外置菜单-常用-修复载具外观”这一项使用之后是牛鲨睾酮效果，并非修复载具外观，麻烦作者修复一下

**Comment by CrazyZhang666** [comment]
好的，感谢反馈，已发现该问题，下次更新修复

**Comment by CrazyZhang666** [comment]
> “小助手外置菜单-常用-修复载具外观”这一项使用之后是牛鲨睾酮效果，并非修复载具外观，麻烦作者修复一下

这个你切换一下战局，然后就可以使用了，是修复载具外观的
