### ISSUE TITLE
给作者提个美化UI的建议

### ISSUE THREAD

**Issue by kycnb666** [CrazyZhang666/GTA5OnlineTools#396]
小助手的UI真的是越来越好看了，但是这样的窗体可能做成圆角会更好看更协调

**Comment by CrazyZhang666** [comment]
> 小助手的UI真的是越来越好看了，但是这样的窗体可能做成圆角会更好看更协调

我不是很喜欢圆角哈，这个窗体还是window默认窗体，我没有修改
