### ISSUE TITLE
图片异常

### ISSUE THREAD

**Issue by zerodown19999** [CrazyZhang666/GTA5OnlineTools#397]
![CWYNX6K4F 927}6M`@MW@FD](https://user-images.githubusercontent.com/98514763/151314660-c1905a56-49b8-4706-83ff-25c819a881e4.png)
像这样,但是一些老旧版本像3.0.01.1是可以正常使用

**Comment by CrazyZhang666** [comment]
> ![CWYNX6K4F 927}6M`@MW@FD](https://user-images.githubusercontent.com/98514763/151314660-c1905a56-49b8-4706-83ff-25c819a881e4.png) 像这样,但是一些老旧版本像3.0.01.1是可以正常使用

https://github.com/dotnet/wpf/issues/707
这个是我搜索到的解决办法，你这种情况应该是与电脑上某个程序冲突导致UI渲染出现异常

**Comment by CrazyZhang666** [comment]
https://blog.walterlv.com/post/wpf-renders-wrong-because-of-nahimicosd.html

**Comment by CrazyZhang666** [comment]
也就是说 外星人程序 有个NahimicOSD.dll 注入到小助手程序才导致出现的UI异常
‪C:\ProgramData\A-Volute\DellInc.AlienwareSoundCenter\Modules\ScheduledModules\x64\NahimicOSD.dll 
把这个dll重命名一下 
比如
‪C:\ProgramData\A-Volute\DellInc.AlienwareSoundCenter\Modules\ScheduledModules\x64\NahimicOSD备份.dll 
然后重启电脑就可以了
也就是NahimicOSD.dll文件重命名一下

**Comment by zerodown19999** [comment]
谢了老哥搞定了
