### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jiuxx** [CrazyZhang666/GTA5OnlineTools#399]
无法正常刷上岛前置任务

**Comment by CrazyZhang666** [comment]
> 无法正常刷上岛前置任务

能具体描述下吗？

**Comment by jiuxx** [comment]
无法导入

**Comment by jiuxx** [comment]
小助手辅助都不能用

**Comment by CrazyZhang666** [comment]
> 小助手辅助都不能用

897010735
有兴趣可以加一下这个群
![image](https://user-images.githubusercontent.com/28080853/151659630-4b57c7aa-394a-48a1-b3b5-1f0df4561978.png)

**Comment by reimelyn19** [comment]
外置小助手打开以后就置顶了,没法最小化或者切回游戏主画面
