### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by douhua1337** [CrazyZhang666/GTA5OnlineTools#400]
您好，小助手的这几种修改器的功能多多少少都有几个失效了，如果您不忙的话还麻烦您更新一下，谢谢您

**Comment by CrazyZhang666** [comment]
> 您好，小助手的这几种修改器的功能多多少少都有几个失效了，如果您不忙的话还麻烦您更新一下，谢谢您

你使用的是最新版本吗？我测试全部功能都可以使用啊

**Comment by CrazyZhang666** [comment]
> 您好，小助手的这几种修改器的功能多多少少都有几个失效了，如果您不忙的话还麻烦您更新一下，谢谢您

897010735
有兴趣可以加一下这个群:grin: 
![Uploading image.png…]()
