### ISSUE TITLE
新版本反馈

### ISSUE THREAD

**Issue by jinshilin35** [CrazyZhang666/GTA5OnlineTools#404]
首先祝您新年快乐，然后再反馈一下，面板大改还有点不适应，然后爆炸子弹能开不能关，很尴尬，飞机刷出来时候轮子收起问题还在，F9热键游戏里和丢弃武器冲突。这是目前我发现的问题。

**Comment by jinshilin35** [comment]
还一个就是小助手内置菜单关掉传送效果也依然存在

**Comment by CrazyZhang666** [comment]
收到反馈
