### ISSUE TITLE
小助手3.0.19版本bug反馈

### ISSUE THREAD

**Issue by fxcker** [CrazyZhang666/GTA5OnlineTools#405]
首先非常感谢作者对于该程序的编写方便大伙单人任务，最新版有一些bug，首先是所有刷出来的飞机没有起落架导致大部分都起降不了，而且有很多飞机变为了阉割版如巨像图拉，火箭助推以及轰炸都没了，其他部分飞机的轰炸也没了，像弟弟兔最开始我使用的版本是有导弹的现在只有爆裂机枪了。大概就这么多是我使用时发现的问题，望修复。谢谢作者啦！！！

**Comment by CrazyZhang666** [comment]
刷载具目前尚未处理，后续更新会陆续修复

**Comment by fxcker** [comment]
> 刷载具目前尚未处理，后续更新会陆续修复

感谢啦！作者新年快乐，希望以后的版本载具武器问题能够得到修复。新年快乐！！！

**Comment by CrazyZhang666** [comment]
> > 刷载具目前尚未处理，后续更新会陆续修复
> 
> 感谢啦！作者新年快乐，希望以后的版本载具武器问题能够得到修复。新年快乐！！！

飞机不是可以起飞吗？我测试没问题啊，能具体说下哪些载具有问题吗？

**Comment by fxcker** [comment]
> > > 刷载具目前尚未处理，后续更新会陆续修复
> > 
> > 
> > 感谢啦！作者新年快乐，希望以后的版本载具武器问题能够得到修复。新年快乐！！！
> 
> 飞机不是可以起飞吗？我测试没问题啊，能具体说下哪些载具有问题吗？

飞机是起落架的问题，我刷出来的飞机都没有起落架，像天煞
![20220201213532_1](https://user-images.githubusercontent.com/98760861/151978095-29917ff3-1902-486f-9090-5b43cb6aa8ba.jpg)

**Comment by fxcker** [comment]
> > > 刷载具目前尚未处理，后续更新会陆续修复
> > 
> > 
> > 感谢啦！作者新年快乐，希望以后的版本载具武器问题能够得到修复。新年快乐！！！
> 
> 飞机不是可以起飞吗？我测试没问题啊，能具体说下哪些载具有

**Comment by CrazyZhang666** [comment]
897010735 加一下这个群

![image](https://user-images.githubusercontent.com/28080853/151978365-299df48c-526b-42d9-89f0-8dfb4f32e6da.png)

**Comment by fxcker** [comment]
> > > 刷载具目前尚未处理，后续更新会陆续修复
> > 
> > 
> > 感谢啦！作者新年快乐，希望以后的版本载具武器问题能够得到修复。新年快乐！！！
> 
> 飞机不是可以起飞吗？我测试没问题啊，能具体说下哪些载具有问题吗?


> > > 刷载具目前尚未处理，后续更新会陆续修复
> > 
> > 
> > 感谢啦！作者新年快乐，希望以后的版本载具武器问题能够得到修复。新年快乐！！！
> 
> 飞机不是可以起飞吗？我测试没问题啊，能具体说下哪些载具有问题吗？

ok
