### ISSUE TITLE
使用问题反馈

### ISSUE THREAD

**Issue by maidi404** [CrazyZhang666/GTA5OnlineTools#406]
外置菜单按f9与扔枪冲突，而且希望外置菜单刷的线上载具不要全改装，然后聊天辅助希望可以优化一下 有时候一按发送软件就崩了

**Comment by maidi404** [comment]
还有外置菜单希望可以窗口稍微调小点

**Comment by CrazyZhang666** [comment]
> 外置菜单按f9与扔枪冲突，而且希望外置菜单刷的线上载具不要全改装，然后聊天辅助希望可以优化一下 有时候一按发送软件就崩了

F9键准备改成ins键，
刷的载具默认是全改装的，毕竟只是当作匿名载具来使用的
聊天栏我测试没问题，没有发现崩溃问题，你可以看下C:\ProgramData\GTA5OnlineTools\Config\ErrorLog错误日志
外置窗口目前是1000x600分辨率，应该不会太大吧，除非你屏幕是1080p一下分辨率的，太小了内容不好放置
