### ISSUE TITLE
Discord邀请链接失效,github和官网的邀请链接均失效

### ISSUE THREAD

**Issue by Weltolk** [CrazyZhang666/GTA5OnlineTools#409]
作者可以补一个邀请链接吗?谢谢

**Comment by CrazyZhang666** [comment]
收到反馈

**Comment by Weltolk** [comment]
> 收到反馈

奇怪,web会显示邀请链接无效,Android会正常跳转到discord

**Comment by CrazyZhang666** [comment]
> > 收到反馈
> 
> 奇怪,web会显示邀请链接无效,Android会正常跳转到discord

小助手网站discord邀请链接意见更新，测试可用

**Comment by Weltolk** [comment]
> > > 收到反馈
> > 
> > 
> > 奇怪,web会显示邀请链接无效,Android会正常跳转到discord
> 
> 小助手网站discord邀请链接已经更新，测试可用

ctrl+F5刷新了,但是貌似还是原来的邀请链接,web端还是显示无效https://discord.com/invite/2pJWvWu

**Comment by CrazyZhang666** [comment]
> > > > 收到反馈
> > > 
> > > 
> > > 奇怪,web会显示邀请链接无效,Android会正常跳转到discord
> > 
> > 
> > 小助手网站discord邀请链接已经更新，测试可用
> 
> ctrl+F5刷新了,但是貌似还是原来的邀请链接,web端还是显示无效https://discord.com/invite/2pJWvWu

https://crazyzhang.cn/gta5/a001.html

**Comment by Weltolk** [comment]
> > > > > 收到反馈
> > > > 
> > > > 
> > > > 奇怪,web会显示邀请链接无效,Android会正常跳转到discord
> > > 
> > > 
> > > 小助手网站discord邀请链接已经更新，测试可用
> > 
> > 
> > ctrl+F5刷新了,但是貌似还是原来的邀请链接,web端还是显示无效https://discord.com/invite/2pJWvWu
> 
> https://crazyzhang.cn/gta5/a001.html

thanks,solved

**Comment by Weltolk** [comment]
> > > > > > 收到反馈
> > > > > 
> > > > > 
> > > > > 奇怪,web会显示邀请链接无效,Android会正常跳转到discord
> > > > 
> > > > 
> > > > 小助手网站discord邀请链接已经更新，测试可用
> > > 
> > > 
> > > ctrl+F5刷新了,但是貌似还是原来的邀请链接,web端还是显示无效https://discord.com/invite/2pJWvWu
> > 
> > 
> > https://crazyzhang.cn/gta5/a001.html
> 
> thanks,solved

补充,我这边pc端在浏览器打开显示无效的原因,pc端没开着Discord时,点击链接就会显示无效,如果开着Discord,不论前台后台,都可以正常加群,Android端则不论打不打开Discord都可以正常加群
