### ISSUE TITLE
有关刷钱,请问作者大大,一些快速出钱的方法中,哪些还算风险相对低一点的?谢谢

### ISSUE THREAD

**Issue by Weltolk** [CrazyZhang666/GTA5OnlineTools#411]
改车卖钱
赌场改点数刷筹码
小岛跳前置
地堡,摩托帮,ceo出货等

**Comment by CrazyZhang666** [comment]
现在推荐正常出货赚钱，也就是用传送加快下出货时间这些的了，或者是刷别惹瑞德（我目前还没了解过）

**Comment by Weltolk** [comment]
> 现在推荐正常出货赚钱，也就是用传送加快下出货时间这些的了，或者是刷别惹瑞德（我目前还没了解过）

感谢

**Comment by 2002smart** [comment]
赌场刷筹码现在风险相当高，不应该被使用
