### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1020623818** [CrazyZhang666/GTA5OnlineTools#412]
那个小助手
自动击杀敌对npc
现在用起来感觉是把所有“有血条”的npc都杀掉了
任务里包括红圈、蓝圈一并杀掉
而且载具里的敌对npc有时候杀不掉
希望能识别一下，如果是蓝圈就不杀，红圈再杀
因为现在这样只要有一个蓝圈或者一个npc队友，就不能开击杀敌对npc
（v3.0.2.2   v3.0.2.3）

**Comment by CrazyZhang666** [comment]
收到反馈，你可以举几个出现问题的任务例子吗？我好方便测试

**Comment by 1020623818** [comment]
我不小心开过的任务有这些
赌场-贝克女士：解救陈陶：开了之后那个逼逼赖赖的陈陶一块死在了汽车酒店里，根本找不到人
赌场-贝克女士：铁腕战术：一开，陈陶和翻译员一起挂掉
突袭人道研究实验室：女武神：开了之后终点等着的人会挂掉然后失败（我不太确定是不是女武神但一定是人道前置）
末日豪劫3-前置：营救ULP（就是那个老让你买机动作战中心的14号探员）：开了之后探员嗝屁
末日豪劫3-前置：护送ULP：我是如果在探员飞机起飞之前开的话探员、周围一圈人全都会死，一次是探员死了，一次是保镖死了

可能稍微有些偏差，但是大部分带己方npc的任务都能杀死己方npc

**Comment by CrazyZhang666** [comment]
收到反馈
