### ISSUE TITLE
cannot open 不能打开

### ISSUE THREAD

**Issue by Jason-JDM-Fan** [CrazyZhang666/GTA5OnlineTools#413]
When I update to v3.0.2.4 the online helper cannot open.
当我更新到v3.0.2.4的时候小助手打不开了

**Comment by WSYwsy22** [comment]
我也是一样无法打开，刚刚更新完新版本无法打开。

**Comment by 007DM** [comment]
我也是，今天更新了就打不开了，希望尽快修复！

**Comment by 1020623818** [comment]
+1，但我是啥都不提示，只有申请管理员权限，然后就没后文了

**Comment by 1621614056** [comment]
我也是打不开没反应

**Comment by 1621614056** [comment]
希望作者快点修复打不开没反应啊

**Comment by CrazyZhang666** [comment]
安装net6.0.2就可以打开了，直接下载安装下面的链接
https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer

**Comment by 007DM** [comment]
修复了，大家下载第二个新的必装NET6.0.2就行了
