### ISSUE TITLE
win10 GTA5线上小助手支持1,58完全免携v3.0.1.8可以打开GTA5线上小助手支持1,58完全免携v3.0.2.4打开后自动关闭

### ISSUE THREAD

**Issue by gksol1** [CrazyZhang666/GTA5OnlineTools#415]
win10 GTA5线上小助手支持1,58完全免携v3.0.1.8可以打开GTA5线上小助手支持1,58完全免携v3.0.2.4打开后自动关闭。管理员运行问题依旧

**Comment by CrazyZhang666** [comment]
最新版本如果打不开需要安装.NET6.0.2运行库，下载地址
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.2-windows-x64-installer

**Comment by gksol1** [comment]
我之前安装的runtime-desktop-6.0.1-windows-x64，没有安装6.0.2，所以没打开，谢谢耐心回复！问题已解决
