### ISSUE TITLE
新版本打不开

### ISSUE THREAD

**Issue by shusheng1235** [CrazyZhang666/GTA5OnlineTools#417]
新版本打不开

**Comment by 31431316** [comment]
我也是 更新之后一点反应都没有， 向我要了权限啥都没出来 win10系统

**Comment by 31431316** [comment]
美国海外链接下载的

**Comment by CrazyZhang666** [comment]
麻烦大家看一看使用说明好吗？Iss旁边就是解决办法，这几天几百人轮流问这个问题，我小助手主页，网站都写了公告如何解决，都过了3天了还是不看，真是没办法😔
