### ISSUE TITLE
小助手的kiddion v0.8.10打不开

### ISSUE THREAD

**Issue by 339989787** [CrazyZhang666/GTA5OnlineTools#42]
![49ce81f2dc894e7fbe756b6c884074c](https://user-images.githubusercontent.com/81003925/111860584-8335e300-8983-11eb-82da-fc930c09f46b.jpg)
![fbbf4c4dc1a2441df47f8425f22613e](https://user-images.githubusercontent.com/81003925/111860585-8630d380-8983-11eb-84dc-12e5fc5c73f0.jpg)

**Comment by CrazyZhang666** [comment]
已更新版本
