### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by Cython4869** [CrazyZhang666/GTA5OnlineTools#422]
![QQ截图20220313141603](https://user-images.githubusercontent.com/101493808/158047589-6798aa72-f69c-4079-8c41-7a3c2277f8dd.png)
大佬你好，我在GTA5线上模式中遇到一个问题，如图，小助手外置菜单中，有一个任务帮手，里面关于CEO的出货功能，有的是有特殊物品的，有的是没有特殊物品的。这里说需要退出CEO的电脑重新进入可以生效。这个功能我在试的时候的确可以【变换货物类型】，但是始终【没有特殊物品】，退出CEO电脑重进无法生效，切换战局也无法生效。

**Comment by HCXSF** [comment]
小助手这两天打开后游戏里面显示不了菜单、但是可以用

**Comment by HCXSF** [comment]
这两天打开游戏里面显示不出来那个菜单

**Comment by HongKonDoll** [comment]
打开之后经常卡画面动不了，然后游戏闪退，特别是过场动画，不在过场动画也会出现这种情况
