### ISSUE TITLE
2022.4.26更新后的问题

### ISSUE THREAD

**Issue by yanglaosanbuqu1** [CrazyZhang666/GTA5OnlineTools#432]
线上不能刷出载具和武器，第三方和外置菜单都不行

**Comment by yanglaosanbuqu1** [comment]
更新完就不能刷了

**Comment by sunzhuangdakeng** [comment]
我也是，刷不出来啊，怎么办

**Comment by lilan233** [comment]
世界功能里面的战局切换功能，除了离开线上模式其他的用了都没反应；线上选项里面的刷新个人载具和呼叫个人载具点了没有效果；线上载具里面的修复载具外观没有效果，还有刷载具刷不出来，空地不能，室内的没试过。
其他没说的就是没试。

**Comment by hebianhuang** [comment]
作者大大，kid那个三方辅助更新之后载具和赌场之类的都用不了了

**Comment by 2621282111** [comment]
求更新啊
