### ISSUE TITLE
2022.4.26GTA更新2612版本小助手的问题

### ISSUE THREAD

**Issue by kx227** [CrazyZhang666/GTA5OnlineTools#433]
2022.4.26GTA更新2612版本之后线上载具和武器刷不出来，切换战局和退回桌面进游戏都没用，刷载具开阔地也没用

**Comment by chenyingjie202201** [comment]
我也是啊 难受死了 这么良心的辅助没动力更新了

**Comment by 848520989** [comment]
2022.4.27GTA线上小助手佩里克岛抢劫导入不进去，这是为什么啊？小助手更新了吗还是我电脑的问题

**Comment by kx227** [comment]
等等作者更新吧，不差这几天



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 2022.4.26GTA更新2612版本小助手的问题 (Issue #433)




 
2022.4.27GTA线上小助手佩里克岛抢劫导入不进去，这是为什么啊？小助手更新了吗还是我电脑的问题

**Comment by 848520989** [comment]
没得问题 我就是偶然发现的，然后来这里问一下

**Comment by 2621282111** [comment]
刷不出来咋办

**Comment by 2621282111** [comment]
刷不出载具咋办啊

**Comment by echo488** [comment]
求更新

**Comment by CHN3333** [comment]
作者什么时候更新啊 载具刷不出来 赌场前置任务也跳过不了 小助手也切换不了战局

**Comment by 848520989** [comment]
为啥我更新了以后，2.6版本上岛前置代码还是不行  有谁能和我说一下

**Comment by kx227** [comment]
等作者更新



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 晚上8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 2022.4.26GTA更新2612版本小助手的问题 (Issue #433)




 
刷不出载具咋办啊
