### ISSUE TITLE
地堡出货数量修改

### ISSUE THREAD

**Issue by ajie63** [CrazyZhang666/GTA5OnlineTools#44]
触发地堡生产错误有原材料但是一直报错原材料为空
![-5ce4044be07fe4d6](https://user-images.githubusercontent.com/81022149/111869888-713a4d00-894f-11eb-967e-d78d3ddf9fe5.png)

**Comment by CrazyZhang666** [comment]
派遣人员去研究，然后切换战局试试，我测试是可以使用的

**Comment by CrazyZhang666** [comment]
我测试是可以使用的，如果不行就出一次货试试看或者手动偷取一次原料，我是epic版本测试的
