### ISSUE TITLE
开发者你好，代码界面最后一步无运行，麻烦您解决一下

### ISSUE THREAD

**Issue by Smallbuilding** [CrazyZhang666/GTA5OnlineTools#443]
![image](https://user-images.githubusercontent.com/104681079/166105656-83477211-77b2-4228-86f8-2012d69a87a0.png)
  最后的写入gtahax页面一直显示代码在队列中但没有后续反应

**Comment by Galaxy-Studio-Code** [comment]
这样是正常的，左下角那个Add 19 into queue有变化说明就在运行了，如果没变化就再在小助手里点一次就行

**Comment by Aure7138** [comment]
此工具还未更新，暂时无法使用

**Comment by WAN271** [comment]
开发者你好刷车的时候有点慢有时候还刷不出来比如那个拉能自行车 ，刚刷出来过，过一会儿，就没了。还有赌场抢劫那个任务太可使用。 还有就是更新之后之前的那个补充弹药快捷键消失了吗？希望开发者大大尽快修复。
