### ISSUE TITLE
技工叫车无法确认

### ISSUE THREAD

**Issue by kaikaiso** [CrazyZhang666/GTA5OnlineTools#447]
一开了小助手第三方后，  打电话给技工拿车，  到了确认车辆页面卡住 无法确认。大退游戏重登后可以正常叫车，一开小助手又不行。
![Uploading QQ截图20220503131159.png…]()

**Comment by Aure7138** [comment]
哪款第三方

**Comment by kaikaiso** [comment]
kiddion



| |
skandsy
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月05日 16:45 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 技工叫车无法确认 (Issue #447) |

哪款第三方

**Comment by doublebuling** [comment]
我也是启动第三方辅助kiddion后，游戏会出现几个问题。                             
第一个问题：游戏内打电话给npc互动都无法确认选择，比如技工叫车，拉玛劫匪，莱斯特取消任务；
第二个问题：赌场豪劫任务进赌场、离开赌场的过场动画会卡黑屏转圈，已经排除网络问题；
第三个问题：无法看到其他玩家譬如喝酒，抽烟，坐过山车之类的与场景互动的动画。                                
已经尝试过关闭杀毒软件启动小助手，管理员权限启动小助手；重装小助手；验证游戏文件。均未能解决启动kiddion带来的问题。如重启游戏而不启动kiddion,则上述问题均未出现。
望回复 @Aure7138 @CrazyZhang666
