### ISSUE TITLE
1.59的新版本小助手打不开

### ISSUE THREAD

**Issue by shengjiangwang** [CrazyZhang666/GTA5OnlineTools#452]
点击之后在鼠标指针上面转圈让后就没了

**Comment by tian666-shubao** [comment]
win10系统有点问题，打开1.59的最新版总是报毒，并且自动删除小助手，我所有的杀毒软件都关了，小助手白名单也没法加进去，但1.59最新版之前的版本就不这样，可以正常使用，这是怎么回事，在线急等。

**Comment by tian666-shubao** [comment]
![微信图片_20220515190628](https://user-images.githubusercontent.com/105588148/168469586-faded677-074b-44fc-9fa6-acdca6ed7842.png)，我是下载了这个东西之后，就最新版不能用了，我是win10系统
