### ISSUE TITLE
最新版本更新后地堡直接触发生产和研究不能用了

### ISSUE THREAD

**Issue by chen-coco** [CrazyZhang666/GTA5OnlineTools#46]
RT

**Comment by CrazyZhang666** [comment]
![image](https://user-images.githubusercontent.com/28080853/112092318-35fb8080-8bd2-11eb-901e-c719878db963.png)

**Comment by bobstarsky** [comment]
我用地堡刷钱被暂时封号了

**Comment by bobstarsky** [comment]
我用地堡刷钱被暂时封号了 也不是立马封号的 玩了几天刷了几次 昨晚9点下线 凌晨1点说我号违规

**Comment by chen-coco** [comment]
> 我用地堡刷钱被暂时封号了 也不是立马封号的 玩了几天刷了几次 昨晚9点下线 凌晨1点说我号违规
我的号也是今天收到邮件封号了，前天我刷了100级第二天就没了，你是只刷了钱吗

**Comment by bobstarsky** [comment]
刷钱之前好多天就刷等级了

**Comment by chen-coco** [comment]
> 刷钱之前好多天就刷等级了

单刷钱应该不会有事

**Comment by bobstarsky** [comment]
> > 刷钱之前好多天就刷等级了
> 
> 单刷钱应该不会有事

我听的版本是刷等级没事😂
