### ISSUE TITLE
Kiddion问题

### ISSUE THREAD

**Issue by ggmenji** [CrazyZhang666/GTA5OnlineTools#464]
Kiddion运行显示英文弹窗，翻译为：“与当前游戏开启版本不兼容，继续使用可能会损害你的游戏”，然后点击汉化，也没有汉化成功

**Comment by eiyooooo** [comment]
可以忽略此提示

v0.9.3 When starting the menu on GTA5.exe version 1.0.2628.2 you'll get a warning "Incompatible version detected". For v0.9.3 and game version 1.0.2628.2 only this warning can be ignored!
