### ISSUE TITLE
Gta5 small assistant interface menu failure

### ISSUE THREAD

**Issue by YUXUEXD5** [CrazyZhang666/GTA5OnlineTools#47]
When I open the small assistant, the error prompt box will pop up, but the external menu can be used. I hope the team can quickly solve this problem. This has been happening for three days. Here is a screenshot of the assistant error prompt.As the picture can't be uploaded, I will retell the contents of the picture pop-up here
“Unable to find GTA5 process!
'If GTA5 is running in the task mananger, try running "As Administrator".

Then pop up——

Kiddion v0.8.11 CrazyZhangfmAsk"L

I hope the team can repair the bug caused by the Chinese menu as soon as possible, which is not in vain for me to use the translation software. Thank you again!

**Comment by YUXUEXD5** [comment]
Call out s with administrator privileges

**Comment by CrazyZhang666** [comment]
This is caused by the anti-virus software. Please turn off the anti-virus software
