### ISSUE TITLE
最新dlc更新之后刷载具必黑屏

### ISSUE THREAD

**Issue by xiaoevan** [CrazyZhang666/GTA5OnlineTools#473]
![图片](https://user-images.githubusercontent.com/109744262/180985009-07675f0e-842a-4650-b9e9-6ab2e6ce4906.png)

**Comment by 2002smart** [comment]
对，点击“刷出载具”后直接卡死，现在查询直接显示“账号数据不符合逻辑”了，估计马上要被封号了。无语

**Comment by CrazyZhang666** [comment]
> 对，点击“刷出载具”后直接卡死，现在查询直接显示“账号数据不符合逻辑”了，估计马上要被封号了。无语

游戏更新后先不要使用小助手，等待小助手更新

**Comment by SmartDebug** [comment]
> 

电脑重启后已经可以正常进入线上模式了。也怪我自己，明知大更新后应当老老实实绿色游玩的。作者辛苦了

**Comment by SmartDebug** [comment]
> > 对，点击“刷出载具”后直接卡死，现在查询直接显示“账号数据不符合逻辑”了，估计马上要被封号了。无语
> 
> 游戏更新后先不要使用小助手，等待小助手更新

电脑重启后已经可以正常进入线上模式了。大更新后确实应当老老实实绿色游玩、等待小助手更新的。作者辛苦了
