### ISSUE TITLE
GTA5--7月26日更新问题

### ISSUE THREAD

**Issue by ssgdru** [CrazyZhang666/GTA5OnlineTools#474]
北京时间7月26日下午GTA5更新完之后，小助手的线上模式就失效了，除了故事模式功能和传送功能、玩家功能正常使用外，其余的均全部失效，望更新小助手解决问题！

**Comment by CrazyZhang666** [comment]
已更新，请下载最新版本小助手使用

**Comment by ssgdru** [comment]
还是无法使用，线下模式刷出载具的默认选项无法刷出，其余功能正常；线上模式功能全部无法使用



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月30日 12:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] GTA5--7月26日更新问题 (Issue #474) |

已更新，请下载最新版本小助手使用
