### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by lingfeng18250** [CrazyZhang666/GTA5OnlineTools#477]
Why does it show that 'T' is an invalid start of a value.Path: $ | LineNumber: 0 lBytePositionInLine: 0.
![error](https://user-images.githubusercontent.com/99312503/181288950-34e4544c-1a55-4ea7-9586-b2fbcad421aa.png)

**Comment by CrazyZhang666** [comment]
请重新下载小助手最新版本文件
