### ISSUE TITLE
大佬gta更新之后的问题

### ISSUE THREAD

**Issue by Sip09527** [CrazyZhang666/GTA5OnlineTools#478]
继夏日dlc出来之后，这个任务助手失效了，用不了现在，我只测试了地堡那一栏，无法最低价格入货那些，也无法最低时间生产研究那些了，F6传送也出问题了，他会直接给玩家传送到附近地下有时候，导致地堡军火运货失败

**Comment by MisakMikot** [comment]
CEO功能也失效了

**Comment by CrazyZhang666** [comment]
已更新，请下载最新版本小助手使用
