### ISSUE TITLE
Kiddion第一人称卡视角

### ISSUE THREAD

**Issue by Matoliet** [CrazyZhang666/GTA5OnlineTools#479]
现在用Kiddion的话第一人称太容易卡视角了，而且差事失败了直接卡在地图里，结束不了。

**Comment by CrazyZhang666** [comment]
Kiddion没有更新，还是旧版本

**Comment by Matoliet** [comment]
我昨天用YimMenu同样也会卡第一人称视角，就像fov被锁了一定角度一样。还有快捷键传送8太好使，好多次都要手动去到界面里用鼠标点才行。
