### ISSUE TITLE
功能失效反馈

### ISSUE THREAD

**Issue by zitenglu** [CrazyZhang666/GTA5OnlineTools#48]
在Kiddion外置辅助地堡刷钱这个过程中，触发生产这一选项按下确认后无反应，导致后续步骤无法进行。
During the process of brushing money in Kiddion's external auxiliary bunker, the trigger production option is pressed to confirm that there is no response, resulting in the next steps not being carried out.

**Comment by CrazyZhang666** [comment]
我还在调查这个问题

**Comment by zitenglu** [comment]
这个问题我后来解决了，这个失效问题的话，只能先等等，等他自己生产，然后这样子刷那么大概三次的话，这个功能就恢复正常了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月23日(星期二) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 功能失效反馈 (#48)





 
我还在调查这个问题

**Comment by CrazyZhang666** [comment]
我刚刚上线测试了，没啥问题，我是epic版本，部分玩家没有效果暂时原因未知，你可以尝试重新打开小助手

**Comment by zitenglu** [comment]
这个问题我后来解决了，这个失效问题的话，只能先等等，等他自己生产，然后这样子刷那么大概三次的话，这个功能就恢复正常了。我是steam版本，如果有人和我一样的问题，我的解决办法可以参考一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月23日(周二) 中午12:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 功能失效反馈 (#48)




 
我刚刚上线测试了，没啥问题，我是epic版本，部分玩家没有效果暂时原因未知，你可以尝试重新打开小助手

**Comment by CrazyZhang666** [comment]
👍🏻

**Comment by CrazyZhang666** [comment]
其实也可以尝试自己去偷取一次原材料，或者购买原材料一次

**Comment by zitenglu** [comment]
啧，我那个解决方法应该不太对，重启游戏后会失效，今天又鼓捣了一会，目前的解决方法是反复重启反复进退战局，这样可能有用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月23日(周二) 中午12:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 功能失效反馈 (#48)




 
👍🏻

**Comment by zitenglu** [comment]
我知道了，只有单人公开战局才能触发生产，用修改器可以创建公开战局，这样就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月23日(周二) 中午12:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 功能失效反馈 (#48)




 
其实也可以尝试自己去偷取一次原材料，或者购买原材料一次
