### ISSUE TITLE
笔记本使用YimMenu内置鼠标会出现卡在中间不动的情况

### ISSUE THREAD

**Issue by Wzh2002112233** [CrazyZhang666/GTA5OnlineTools#480]
内置菜单唤出时 移动鼠标会自动弹回屏幕正中央

**Comment by EQ-Aky** [comment]
我不是笔记本也是这个情况，但少部分人这样，个人感觉是系统问题，不兼容，换个版本

**Comment by EQ-Aky** [comment]
刚刚研究了一下，已经找到解决办法，把游戏里面的鼠标输入方式换成直接输入就可以解决了

**Comment by CrazyZhang666** [comment]
> 刚刚研究了一下，已经找到解决办法，把游戏里面的鼠标输入方式换成直接输入就可以解决了
👍
