### ISSUE TITLE
误操作导致YimMenu菜单呼出键绑定鼠标左键，游戏内无法呼出

### ISSUE THREAD

**Issue by BelonelyQ** [CrazyZhang666/GTA5OnlineTools#482]
怎么搞呀小助手初始化配置文件也没用，重新下载了也没用

**Comment by CrazyZhang666** [comment]
默认配置文件路径：C:\Users\用户名\AppData\Roaming\BigBaseV2
如果你不小心修改了某些设置导致Yim无法正常使用，请先卸载注入，到这个文件夹清理里面内容，然后重新注入Yim即可恢复默认设置

一键找到该路径：小助手主页面-》工具设置-》BigBaseV2配置目录

**Comment by BelonelyQ** [comment]
谢谢，谢谢
