### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by herowxx** [CrazyZhang666/GTA5OnlineTools#483]
@小助手已经是下载到最新版本了，运行库也是下载了最新的版本，但还是出现错误
![微信图片_20220730153028](https://user-images.githubusercontent.com/110279865/181880137-f737b6bb-cb24-4b41-bddf-d9a2ebf3760d.png)
![微信图片_20220730153028](https://user-images.githubusercontent.com/110279865/181880137-f737b6bb-cb24-4b41-bddf-d9a2ebf3760d.png)

**Comment by CrazyZhang666** [comment]
你可以来discord频道来反馈吗？我想了解一下具体的报错原因
