### ISSUE TITLE
小助手部分功能无法使用，bug反馈

### ISSUE THREAD

**Issue by sxp521** [CrazyZhang666/GTA5OnlineTools#49]
小助手部分功能无法使用subVersion v1.3.5.2，Kiddion最新版本v0.8.11除了无敌传送外都无法使用 外置菜单打开一分钟卡退掉线

**Comment by CrazyZhang666** [comment]
> 小助手部分功能无法使用subVersion v1.3.5.2，Kiddion最新版本v0.8.11除了无敌传送外都无法使用 外置菜单打开一分钟卡退掉线

subVersion v1.3.5.2尚未更新，Kiddion最新版本v0.8.11一切功能正常，外置菜单一切功能正常，你应该检查你的电脑系统，这个不是辅助问题

**Comment by sxp521** [comment]
![image](https://user-images.githubusercontent.com/79043001/113690918-83154180-96fe-11eb-858c-690e365c1076.png)辅助前面两个小菜单无法打开，偶尔还会出现卡退，辅助菜单的大部分功能不能用重启 重新安装都没有反应
