### ISSUE TITLE
外置菜单穿墙功能问题bug

### ISSUE THREAD

**Issue by chengzi5545** [CrazyZhang666/GTA5OnlineTools#492]
穿墙功能到现在一直使用不了 希望尽快修复一下 感谢了

**Comment by chengzi5545** [comment]
希望作者尽快修复一下 这个问题好几天了一直没有更新修复

**Comment by CrazyZhang666** [comment]
最新版本穿墙测试可以使用啊，你先勾选，然后按快捷键数字0开关功能，而且会又提示音，注意是数字0，而不是小键盘0
