### ISSUE TITLE
小助手外置菜单没有超级跳功能了

### ISSUE THREAD

**Issue by RiotGamesU** [CrazyZhang666/GTA5OnlineTools#503]
请问现在还有吗?有的话在什么地方呢?没有的话以后还会增加吗?

**Comment by CrazyZhang666** [comment]
因为风险问题暂时移除了，你可以使用Kiddion或者YimMenu里的

**Comment by RiotGamesU** [comment]
> 因为风险问题暂时移除了，你可以使用Kiddion或者YimMenu里的

thx
