### ISSUE TITLE
启动小助手异常

### ISSUE THREAD

**Issue by MCxingX** [CrazyZhang666/GTA5OnlineTools#510]
![1666018743345 jpg(2)](https://user-images.githubusercontent.com/96986991/196212297-24cc133b-dad6-4886-9c5b-28930bd57d01.jpg)
昨天都可以，关机再重启就不行了

**Comment by CrazyZhang666** [comment]
刚刚更新了3.0.5.7版本，修复了这个问题，你重新下载最新版本看看
