### ISSUE TITLE
3.0.5.7 版的 YimMenu 無法注入

### ISSUE THREAD

**Issue by PoorerImmune** [CrazyZhang666/GTA5OnlineTools#511]
這個倉庫的 Releases 也太乾淨了，完全沒有舊版本的下載連結，被迫更新後出現問題又無法回滾。按照正常的開發流程，沒有經過充分測試的版本通常會被標註為 Beta 版，而不是像你這樣剛一發佈就彈窗告知使用者儘快更新。這一版的 YimMenu 無法注入遊戲進程，一點下去，應用程式就假死，然後退出了。

**Comment by q410934219** [comment]
确实 我也有遇到这个情况 我都想退游了

**Comment by q410934219** [comment]
> 旧版本下载链接在蓝奏云盘，YimMenu注入下个版本修复
还是闪退 然后蓝奏云里还是只有新版本

**Comment by CrazyZhang666** [comment]
历史版本地址，
https://crazyzhang.lanzouf.com/b04n07ymb
![image](https://user-images.githubusercontent.com/28080853/196445001-18446fef-2e3b-4f24-9421-3b2d29d4cb7a.png)
![image](https://user-images.githubusercontent.com/28080853/196444702-075d704c-ce89-41d9-95fa-0e6722a79cc4.png)

**Comment by CrazyZhang666** [comment]
已经发布3.0.5.8版本更新，修复此bug
