### ISSUE TITLE
游戏问题

### ISSUE THREAD

**Issue by NQYBFS** [CrazyZhang666/GTA5OnlineTools#512]
似乎现在使用小助手会闪退 请问可以多试几次是什么问题吗 我开着小助手在游戏的时候 多人游戏玩一段时间就会闪退

**Comment by CrazyZhang666** [comment]
C:\ProgramData\GTA5OnlineTools\Log\ErrorLog
可以把这个文件夹最新的日志文件发一下

**Comment by YDD0606** [comment]
YimMenu刷出保镖然后上车会闪退
