### ISSUE TITLE
没反应

### ISSUE THREAD

**Issue by DIAONIMIE** [CrazyZhang666/GTA5OnlineTools#515]
我不知道是GTA5更新了还是什么，我玩的时候闪退，闪退后再次登陆GTA游戏显示需要更新。不知道是不是因为更新的原因，很多功能无法使用，例如开无敌以及补充武器弹药还有坐在车的载具里无法传送。

**Comment by rizardrrk** [comment]
+1（好像确实是因为更新了）

**Comment by soul-zym** [comment]
是的，游戏更新后出现了 （传送多次后闪退，坐在载具内无法传送，无法使用消除警星）目前发现这些问题，根据提示尝试清除程序释放目录内容后重启，问题依然存在
