### ISSUE TITLE
kiddion BUG

### ISSUE THREAD

**Issue by Kusunok1** [CrazyZhang666/GTA5OnlineTools#517]
can't open kiddion, 

unable to find required GTA5 offsets(13)

**Comment by kanshenmekanjiaji** [comment]
无法找到所需的 GTA5 偏移量（13） 是什么情况，我刷新dns缓存，初始化配置文件夹，gc垃圾回收，都点了以后，还是一样的问题，用的是最新版本的Kiddion，用了另一个YimMenu注入的，一进去就崩溃

**Comment by AAASJX** [comment]
我也是

**Comment by 7Luna** [comment]
俺也一样，GTA5更新的原因吧
