### ISSUE TITLE
更新错误

### ISSUE THREAD

**Issue by sdhauh** [CrazyZhang666/GTA5OnlineTools#52]
更新好像是被拦截了，但我也没有杀毒软件，系统是win10的
![6$C5EOYDYYVC8ZT 5QJFV72](https://user-images.githubusercontent.com/81280654/112258824-23e91300-8ca2-11eb-9103-e3895bbd1f3b.png)

**Comment by CrazyZhang666** [comment]
请关闭win10系统自带的杀毒软件

**Comment by ZYY5418** [comment]
这是怎么回事

![7{)_DGTKR68DY9@0J8 {(1X](https://user-images.githubusercontent.com/81253518/112295627-fd1fe200-8c8b-11eb-9c5a-e975ec252ce0.png)
![}2A2XG%@ILE%(N7@44T384I](https://user-images.githubusercontent.com/81253518/112295652-027d2c80-8c8c-11eb-9d6b-019b991b70e7.png)
![NFOS)C`7~JMFBBQ `H0~LL](https://user-images.githubusercontent.com/81253518/112295680-090ba400-8c8c-11eb-8f40-778252a3079f.png)
![3 OQXS}VCXGS$DI~V7MXX@2](https://user-images.githubusercontent.com/81253518/112295738-17f25680-8c8c-11eb-87f4-618c2a497271.png)
![@)YZ5S`YC61{V)QM)(A$KYL](https://user-images.githubusercontent.com/81253518/112295766-1d4fa100-8c8c-11eb-9628-556efc05b127.png)
![2AS ~F6B6U`89XOFB(638`7](https://user-images.githubusercontent.com/81253518/112295781-20e32800-8c8c-11eb-8b90-b84b19535a16.png)

**Comment by CrazyZhang666** [comment]
> 这是怎么回事
> 
> ![7{)_DGTKR68DY9@0J8 {(1X](https://user-images.githubusercontent.com/81253518/112295627-fd1fe200-8c8b-11eb-9c5a-e975ec252ce0.png)
> ![}2A2XG%@ILE%(N7@44T384I](https://user-images.githubusercontent.com/81253518/112295652-027d2c80-8c8c-11eb-9d6b-019b991b70e7.png)
> ![NFOS)C7~JMFBBQ H0~LL](https://user-images.githubusercontent.com/81253518/112295680-090ba400-8c8c-11eb-8f40-778252a3079f.png)
> ![3 OQXS}VCXGS$DI~V7MXX@2](https://user-images.githubusercontent.com/81253518/112295738-17f25680-8c8c-11eb-87f4-618c2a497271.png)
> ![@)YZ5SYC61{V)QM)(A$KYL](https://user-images.githubusercontent.com/81253518/112295766-1d4fa100-8c8c-11eb-9628-556efc05b127.png) ![2AS ~F6B6U89XOFB(638`7](https://user-images.githubusercontent.com/81253518/112295781-20e32800-8c8c-11eb-8b90-b84b19535a16.png)

用小助手外置菜单里的功能切换战局

**Comment by ZYY5418** [comment]
> > 这是怎么回事
> > ![7{)_DGTKR68DY9@0J8 {(1X](https://user-images.githubusercontent.com/81253518/112295627-fd1fe200-8c8b-11eb-9c5a-e975ec252ce0.png)
> > ![}2A2XG%@ILE%(N7@44T384I](https://user-images.githubusercontent.com/81253518/112295652-027d2c80-8c8c-11eb-9d6b-019b991b70e7.png)
> > ![NFOS)C7JMFBBQ H0LL](https://user-images.githubusercontent.com/81253518/112295680-090ba400-8c8c-11eb-8f40-778252a3079f.png)
> > ![3 OQXS}VCXGS$DI~V7MXX@2](https://user-images.githubusercontent.com/81253518/112295738-17f25680-8c8c-11eb-87f4-618c2a497271.png)
> > ![@)YZ5SYC61{V)QM)(A$KYL](https://user-images.githubusercontent.com/81253518/112295766-1d4fa100-8c8c-11eb-9628-556efc05b127.png) ![2AS ~F6B6U89XOFB(638`7](https://user-images.githubusercontent.com/81253518/112295781-20e32800-8c8c-11eb-8b90-b84b19535a16.png)
> 
> 用小助手外置菜单里的功能切换战局

好我试试
