### ISSUE TITLE
功能小助手

### ISSUE THREAD

**Issue by DXYCHEN** [CrazyZhang666/GTA5OnlineTools#53]
载具刷不出

**Comment by ZYY5418** [comment]
![T$MM 7$YFD1LL{8USJ3NA_Y](https://user-images.githubusercontent.com/81253518/112716991-be588900-8f24-11eb-9336-b710c25c3fb9.png)

**Comment by 1234XXXX550** [comment]
我也是这个问题你解决了吗地堡显示原材料空了但是我这里是满的

**Comment by CrazyZhang666** [comment]
需要使用外置辅助创建一个新的战局
