### ISSUE TITLE
大伙都是闪退+崩溃游戏吗

### ISSUE THREAD

**Issue by TRelymc** [CrazyZhang666/GTA5OnlineTools#539]
今晚更新了3.0.6.2，kiddon打不开，提示什么offset，然后yimwu也直接闪退

**Comment by hebianhuang** [comment]
gta5版本更新到了16.3然后辅助和现在的的版本不适配不知道啥时候才能弄好

**Comment by TRelymc** [comment]
> 

你这邮箱昵称太吓人了

**Comment by TRelymc** [comment]
> gta5版本更新到了16.3然后辅助和现在的的版本不适配不知道啥时候才能弄好

你这中文昵称太吓人了

**Comment by li666789** [comment]
只要开了辅助就游戏闪退
