### ISSUE TITLE
kiddion 在主界面的时候按下数字键0 菜单就没了

### ISSUE THREAD

**Issue by 80725015** [CrazyZhang666/GTA5OnlineTools#54]
![微信截图_20210326092730](https://user-images.githubusercontent.com/18433497/112564125-a34b2380-8e15-11eb-96f7-25215871cd5e.png)
在这个界面下，按数字0 返回是上一级菜单然后菜单就没有了。

**Comment by yfxfeng** [comment]
主界面按0就隐藏了，按-就呼出菜单

**Comment by 80725015** [comment]
> 主界面按0就隐藏了，按-就呼出菜单

oh, thx
