### ISSUE TITLE
小助手

### ISSUE THREAD

**Issue by SXZSG** [CrazyZhang666/GTA5OnlineTools#540]
刷车刷出蹂躏者P8的时候会闪退，注入的也这样

**Comment by CrazyZhang666** [comment]
v3.0.6.4版本 测试了下可用刷，我是邀请战局刷的
![image](https://user-images.githubusercontent.com/28080853/198240773-dccdc0d3-8aba-4b86-ac8a-7fc20a7c24b8.png)
