### ISSUE TITLE
小助手无法识别到gta5

### ISSUE THREAD

**Issue by weiyi598647** [CrazyZhang666/GTA5OnlineTools#546]
gta小助手识别不到我在pcstory.ml上的蘑菇下载器下载的gta5，我的联系方式是
邮箱：azxcvbbnm@outlook.com
QQ：2719284054

**Comment by CrazyZhang666** [comment]
小助手仅支持最新版本GTA5线上模式，单机线下你随便去找一个故事模式修改器就行
