### ISSUE TITLE
无法使用小助手外置菜单

### ISSUE THREAD

**Issue by Martinqe** [CrazyZhang666/GTA5OnlineTools#549]
用的是mac装的boot camp，是win10 ，在游戏进行是其他功能都可以使用，外置菜单一打开小助手就会报错然后无响应自动退出

**Comment by gaohai7** [comment]
https://user-images.githubusercontent.com/116833099/198890103-733e48f8-fcee-4586-a9a0-213221135848.mp4

**Comment by CrazyZhang666** [comment]
点一下这个恢复配置文件，如果还奔溃，把错误日志发到这里
C:\ProgramData\GTA5OnlineTools\Log\ErrorLog
![image](https://user-images.githubusercontent.com/28080853/198998877-801b921d-6187-4b3f-a682-3caa1b06045f.png)

**Comment by CrazyZhang666** [comment]
[GTA5线上小助手]Bug测试群，可以加群详细描述下问题
747753199
