### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by MeeH0tel** [CrazyZhang666/GTA5OnlineTools#555]
### 小助手版本号

3.0.7.3

### 战局模式

公开战局

### 玩家数量

1

### 具体功能

一打开小助手外置菜单整个小助手软件就闪退了

### 问题描述

从3.0.7.3，11月6日下载了最新版本3.0.7.3发生的问题，以前几个版本都没问题

**Comment by CrazyZhang666** [comment]
C:\ProgramData\GTA5OnlineTools 把这个文件夹清空后再打开小助手，而且小助手最新版本是3.0.7.4
