### ISSUE TITLE
[Bug]: Kiddion故事模式里的刷车车刚刷出来会消失

### ISSUE THREAD

**Issue by liangzaihenliang** [CrazyZhang666/GTA5OnlineTools#559]
### 助手版本

3.0.7.6

### 战局模式

故事模式

### 玩家数量

1

### 杀毒软件

windows安全中心

### 具体功能

Kiddion外置辅助菜单-故事模式-刷出载具

### 问题描述

在空地上 无遮挡物 车会消失

**Comment by CrazyZhang666** [comment]
勾选 启用多人模式载具 按钮看看
