### ISSUE TITLE
 [Bug]: 小助手开启时会闪退

### ISSUE THREAD

**Issue by AgatsumaZen1tsu** [CrazyZhang666/GTA5OnlineTools#560]
### 助手版本

3.0.7.7

### 战局模式

公开战局

### 玩家数量

1

### 杀毒软件

无运行

### 具体功能

开启时会闪退

### 问题描述

开启时闪退, 提示选择目录

**Comment by CrazyZhang666** [comment]
先手动删除  C:\ProgramData\GTA5OnlineTools 这个文件夹，然后再打开小助手，杀毒要关闭
