### ISSUE TITLE
[Bug]: 注入YimMenu 4人或者3人在邀请战局会直接崩溃卡死直接退至桌面

### ISSUE THREAD

**Issue by LDGNRV** [CrazyZhang666/GTA5OnlineTools#563]
### 助手版本

3.0.7.8

### 战局模式

邀请战局

### 玩家数量

4

### 杀毒软件

否

### 具体功能

Yinmenu注入试菜单

### 问题描述

注入YimMenu 单人或者3人或者4人在邀请战局会直接崩溃卡死直接退至桌面

**Comment by ppr64** [comment]
YimMenu菜单删除了以后还会回来吗
