### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kevjin3215** [CrazyZhang666/GTA5OnlineTools#571]
### 助手版本

3.0.7.9

### 战局模式

非公开好友战局；邀请战局

### 玩家数量

1

### 杀毒软件

Windows安全中心

### 具体功能

小助手外置辅助和kiddion 刷出线上载具均无效

### 问题描述

使用小助手外置辅助和kiddion刷出线上载具全部无效，人物面前有足够空地，但是点击刷出无反应。

**Comment by sch-lda** [comment]
目前需要等Kiddion作者更新适配，Kiddion作者警告称更新之前不要使用
