### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xhyxhy6666** [CrazyZhang666/GTA5OnlineTools#575]
### 助手版本

3.0.7.9

### 战局模式

公开战局

### 玩家数量

1 

### 杀毒软件

否

### 具体功能

小助手外设辅助》刷出载具》功能无效

### 问题描述

载具刷不出来

**Comment by sch-lda** [comment]
小助手作者最近可能比较忙，或者在等Kiddion等第三方插件全部更完，或者准备弃坑了。实在着急刷车就去用YimMenu https://github.com/YimMenu/YimMenu
