### ISSUE TITLE
[Bug]: GTAhax失效 

### ISSUE THREAD

**Issue by 1314520yby** [CrazyZhang666/GTA5OnlineTools#576]
### 助手版本

最新版本

### 战局模式

所有战局

### 玩家数量

全部

### 杀毒软件

裸奔

### 具体功能

gtahax失效无法跳过所有任务的前置

### 问题描述

gta更新后无法使用

**Comment by sch-lda** [comment]
小助手作者最近可能比较忙，或者在等Kiddion等第三方插件全部更完，或者准备弃坑了。实在着急就自己找最新的Gtahax https://www.unknowncheats.me/forum/grand-theft-auto-v/461672-gtahax-1-64-external-thread-3-a.html
和最新的抢劫任务修改教程 https://www.unknowncheats.me/forum/grand-theft-auto-v/431801-cayo-perico-heist-click.html
国外抢劫任务编辑器作者阳了，也推迟更新了，所以目前没有一键修改的方案了
