### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wmyTMlaila** [CrazyZhang666/GTA5OnlineTools#577]
### 助手版本

3.0.7.9

### 战局模式

任何线上战局

### 玩家数量

1

### 杀毒软件

没有

### 具体功能

刷出线上载具 点哪个都一样

### 问题描述

刷不出来

**Comment by sch-lda** [comment]
小助手作者最近可能比较忙，或者在等Kiddion等第三方插件全部更完，或者准备弃坑了。实在着急刷车就去用YimMenu https://github.com/YimMenu/YimMenu
