### ISSUE TITLE
[Bug]: 无法刷车，麻烦快点更新，谢谢

### ISSUE THREAD

**Issue by zdd0818** [CrazyZhang666/GTA5OnlineTools#578]
### 助手版本

3.0.7.9

### 战局模式

公开战局

### 玩家数量

1

### 杀毒软件

无

### 具体功能

快点更新，没法刷车

### 问题描述

无法刷车，麻烦更新

**Comment by sch-lda** [comment]
小助手作者最近可能比较忙，或者在等Kiddion等第三方插件全部更完，或者准备弃坑了。实在着急刷车就去用YimMenu https://github.com/YimMenu/YimMenu
