### ISSUE TITLE
[Bug]: Kiddion小助手 最新版本无法刷车，弹窗提示检查到不兼容错误，大多数功能无法使用

### ISSUE THREAD

**Issue by a1509773059** [CrazyZhang666/GTA5OnlineTools#579]
### 助手版本

3.0.7.9

### 战局模式

战局正常

### 玩家数量

1

### 杀毒软件

没运行

### 具体功能

无法刷出载具，打开Kiddion后弹窗显示检查到不兼容错误，大多数功能无法正常使用

### 问题描述

之前一直玩都没事，今天下载后才发生的

**Comment by sch-lda** [comment]
目前需要等Kiddion作者更新适配，Kiddion作者警告称更新之前不要使用,Kiddion作者不更新小助手作者也不能更新，Kiddion也不开源。实在需要刷车就去用YimMenu https://github.com/YimMenu/YimMenu

**Comment by NQBFS** [comment]
> 目前需要等Kiddion作者更新适配，Kiddion作者警告称更新之前不要使用，Kiddion作者不更新小助手作者也不能更新，Kiddion也不开源。实在需要刷车就去用YimMenu https://github.com/YimMenu/YimMenu

好像现在kiddion自己使用开无敌与弹药无限和传送是没问题的 其他功能还是暂时不要使用
