### ISSUE TITLE
多种功能失效，无法跳前置，无法刷车等，跪求3.7.1.0更新。

### ISSUE THREAD

**Issue by nemo121385** [CrazyZhang666/GTA5OnlineTools#580]
无法跳前置，夜视热成像断电不好用，使用后闪退，车辆无法刷出，前置任务无法跳过

**Comment by sch-lda** [comment]
小助手作者最近可能比较忙，或者在等Kiddion等第三方插件全部更完，或者准备弃坑了。实在着急刷车就去用YimMenu https://github.com/YimMenu/YimMenu
需要改抢劫任务就自己找最新的Gtahax https://www.unknowncheats.me/forum/grand-theft-auto-v/461672-gtahax-1-64-external-thread-3-a.html
和最新的抢劫任务修改教程 https://www.unknowncheats.me/forum/grand-theft-auto-v/431801-cayo-perico-heist-click.html
国外抢劫任务编辑器作者阳了，也推迟更新了，所以目前没有一键修改的方案了
