### ISSUE TITLE
关于GTA5线上小助手的bug

### ISSUE THREAD

**Issue by hihihitooth** [CrazyZhang666/GTA5OnlineTools#616]
gta5线上小助手贼好用！但是在使用过程中我发现了一个bug：打开gta5后无法使用小助手功能并提示未发现gta5游戏进程，可我已经打开了gta5

**Comment by DASQ34** [comment]
我也是这样

**Comment by Dream-yyk** [comment]
gtaol版本更新了，小助手还没适配1.66
