### ISSUE TITLE
小助手注入

### ISSUE THREAD

**Issue by 55U55** [CrazyZhang666/GTA5OnlineTools#622]
我的小助手注入有问题，注入了以后呢他不是先会把那个代码注入游戏嘛，我进到游戏以后我点那个小键盘上的那个零然后没法启动这个注入然后我还没法卸载，重启程序还有那个删除文件夹我都试过了然后都没用，然后我还把这个程序删了重下也是一样的没用，不知道是因为什么😥

**Comment by 55U55** [comment]
然后这个注入了以后呢，GTA5游戏窗口也没有那个代码窗口

**Comment by 55U55** [comment]
请大大更新一下

**Comment by nijk7** [comment]
我的也是，那个第一个还是打不开，打开之后出现两次英文字，就自动关了，我把那英文翻译了一下说是与gt5不匹配啥的，然后第三个能注入成功，就是在游戏里打不开那个窗口

**Comment by 55U55** [comment]
我试过了那个注入是注入成功的但是呢就是在游戏里面打不开但是呢功能是有的

**Comment by 55U55** [comment]
不知道是因为什么

**Comment by nijk7** [comment]
你的功能还有？那比我好啊

**Comment by nijk7** [comment]
我的能注入成功，先是打不开，再是啥功能也没有，哎

**Comment by nijk7** [comment]
作者大大，加油，我们期待你的更新
