### ISSUE TITLE
yimmenu注入失败

### ISSUE THREAD

**Issue by pzy2000** [CrazyZhang666/GTA5OnlineTools#626]
错误提示如下：
[01:08:31][INFO/main.cpp:58]: Yim's Menu Initializing
[01:08:31][INFO/main.cpp:59]: Git Info
	Branch:	master
	Hash:	b74980ccbb9bdd0c4e15f2bbd343bed97f6f3bd2-dirty
	Date:	Wed Dec 21 10:21:18 2022
[01:08:31][INFO/main.cpp:62]: Thread pool initialized.
[01:08:31][DEBUG/thread_pool.cpp:21]: Allocating 20 threads in thread pool.
[01:08:31][INFO/globals.cpp:79]: Updating settings.
[01:08:31][INFO/main.cpp:66]: Settings Loaded.
Found 'SCREEN_RESOLUTION' GTA5.exe+0x16A1DF
[01:08:31][WARNING/batch.cpp:37]: Failed to find 'RC'.
Found 'MWL' GTA5.exe+0x5D865F
Found 'GS' GTA5.exe+0x2C0F40
Found 'ISA' GTA5.exe+0xEF13
Found 'PF' GTA5.exe+0x72DA0C
Found 'NPM' GTA5.exe+0x1095B84
Found 'NH' GTA5.exe+0x15F6931
Found 'FV' GTA5.exe+0x15F38AC
Found 'ST' GTA5.exe+0x15F6887
Found 'SP' GTA5.exe+0xA42C59
Found 'SG' GTA5.exe+0x15F61D8
Found 'CGSHM' GTA5.exe+0x15FB245
Found 'S' GTA5.exe+0x1368E39
Found 'WMSB' GTA5.exe+0xCED251
Found 'NRF' GTA5.exe+0x2CC15
Found 'GTS' GTA5.exe+0x15F63A0
Found 'TK' GTA5.exe+0xA46D3C
Found 'TSE' GTA5.exe+0xD8093C
Found 'REH' GTA5.exe+0x16AD4C4
Found 'SEA' GTA5.exe+0x145AB61
Found 'RBWD' GTA5.exe+0x1414A0D
Found 'RBA' GTA5.exe+0x1306D60
Found 'RBS' GTA5.exe+0x1193FA4
Found 'RBB' GTA5.exe+0x1148597
Found 'WBD' GTA5.exe+0x1148AE0
Found 'WBQ' GTA5.exe+0x130EA74
Found 'WBI64' GTA5.exe+0x11975D5
Found 'WBI32' GTA5.exe+0x11964A7
Found 'WBB' GTA5.exe+0x119602C
Found 'WBA' GTA5.exe+0x1697A8E
Found 'WPGSDN' GTA5.exe+0x10ED62C
Found 'RCOE-Patch' GTA5.exe+0xCDC45C
Found 'RI' GTA5.exe+0x1FCC
Found 'PTH' GTA5.exe+0x15FAD01
Found 'GSH' GTA5.exe+0x15FC1D0
Found 'BE' GTA5.exe+0xA6C5D8
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'SNITL'.
Found 'CNOM' GTA5.exe+0xB192B0
Found 'NPMI' GTA5.exe+0x10F8053
Found 'NPMS' GTA5.exe+0x112C4D2
Found 'FR' GTA5.exe+0xCD9114
Found 'GSCFWC' GTA5.exe+0xA41DBC
Found 'GGCC' GTA5.exe+0xA76906
Found 'GPR' GTA5.exe+0x11B2264
Found 'WPGDN' GTA5.exe+0x10EE148
Found 'RNM' GTA5.exe+0x142D6ED
Found 'GNED' GTA5.exe+0x1A04AA0
Found 'API' GTA5.exe+0x16B35D8
Found 'RCC' GTA5.exe+0x1102618
Found 'CAD' GTA5.exe+0x1102EB6
Found 'RCS/GSTFT/GNOFP/GNO/GSTI' GTA5.exe+0x11035D1
Found 'RBIST' GTA5.exe+0x1102798
Found 'MHT' GTA5.exe+0xB24E
Found 'GLT' GTA5.exe+0xDA0DBB
Found 'MCF' GTA5.exe+0x167116A
Found 'N' GTA5.exe+0x1061009
Found 'RENC' GTA5.exe+0x145981A
Found 'FDGD' GTA5.exe+0x12FA78F
Found 'FDS' GTA5.exe+0x12FD2DC
Found 'FPFC' GTA5.exe+0x12F712A
Found 'FPFOA' GTA5.exe+0x12FC018
Found 'FPFM' GTA5.exe+0x12FD552
Found 'FPFUM' GTA5.exe+0x6A2D0F
Found 'GVOV' GTA5.exe+0x2E2330
Found 'IMCD' GTA5.exe+0x53863D
Found 'SCP' GTA5.exe+0x2EF758
Found 'SCM' GTA5.exe+0x10A7B21
Found 'SGSBGH' GTA5.exe+0x43D51D
Found 'SGSBGH' GTA5.exe+0x13F4B9A
Found 'JSBI' GTA5.exe+0x1170C20
Found 'INT' GTA5.exe+0x15F2FD2
Found 'VM' GTA5.exe+0x15F61E2
Found 'GU' GTA5.exe+0x141321E
Found 'HT' GTA5.exe+0x13E792D
Found 'PGI' GTA5.exe+0x1403FBC
Found 'PIGI' GTA5.exe+0x10A199B
Found 'C' GTA5.exe+0xCDB140
Found 'SDEGSDN' GTA5.exe+0x110C7C8
Found 'SPIDN' GTA5.exe+0x110EB4C
Found 'SVGDN' GTA5.exe+0x11162D4
Found 'GVGAS' GTA5.exe+0x10F05A4
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'HJR'.
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'WJRD'.
Found 'QP' GTA5.exe+0x145197E
Found 'SGS' GTA5.exe+0x11899BC
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'APTS'.
Found 'SCNM' GTA5.exe+0x11E6C5A
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'PMFR'.
Found 'SPDM' GTA5.exe+0x1118738
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'SPDM'.
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'IMSV'.
Found 'SND' GTA5.exe+0xF4C947
Found 'RR' GTA5.exe+0xC0BD23
Found 'GCP&SRGC' GTA5.exe+0x11E7AAD
Found 'HRGC' GTA5.exe+0x11E07B2
Found 'BNA' GTA5.exe+0x16BD584
Found 'BP' GTA5.exe+0x16BD76E
Found 'RS' GTA5.exe+0x3AE35EE
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'SPDM'.
Found 'STOPVT' GTA5.exe+0x69A0E4
Found 'CD' GTA5.exe+0x18CE97
Found 'SCI' GTA5.exe+0x13D19D3
Found 'CSH' GTA5.exe+0xA34094
Found 'CW' GTA5.exe+0x1646E7
Found 'WBGH' GTA5.exe+0x114A0B4
Found 'RBGH' GTA5.exe+0x114A1A8
Found 'CAC' GTA5.exe+0x147FFF4
Found 'IDC' GTA5.exe+0x676578
Found 'ESI' GTA5.exe+0x140BBD4
[01:08:32][WARNING/batch.cpp:37]: Failed to find 'DSI'.
Found 'CSSJC' GTA5.exe+0x1155416
Found 'CSJJC' GTA5.exe+0x15FAB7A
Found 'NTQVMC' GTA5.exe+0x1516AED
Found 'MFO' GTA5.exe+0xA6F6EF
Found 'LCF' GTA5.exe+0x5D6874
Found 'SAACF' GTA5.exe+0xA8A8A8
Found 'SJD' GTA5.exe+0xA8A44C
Found 'NT' GTA5.exe+0xCCB3AE
Found 'SNT' GTA5.exe+0x1459FFD
Found 'QD' GTA5.exe+0x12E4DB0
Found 'ICF' GTA5.exe+0xA9F5F7
Found 'CGI' GTA5.exe+0x10A1933
[01:08:33][WARNING/main.cpp:193]: Failed to find some patterns.
[01:08:33][INFO/main.cpp:196]: Farewell!

大致猜测：可能是yimmenu未跟随作者版本更新到最新版

**Comment by Hans155922** [comment]
把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成[https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip](https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip)里的，要重命名成YimMenu.dll！！
我在尝试汉化，工程量有点大，，，，

**Comment by pzy2000** [comment]
我也在做yimmenu的汉化哈哈哈哈哈，感觉主菜单那边的汉化特别难搞。（我是在修改zh_CN.json文件）
