### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by sxp521** [CrazyZhang666/GTA5OnlineTools#63]
![image](https://user-images.githubusercontent.com/79043001/113690918-83154180-96fe-11eb-858c-690e365c1076.png)辅助前面两个小菜单无法打开，偶尔还会出现卡退，辅助菜单的大部分功能不能用重启 重新安装都没有反应

**Comment by CrazyZhang666** [comment]
关闭杀毒软件，这种就是杀毒导致的，目前全部功能可用
