### ISSUE TITLE
not work 

### ISSUE THREAD

**Issue by tieto419** [CrazyZhang666/GTA5OnlineTools#632]
not work  last update

**Comment by Hans155922** [comment]
如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll缓存https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip里的YimMenu.dll就行，，我在尝试汉化，工程量有点大，，，，

**Comment by Hans155922** [comment]
如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip里的，要重命名成YimMenu.dll！！
我在尝试汉化，工程量有点大，，，，
