### ISSUE TITLE
怎么完全重新卸载和安装小助手，我现在无论是YimMenu的注入还是Kiddion都启动不了

### ISSUE THREAD

**Issue by Matoliet** [CrazyZhang666/GTA5OnlineTools#635]
怎么重零开始完全重新卸载所以注入目录文件和重新安装小助手，我现在无论是YimMenu的注入还是Kiddion都启动不了。

**Comment by kichampion6** [comment]
因为在线版本更新了吧

**Comment by Hans155922** [comment]
如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成[https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip里的，要重命名成YimMenu.dll！！](https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip%E9%87%8C%E7%9A%84%EF%BC%8C%E8%A6%81%E9%87%8D%E5%91%BD%E5%90%8D%E6%88%90YimMenu.dll%EF%BC%81%EF%BC%81)
我在尝试汉化，工程量有点大，，，，

**Comment by Hans155922** [comment]
如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成[https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip里的，要重命名成YimMenu.dll！！](https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip%E9%87%8C%E7%9A%84%EF%BC%8C%E8%A6%81%E9%87%8D%E5%91%BD%E5%90%8D%E6%88%90YimMenu.dll%EF%BC%81%EF%BC%81)
我在尝试汉化，工程量有点大，，，，

**Comment by Hans155922** [comment]
如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成[https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip](https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip)里的，要重命名成YimMenu.dll！！
我在尝试汉化，工程量有点大，，，，
