### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by 2115544** [CrazyZhang666/GTA5OnlineTools#636]
Now update can play no localization“YimMenu”Injector how injection，I just play the game and contact and don't understand these things

**Comment by Hans155922** [comment]
如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成[https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip](https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip)里的，要重命名成YimMenu.dll！！
我在尝试汉化，工程量有点大，，，，
