### ISSUE TITLE
第三方插件问题

### ISSUE THREAD

**Issue by gwbgs** [CrazyZhang666/GTA5OnlineTools#637]
kiddon和yimmenu都不支持目前更新的线上版本，希望作者大大保持更新

**Comment by Hans155922** [comment]
如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成[https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip](https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip)里的，要重命名成YimMenu.dll！！
我在尝试汉化，工程量有点大，，，，

**Comment by CrazyZhang666** [comment]
yim问题可以看这个教程 https://crazyzhang.cn/gta5/yimm.html

**Comment by Dream-yyk** [comment]
> 如果是YimMenu的话。把C:\ProgramData\GTA5OnlineTools\Inject目录下的YimMenu.dll换成https://nightly.link/YimMenu/YimMenu/actions/artifacts/541142237.zip里的，要重命名成YimMenu.dll！！ 我在尝试汉化，工程量有点大，，，，

看了 #632 的评论了，目前用`https://github.com/YimMenu/YimMenu/releases/download/nightly/YimMenu.dll`替换文件已经能正常使用功能，不过汉化缺失还是很多，期待大佬和官方的汉化吧(○｀ 3′○)
ps：其实英文自己也看的懂，不过还是汉化更舒服啦（狗头保命）

**Comment by CrazyZhang666** [comment]
yim完整汉化已更新
