### ISSUE TITLE
一直忘记提的一个bug之摩托帮自动补货

### ISSUE THREAD

**Issue by Dream-yyk** [CrazyZhang666/GTA5OnlineTools#638]
位于stat自动化脚本中，执行后第一次会正确显示已到达xx工厂的通知但是实际货物数量并未改变，之后每过不久都会发消息提示“你购买的原材料已到达null”（如下图）
而且该功能会永久修改到gtaol存档中并无法撤销，自己手动在阳关道买的货物也同样无法送到各工厂
希望作者大大可以修复一下ヾ(•ω•`)o
![Grand Theft Auto V 2023_2_4 16_50_29](https://user-images.githubusercontent.com/72236930/216768694-1f5aaf39-2544-4058-862b-a6a5c6fdfa28.png)

**Comment by CrazyZhang666** [comment]
收到反馈

**Comment by Dream-yyk** [comment]
期待修复，现在厂全关了还能收到补货的提示（
就挺离谱
