### ISSUE TITLE
希望能添加的解锁小功能，非常感谢。 

### ISSUE THREAD

**Issue by leehaaron** [CrazyZhang666/GTA5OnlineTools#64]
你好作者，感谢你制作这个辅助器，帮了很大的忙。有一个解锁项目在现有的辅助器好像没办法完成，所以希望可以加入。

游戏里面的钻石赌场抢劫，有一个隐藏的8%分红枪手 - 派翠克·麦克瑞利。自赌场更新的两年多至今，即使我已经把全部赌场抢劫的方式通关过一遍，但我一直无法解锁他，所有刷新点我都长时间等过，所有网上的方法都已试过，实在没有办法。而因此也导致两个相关奖章一直未能完成。

我看到辅助里面有选项能一键解锁同样隐藏的赌场抢劫骇客，所以很希望能加入一个功能，以能够解锁这个困扰的枪手，相信除了我，也有很多玩家未能解锁他，希望能帮帮忙。

这个问题已困扰我很久了，网上有很多玩家也因为有bug而不能解锁，如果能达成这个解锁功能，付费我也愿意。非常感谢。

**Comment by CrazyZhang666** [comment]
试试Bread里的全解锁
