### ISSUE TITLE
kiddion的问题

### ISSUE THREAD

**Issue by M1nGX1nnnnn** [CrazyZhang666/GTA5OnlineTools#641]
warning:lncompatible game version detected（2824）！
please note most functions usually dont work and may seriously harm your game！

unable to find required GTA5 offsets（19）

**Comment by CrazyZhang666** [comment]
kiddion目前尚未更新

**Comment by ZihanAn** [comment]
不知道可不可以共建这个呀？期待！！！

**Comment by FruitDuo** [comment]
kiddion更新了记得T一下，谢谢

**Comment by CrazyZhang666** [comment]
kiddion已更新
