### ISSUE TITLE
无法使用出现2824错误

### ISSUE THREAD

**Issue by zhu85623** [CrazyZhang666/GTA5OnlineTools#644]
![111](https://user-images.githubusercontent.com/124883307/217797821-98705d93-8f0a-4d96-827b-ec787f3410c8.jpg)
![222](https://user-images.githubusercontent.com/124883307/217797828-776d9004-c9e5-4c79-972d-800d953b3615.jpg)
![333](https://user-images.githubusercontent.com/124883307/217797837-da799ab5-2564-49a0-b9d4-51eefa09e804.jpg)

**Comment by zhu85623** [comment]
救救我叭

**Comment by nijk7** [comment]
我也是这样的，自从那次r星更新之后，我就一直打不开

**Comment by fast7990** [comment]
me to
