### ISSUE TITLE
kiddion菜单错误

### ISSUE THREAD

**Issue by Ronge688** [CrazyZhang666/GTA5OnlineTools#647]
![G6V_1R SJ1K}XVTKZ 6HJ@D](https://user-images.githubusercontent.com/124894373/217827104-9e5ec33c-3868-474f-b7e8-f3579f53db10.png)

**Comment by Ronge688** [comment]
![XR4T1BSP68L62F_H}332263](https://user-images.githubusercontent.com/124894373/217827279-f564aaf9-bfac-4ebc-b9fa-305780bd93e0.png)

**Comment by Apasser-by** [comment]
我也一样

**Comment by CrazyZhang666** [comment]
请等待更新，目前都无法使用
