### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jiumengyya** [CrazyZhang666/GTA5OnlineTools#648]
Yim Menu汉化有问题，大部分都是英文，小部分字体显示为问号

**Comment by CrazyZhang666** [comment]
YimMenu目前为官方中文，目前还不完善

**Comment by jiumengyya** [comment]
之前不是汉化的很完整吗

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月11日 23:35
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [CrazyZhang666/GTA5OnlineTools] 1 (Issue #648)


YimMenu目前为官方中文，目前还不完善

―
