### ISSUE TITLE
所有轰炸机按e无反应无法投弹

### ISSUE THREAD

**Issue by YangGeGe** [CrazyZhang666/GTA5OnlineTools#652]
带轰炸功能的飞机按e无反应，包括b11突击部队，阿尔科诺斯特登等

**Comment by YangGeGe** [comment]
是因为刷出的载具是不满改的

**Comment by Aigio1064** [comment]
> 是因为刷出的载具是不满改的

其实...在代码方面，确实是满改的，自动选择改装选项里最下面的一个改装，  
目前还没有满改的定义，个人需求是不一样的，所以使用载具修改器自行编辑才是最好的选择；  

你可能会说:"那每个载具都搞一套配置不就行了？"，  
但这是不现实的，GTAV的载具量非常大，这导致如果真要这样弄的话将消耗大量时间，  
还有就是格式的统一，不同的人有不同的写法，如果要适配所有提交者的配置，那么工作量也还是很大，  
定义统一的标准也需要其他人的配合。

**Comment by CrazyZhang666** [comment]
这个下次更新修复

**Comment by CrazyZhang666** [comment]
已修复
