### ISSUE TITLE
求解答 yim无法和别人组队

### ISSUE THREAD

**Issue by Desmond5418** [CrazyZhang666/GTA5OnlineTools#656]
在使用yim的时候无法和别人组队？开启差事别人卡云进不到房间 卸载后就没有这个问题  不知道是设置在哪出的问题 希望能解答下 谢谢！

**Comment by CrazyZhang666** [comment]
这个是yim默认开启的防护导致的，你使用最新版本小助手，然后清理yim缓存，再注入，最新版本yim默认关闭全部功能的

**Comment by Desmond5418** [comment]
非常感谢您的回答~&nbsp; 我在开发者问答区找到了您的一个回答&nbsp; 已经全部修改成默认关闭 目前没有测试 感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月19日(星期天) 晚上9:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 求解答 yim无法和别人组队 (Issue #656)





 
这个是yim默认开启的防护导致的，你使用最新版本小助手，然后清理yim缓存，再注入，最新版本yim默认关闭全部功能的

**Comment by Desmond5418** [comment]
我不知道关闭的回答还能不能继续发问 经过测试依然存在这些问题 全部恢复默认 全部关闭 完全全新的yim依然存在这个问题。所有选项都没有勾选 依然无法组队 会卡在云上 队友进不来
