### ISSUE TITLE
WIN7玩到一半老是未响应停止工作怎么回事

### ISSUE THREAD

**Issue by Matoliet** [CrazyZhang666/GTA5OnlineTools#657]
昨天更新小助手之后游戏老是崩溃，Win7 64位，玩到一半就老是程序未响应停止工作怎么回事呢？非公开邀请战局，没在公开战局。只有我和朋友两个人。应该不会是输入法的问题啊。

**Comment by CrazyZhang666** [comment]
你具体用了哪些功能呢？小助手里功能比较多，你可以说下都用了哪个界面里的哪些功能
