### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by zxc994** [CrazyZhang666/GTA5OnlineTools#66]
希望可以增加一个辅助每项的说明，可以单独弄一个文件，像禁用武器恢复我一直不知道是什么作用，而且我想增加一个可以永久删掉不想要的武器的功能，可以用GTAHAX，希望作者大大采纳

**Comment by CrazyZhang666** [comment]
这个是翻译过来的，有的翻译不准确，暂时没有永久删除武器的办法，游戏机制就是这样
