### ISSUE TITLE
v3.1.0.0版本打开小助手外置菜单闪退

### ISSUE THREAD

**Issue by zgojin** [CrazyZhang666/GTA5OnlineTools#662]

**Comment by ikun55** [comment]
我的也打不开

**Comment by zhilings** [comment]
我的也打不开

**Comment by CrazyZhang666** [comment]
https://crazyzhang.cn/help/#%E6%89%93%E5%BC%80%E9%97%AA%E9%80%80%E6%88%96%E5%B4%A9%E6%BA%83

![image](https://user-images.githubusercontent.com/28080853/221407300-b421c259-0881-4fd7-a655-1419f539c11e.png)
