### ISSUE TITLE
崩溃日志

### ISSUE THREAD

**Issue by qfmyg800** [CrazyZhang666/GTA5OnlineTools#664]
[#Crash#20230227_05-36-12_3224.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/10834972/Crash.20230227_05-36-12_3224.log)

**Comment by CrazyZhang666** [comment]
可以尝试右键管理员运行小助手

**Comment by CrazyZhang666** [comment]
还有，你的GTA5游戏路径发一下，如果是虚拟路径，可能会有问题

**Comment by qfmyg800** [comment]
好的👌，回去试试，辛苦了！



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月27日 08:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 崩溃日志 (Issue #664) |

可以尝试右键管理员运行小助手

**Comment by qfmyg800** [comment]
已经解决了，按照用管理员启动的方法。




| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月27日 08:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 崩溃日志 (Issue #664) |

还有，你的GTA5游戏路径发一下，如果是虚拟路径，可能会有问题
