### ISSUE TITLE
反馈一个BUG

### ISSUE THREAD

**Issue by cloudrocc** [CrazyZhang666/GTA5OnlineTools#665]
你好，CrazyZhang
我想反馈一个BUG，该BUG可能会导致在进行任务 首轮募资:窃取冰毒 时出现无法提示偷取油罐车的情况
具体触发原因未知，当我们将小助手全部退出重新上游戏进行任务时，没有在出现此情况
希望您能留意^^
我会一直支持小助手

**Comment by CrazyZhang666** [comment]
你看看是不是使用yim导致的

**Comment by cloudrocc** [comment]
感谢大佬回复^^
不是yim导致的，用的是小助手外置菜单，在邀请战局。
具体情况是第一天做的时候发现无法触发偷取油罐车，以为是网络原因。第二天发现问题依旧，于是我去搜索了一下，发现贴吧有相同情况，我们尝试关闭进程并重新打开，然后就没有此问题了
