### ISSUE TITLE
Yim菜单注入后游戏直接闪退

### ISSUE THREAD

**Issue by SAINT0430** [CrazyZhang666/GTA5OnlineTools#668]
这是日志文件，希望有懂的大佬可以指点一下
![image](https://user-images.githubusercontent.com/111118648/230321584-819f69b3-1089-449f-9b9d-2c97973082a7.jpeg)

**Comment by CrazyZhang666** [comment]
可以看一下这个教程，https://crazyzhang.cn/yimmenu/74e4.html

其实就是，先点这个按钮清空缓存，然后打开游戏，进入邀请战局，
完全进入邀请战局后，在注入并按照提示更新缓存即可（如果游戏还没有准备好就注入，大概率崩溃）
![image](https://user-images.githubusercontent.com/28080853/230522735-7a855ed5-968e-4663-b7fb-8b737250177c.png)
