### ISSUE TITLE
关于小助手外置菜单ESP功能反馈（BUG）

### ISSUE THREAD

**Issue by LittlePlumqwq** [CrazyZhang666/GTA5OnlineTools#669]
在使用YimMenu的同时开启小助手外置菜单中的ESP功能（勾选“非游戏状态隐藏”）将导致ESP生效在Yimmenu的外置窗口上，且切换至GTAV游戏进程后无法显示。
解决办法（临时）：取消勾选“非游戏状态隐藏”，并将Yimmenu外置窗口拉到最大
↑个人摸索出的办法，希望作者修复（小助手ESP找NPC真的很好用！很多辅助都不能显示NPC）

**Comment by Gabriel-Antonio-Sephiroth** [comment]
[#Crash#20230423_18-53-38_1570.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/11303631/Crash.20230423_18-53-38_1570.log)

**Comment by laoMao-998** [comment]
新版本里的Yim一注入就崩溃，在旧版本3.1.1.4就不会
![E VSK_AU23%KRQD~%V_ PR](https://user-images.githubusercontent.com/132966579/236975630-3b663b45-726e-48b5-b663-62a3d5827ada.png)

**Comment by laoMao-998** [comment]
[Uploading #Crash#20230508_21-57-07_8839.log…]()

**Comment by laoMao-998** [comment]
[#Crash#20230509_10-16-30_8461.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/11426614/Crash.20230509_10-16-30_8461.log)

**Comment by CrazyZhang666** [comment]
我测试了下，貌似没有这个问题，我先开启yim，然后开启esp

![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/09ea651d-6d18-4d87-9a1f-3ea05da3506e)

**Comment by Gabriel-Antonio-Sephiroth** [comment]
记得当时dos窗口里有红色error报错，后来的更新后那里就没红色error了，可能是当时yim有问题吧:(



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月17日 19:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 关于小助手外置菜单ESP功能反馈（BUG） (Issue #669) |

我测试了下，貌似没有这个问题，我先开启yim，然后开启esp

**Comment by Gabriel-Antonio-Sephiroth** [comment]
记得当时dos窗口里有红色error报错，后来的更新后那里就没红色error了，可能是当时yim有问题吧:( 就像楼上说的一个多月了，这问题没意义了


---- 回复的原邮件 ----
***@***.***>日期2023年06月17日 ***@***.***>***@***.***>***@***.***>主题Re: [CrazyZhang666/GTA5OnlineTools] 关于小助手外置菜单ESP功能反馈（BUG） (Issue #669)
我测试了下，貌似没有这个问题，我先开启yim，然后开启esp
