### ISSUE TITLE
sub 和 kiddion 都会让游戏崩溃

### ISSUE THREAD

**Issue by 17603419648** [CrazyZhang666/GTA5OnlineTools#67]
sub 在取消超级跳跃和爆炸子弹的时候会使游戏卡死崩溃；
kiddion 在伪装改车王模型的时候从改车王出来也会使游戏崩溃

**Comment by 17603419648** [comment]
感谢您所做出的贡献，为我游戏提供了很多便利，添加了更多乐趣，希望您有时间修复一下我之前所说的bug

**Comment by CrazyZhang666** [comment]
这个我也没办法啊，我没有出现崩溃过，不知道啥原因，尽量避免可能崩溃的功能吧
