### ISSUE TITLE
【YimMenu】注入崩溃

### ISSUE THREAD

**Issue by Matoliet** [CrazyZhang666/GTA5OnlineTools#674]
无论我怎么弄怎么清理缓存和删掉配置只要进去仅限邀请的战局或者其他线上战局注入就崩溃，急急急！

**Comment by sch-lda** [comment]
昨日Rockstar更新了游戏启动器导致Yimmenu注入崩溃，该问题已被Yimmenu修复，请耐心等待小助手更新。这里有一个理论上yimmenu注入正常的小助手非官方测试版，有需要的可以下载使用。下载后无论能用还是不能用都请ping我反馈一下。从这里下载 https://dl.ffff.cf/GTA5OnlineTools-YimMenu

**Comment by yichunedm** [comment]
测试版的可以正常注入，但是不能开启舞蹈模式，开启会导致游戏崩溃 @sch-lda

**Comment by sch-lda** [comment]
OK，感谢反馈。能注入就行，舞蹈模式确实在很多场景下不兼容

**Comment by CrazyZhang666** [comment]
已发布更新修复崩溃问题

**Comment by ERGFHT** [comment]
还是没有用，CMD显示严重错误.未找到 'PD'.这可能是游戏版本或启动器版本不受支持
