### ISSUE TITLE
用了小助手以后重启了下电脑，然后进不去游戏了

### ISSUE THREAD

**Issue by yanjichen857** [CrazyZhang666/GTA5OnlineTools#68]
没有被ban，但是就是进不去游戏，有两种提示，一种是用steam进游戏，显示服务不可用，错误代码134，一种是R星登录器进游戏，显示我们无法创建登录令牌，请稍后再试，网上什么方法都试过了，删文档，删R星，删游戏，啥都试过了，听说有可能是小助手的问题，想问下有没有其他人有这种情况。

**Comment by yanjichen857** [comment]
然后就是，我朋友都在玩，就我不能进

**Comment by xueshiji** [comment]
你这明显是网络的问题。

**Comment by CrazyZhang666** [comment]
开个加速器，或者把我的文档Rockstar Games文件夹删除重新进入游戏
![image](https://user-images.githubusercontent.com/28080853/117406079-23999400-af3f-11eb-933b-666f3de3d6ba.png)
