### ISSUE TITLE
改装铺跳过前置任务直接变白板了

### ISSUE THREAD

**Issue by weiye888** [CrazyZhang666/GTA5OnlineTools#680]
改装铺跳过前置任务直接变白板了，这一个bug怎么换都没用![QQ截图20230520180411](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/117328683/db5069d4-b377-4831-86e6-74bf1ab135ac)

**Comment by CrazyZhang666** [comment]
这个我后续研究下

**Comment by CrazyZhang666** [comment]
已修复
