### ISSUE TITLE
win11软件启动1分钟闪退

### ISSUE THREAD

**Issue by PengGe20000** [CrazyZhang666/GTA5OnlineTools#691]
https://github.com/CrazyZhang666/GTA5OnlineTools/assets/105643299/c439c4a5-431e-4e8d-b225-aef2bd277450

**Comment by CrazyZhang666** [comment]
删除这个文件夹，然后再打开小助手
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/79a5ddeb-eafa-4cb6-8a20-dc9cb03d0e56)

**Comment by PengGe20000** [comment]
https://github.com/CrazyZhang666/GTA5OnlineTools/assets/105643299/3e8d8c14-88f6-4d3b-8688-5edd1058d17e
没用我反反复复几10次

**Comment by CrazyZhang666** [comment]
把这里的崩溃日志发一下
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/46fbe551-bbb4-496c-a1b2-a2762ab38d1f)

**Comment by CrazyZhang666** [comment]
在视频的最后1秒钟 我看到了一个控制台窗口一闪而过 这个应该就是导致闪退的问题
这个应该是个隐藏的dll文件（以前有人反馈过，是森林之子的辅助自动注入到小助手导致的闪退）

你把小助手别放到桌面，比如D盘，单独建一个文件夹，把小助手放到里面去再打开就可以了

**Comment by PengGe20000** [comment]
我之前好像是用过森林之子辅助但是我文件夹里面没有崩溃文件没有收集到原因
在D盘的小助手没有闪退这个奇怪的我森林之子也在D盘应该是什么东西一直在冲突后台没有收集到
Uploading bandicam 2023-06-17 00-27-59-352.mp4…

**Comment by CrazyZhang666** [comment]
因为你桌面有隐藏文件，请按照图片操作，应该会找到一个可疑的隐藏dll文件
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/fe3f76d0-6488-4e53-98f3-c277f6dd2fea)
