### ISSUE TITLE
F-160载具貌似会导致小助手崩溃？

### ISSUE THREAD

**Issue by GoldenDog1218** [CrazyZhang666/GTA5OnlineTools#699]
F-160载具貌似会导致小助手崩溃？
不管是直接在全部载具-飞机里找还是搜索F-160都会导致小助手崩溃
然后就是全部载具-飞机里在崩溃前只能加载出几辆飞机
其他载具目前还没发现问题

**Comment by CrazyZhang666** [comment]
我这里没办法复现，不知道从何入手😂

**Comment by CrazyZhang666** [comment]
把这个文件夹的崩溃日志发这里我看看
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/0cb62482-b1d4-41be-925b-d6adccdb007d)

**Comment by CrazyZhang666** [comment]
已修复
