### ISSUE TITLE
线上小助手bug

### ISSUE THREAD

**Issue by YuHan02** [CrazyZhang666/GTA5OnlineTools#7]
Breat在之前我使用这个修改了赌场收益，金额是1个亿，过了一天后第二天就不能修改了，现在Breat输入赌场收益那一条代码显示的不是赌场收益的金额而一直是0。请官方赶紧修复！！！谢谢

**Comment by CrazyZhang666** [comment]
这个不是bug，应该是你角色弄错了，MP0是角色1，MP1是角色2
