### ISSUE TITLE
为什么kiddion已过期 等待更新 

### ISSUE THREAD

**Issue by Hun0Ali** [CrazyZhang666/GTA5OnlineTools#701]
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/137083244/00ff09c4-f524-4382-b60b-98dab678705d)

**Comment by CrazyZhang666** [comment]
因为kiddion没有更新

**Comment by Hun0Ali** [comment]
怎么更它呀

**Comment by CrazyZhang666** [comment]
这个是kiddion的发布地址，目前还没有更新
https://www.unknowncheats.me/forum/grand-theft-auto-v/576854-kiddions-modest-external-menu-thread-5-a.html
