### ISSUE TITLE
esp能把好友也加进去吗，我记得以前都有

### ISSUE THREAD

**Issue by MercurYBT** [CrazyZhang666/GTA5OnlineTools#702]

**Comment by CrazyZhang666** [comment]
是好友单独显示一个颜色对吗，便于区分？

**Comment by MercurYBT** [comment]
> 是好友单独显示一个颜色对吗，便于区分？

也可以这样，可以添加一个包含好友也一起锁的按钮吗

**Comment by CrazyZhang666** [comment]
这个后续我研究下怎么弄，锁定是根据距离准星近的，不区分是否为好友

**Comment by MercurYBT** [comment]
> 这个后续我研究下怎么弄，锁定是根据距离准星近的，不区分是否为好友

我记得以前好像就是显示全部玩家（也包括好友）那种比较方便。或者添加一个按钮：取消锁定好友

**Comment by CrazyZhang666** [comment]
这个后续都可以调整，如果你有兴趣，也可以看看小助手ESP源码

**Comment by MercurYBT** [comment]
> 这个后续都可以调整，如果你有兴趣，也可以看看小助手ESP源码

我也很想帮忙，但是有点看不懂😅
