### ISSUE TITLE
小助手外置菜单无法呼叫飞行载具

### ISSUE THREAD

**Issue by NQBFS** [CrazyZhang666/GTA5OnlineTools#705]
用小助手外置菜单无论是双击或者点击呼叫个人载具都无法叫出飞行载具 只能通过m键呼叫飞行载具才可

**Comment by CrazyZhang666** [comment]
飞行载具我还没测试过，汽车是没问题的

**Comment by NQBFS** [comment]
可以修复吗 好像1.65的版本可以通过外置菜单呼叫飞行载具 在哪次更新之后就不行了
