### ISSUE TITLE
最近4-5版本很容易出现异常

### ISSUE THREAD

**Issue by immoke** [CrazyZhang666/GTA5OnlineTools#708]
作者好，最近更新的4-5个版本里，dll注入都很容易出现崩溃的情况，错误代码大致如下：

现象就是游戏可以正常玩，该有的功能基本都在，就算出问题了，使用小助手换一个战局就好了。
但是比如说做任务（我有1次佩里克岛，1次末日3）会频繁的卡位移，什么操作都做不了。自杀以后，就一直转圈，最后导致只能退出重新登录游戏，然后任务也得重新做。

麻烦帮忙看看这是什么原因，出现次数越来越多了。谢谢。

`[04:52:09.8941834][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7F0920000 Size: 67158528
ntdll.dll Base Address: 0x7FFB12DB0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFB10EE0000 Size: 519168
KERNELBASE.dll Base Address: 0x7FFB10820000 Size: 1255424
USER32.dll Base Address: 0x7FFB11300000 Size: 581120
win32u.dll Base Address: 0x7FFB10540000 Size: 42496
GDI32.dll Base Address: 0x7FFB11110000 Size: 61952
gdi32full.dll Base Address: 0x7FFB10700000 Size: 669696
msvcp_win.dll Base Address: 0x7FFB10D70000 Size: 344064
ucrtbase.dll Base Address: 0x7FFB10600000 Size: 735744
PSAPI.DLL Base Address: 0x7FFB10ED0000 Size: 2048
WS2_32.dll Base Address: 0x7FFB118C0000 Size: 275456
RPCRT4.dll Base Address: 0x7FFB10FA0000 Size: 923136
CRYPT32.dll Base Address: 0x7FFB10C10000 Size: 1100288
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFAB4A60000 Size: 96256
DSOUND.dll Base Address: 0x7FFABFEA0000 Size: 380416
WINTRUST.dll Base Address: 0x7FFB10B50000 Size: 292864
msvcrt.dll Base Address: 0x7FFB11930000 Size: 477184
VERSION.dll Base Address: 0x7FFB09C40000 Size: 10752
IMM32.dll Base Address: 0x7FFB110E0000 Size: 122368
advapi32.dll Base Address: 0x7FFB117B0000 Size: 427520
bcrypt.dll Base Address: 0x7FFB10B20000 Size: 103424
sechost.dll Base Address: 0x7FFB10E30000 Size: 412672
SHLWAPI.dll Base Address: 0x7FFB115D0000 Size: 182784
bink2w64.dll Base Address: 0x7FFABFF40000 Size: 307712
combase.dll Base Address: 0x7FFB12540000 Size: 2327040
SHELL32.dll Base Address: 0x7FFB11D30000 Size: 5803520
ole32.dll Base Address: 0x7FFB114A0000 Size: 832000
OLEAUT32.dll Base Address: 0x7FFB11C60000 Size: 608256
WININET.dll Base Address: 0x7FFAF7250000 Size: 2026496
WINMM.dll Base Address: 0x7FFB05E20000 Size: 81408
MF.dll Base Address: 0x7FFACE000000 Size: 340992
msdmo.dll Base Address: 0x7FFAF3490000 Size: 13312
MFPlat.DLL Base Address: 0x7FFAE59D0000 Size: 1409536
PROPSYS.dll Base Address: 0x7FFB0B840000 Size: 631296
MFReadWrite.dll Base Address: 0x7FFAB4950000 Size: 918016
cfgmgr32.dll Base Address: 0x7FFB10BC0000 Size: 218624
WTSAPI32.dll Base Address: 0x7FFB0A9E0000 Size: 37888
d3d9.dll Base Address: 0x7FFAEC9A0000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFACBE10000 Size: 2423296
shcore.dll Base Address: 0x7FFB11140000 Size: 476672
DINPUT8.dll Base Address: 0x7FFB09E90000 Size: 169472
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFB09E70000 Size: 48128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFB12900000 Size: 864768
IPHLPAPI.DLL Base Address: 0x7FFB0F860000 Size: 170496
powrprof.dll Base Address: 0x7FFB10300000 Size: 70656
winmmbase.dll Base Address: 0x7FFAE68C0000 Size: 95232
d3dx9_43.dll Base Address: 0x7FFAB46E0000 Size: 2280960
kernel.appcore.dll Base Address: 0x7FFB0ED30000 Size: 16384
dwmapi.dll Base Address: 0x7FFB0DC40000 Size: 99328
windows.storage.dll Base Address: 0x7FFB0E110000 Size: 5819904
OPENGL32.dll Base Address: 0x7FFACBC40000 Size: 909312
Wldp.dll Base Address: 0x7FFB0FE10000 Size: 94720
GLU32.dll Base Address: 0x7FFAE4400000 Size: 122880
MFCORE.DLL Base Address: 0x7FFAB4250000 Size: 3960832
ksuser.dll Base Address: 0x7FFB09C50000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFB0FD60000 Size: 10752
UMPDC.dll Base Address: 0x7FFB102E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFB10570000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFAE5990000 Size: 105472
MSASN1.dll Base Address: 0x7FFB0FFA0000 Size: 34816
inputhost.dll Base Address: 0x7FFB037D0000 Size: 976384
wintypes.dll Base Address: 0x7FFB0D180000 Size: 487424
CoreUIComponents.dll Base Address: 0x7FFB0D3E0000 Size: 1804800
CoreMessaging.dll Base Address: 0x7FFB0D770000 Size: 606720
ntmarta.dll Base Address: 0x7FFB0F5D0000 Size: 140288
dbghelp.dll Base Address: 0x7FFB0E970000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFAF82E0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFB0FD70000 Size: 46080
d3d12.dll Base Address: 0x7FFAF0A90000 Size: 73728
rsaenh.dll Base Address: 0x7FFB0F490000 Size: 142336
uxtheme.dll Base Address: 0x7FFB0DA40000 Size: 382464
imagehlp.dll Base Address: 0x7FFB10E10000 Size: 45056
clbcatq.dll Base Address: 0x7FFB12490000 Size: 437760
dxdiagn.dll Base Address: 0x7FFAF0A00000 Size: 395264
d3d11.dll Base Address: 0x7FFB0C9A0000 Size: 1853440
DEVOBJ.dll Base Address: 0x7FFB10160000 Size: 109056
dxgi.dll Base Address: 0x7FFB0ED50000 Size: 614912
WMICLNT.dll Base Address: 0x7FFB0B680000 Size: 31744
wbemprox.dll Base Address: 0x7FFB090B0000 Size: 27648
wbemcomn.dll Base Address: 0x7FFB07E80000 Size: 328704
gpapi.dll Base Address: 0x7FFB0ED00000 Size: 69120
wbemsvc.dll Base Address: 0x7FFB075C0000 Size: 7168
cryptnet.dll Base Address: 0x7FFB09B70000 Size: 135168
profapi.dll Base Address: 0x7FFB103D0000 Size: 68608
fastprox.dll Base Address: 0x7FFB07690000 Size: 708608
amsi.dll Base Address: 0x7FFB06D50000 Size: 62464
USERENV.dll Base Address: 0x7FFB10390000 Size: 108032
WINNSI.DLL Base Address: 0x7FFB09C30000 Size: 11776
NSI.dll Base Address: 0x7FFB12480000 Size: 7680
MpOav.dll Base Address: 0x7FFB06C20000 Size: 204800
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFAB3830000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFB11750000 Size: 240128
Normaliz.dll Base Address: 0x7FFB110D0000 Size: 512
WINHTTP.dll Base Address: 0x7FFB09D60000 Size: 845312
Secur32.dll Base Address: 0x7FFAF8680000 Size: 11264
MSVCP140.dll Base Address: 0x7FFAF4DF0000 Size: 346112
VCRUNTIME140.dll Base Address: 0x7FFAF4E80000 Size: 65024
SSPICLI.DLL Base Address: 0x7FFB10350000 Size: 123392
VCRUNTIME140_1.dll Base Address: 0x7FFAF4DA0000 Size: 15360
dhcpcsvc6.DLL Base Address: 0x7FFB09730000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFB09800000 Size: 61440
PrxerDrv.dll Base Address: 0x7FFAEE140000 Size: 60416
mswsock.dll Base Address: 0x7FFB0FB70000 Size: 331776
PrxerNsp.dll Base Address: 0x7FFAE93B0000 Size: 46080
DNSAPI.dll Base Address: 0x7FFB0F8A0000 Size: 599040
napinsp.dll Base Address: 0x7FFAE8BE0000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAE8BC0000 Size: 66048
wshbth.dll Base Address: 0x7FFAEC040000 Size: 43008
NLAapi.dll Base Address: 0x7FFB0BBF0000 Size: 68608
winrnr.dll Base Address: 0x7FFAE8BA0000 Size: 32768
nvapi64.dll Base Address: 0x7FFB07F30000 Size: 6356480
drvstore.dll Base Address: 0x7FFB09920000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFAF09C0000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFB04100000 Size: 7680
nvspcap64.dll Base Address: 0x7FFABFBC0000 Size: 2055680
MSCTF.dll Base Address: 0x7FFB11630000 Size: 864256
textinputframework.dll Base Address: 0x7FFB03970000 Size: 725504
QQPinyinTSF.dll Base Address: 0x7FFAF3FA0000 Size: 97792
QQPinyin.ime Base Address: 0x7FFAE1090000 Size: 6509568
USP10.dll Base Address: 0x7FFAF3F80000 Size: 512
MSIMG32.dll Base Address: 0x7FFB01570000 Size: 1536
rasadhlp.dll Base Address: 0x7FFB01160000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFB02E20000 Size: 288768
TextShaping.dll Base Address: 0x7FFAF6C50000 Size: 304640
WINSTA.dll Base Address: 0x7FFB101C0000 Size: 219648
nvldumdx.dll Base Address: 0x7FFB01CA0000 Size: 597504
edputil.dll Base Address: 0x7FFAEE0A0000 Size: 85504
Windows.StateRepositoryPS.dll Base Address: 0x7FFAF3340000 Size: 29696
urlmon.dll Base Address: 0x7FFB00D50000 Size: 1279488
iertutil.dll Base Address: 0x7FFB01960000 Size: 549888
srvcli.dll Base Address: 0x7FFB00D20000 Size: 54272
netutils.dll Base Address: 0x7FFB0F970000 Size: 19456
virtdisk.dll Base Address: 0x7FFB0BEF0000 Size: 40960
FLTLIB.DLL Base Address: 0x7FFAF0400000 Size: 12800
appresolver.dll Base Address: 0x7FFAEE5F0000 Size: 414720
Bcp47Langs.dll Base Address: 0x7FFB066F0000 Size: 220160
SLC.dll Base Address: 0x7FFB0EFD0000 Size: 133120
sppc.dll Base Address: 0x7FFB0EFA0000 Size: 86528
OneCoreCommonProxyStub.dll Base Address: 0x7FFAF4360000 Size: 16384
OneCoreUAPCommonProxyStub.dll Base Address: 0x7FFB05F20000 Size: 98304
nvwgf2umx.dll Base Address: 0x7FFAFB890000 Size: 35051008
NvCamera64.dll Base Address: 0x7FFAB2FD0000 Size: 4093952
WindowsCodecs.dll Base Address: 0x7FFB071D0000 Size: 1328128
XINPUT9_1_0.dll Base Address: 0x7FFAF5BD0000 Size: 4096
HID.DLL Base Address: 0x7FFB0ECB0000 Size: 20480
MessageBus.dll Base Address: 0x7FFAFA2C0000 Size: 5349888
dxcore.dll Base Address: 0x7FFB0B6A0000 Size: 147968
d3dcompiler_47_64.dll Base Address: 0x7FFAB2BC0000 Size: 3922944
nvcuda64.dll Base Address: 0x7FFAB2220000 Size: 5683200
MMDevApi.dll Base Address: 0x7FFB0A320000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFAB2060000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFB0A3B0000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFB0DB40000 Size: 31744
Windows.UI.dll Base Address: 0x7FFB03B10000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFB075E0000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFB0AA20000 Size: 1449984
avrt.dll Base Address: 0x7FFB07CB0000 Size: 5632
MessageBus.dll Base Address: 0x7FFAF5470000 Size: 5349888
socialclub.dll Base Address: 0x7FFABEFD0000 Size: 5094912
chrome_elf.dll Base Address: 0x7FFABEEC0000 Size: 685568
libcef.dll Base Address: 0x7FFAB6E20000 Size: 109755392
COMDLG32.dll Base Address: 0x7FFB119D0000 Size: 684032
OLEACC.dll Base Address: 0x7FFB01500000 Size: 260608
UIAutomationCore.DLL Base Address: 0x7FFAE7790000 Size: 2041344
NETAPI32.dll Base Address: 0x7FFAFA240000 Size: 47616
COMCTL32.dll Base Address: 0x7FFAFB170000 Size: 560128
DWrite.dll Base Address: 0x7FFAFAEF0000 Size: 1601024
WINSPOOL.DRV Base Address: 0x7FFB012B0000 Size: 349184
dxva2.dll Base Address: 0x7FFAE9690000 Size: 96256
credui.dll Base Address: 0x7FFAF07A0000 Size: 61952
ncrypt.dll Base Address: 0x7FFB0FE80000 Size: 102400
CRYPTUI.dll Base Address: 0x7FFAF35E0000 Size: 246272
wevtapi.dll Base Address: 0x7FFB0A180000 Size: 296960
ESENT.dll Base Address: 0x7FFAFAA00000 Size: 2585088
WKSCLI.DLL Base Address: 0x7FFB0F5B0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFB09670000 Size: 61440
NTASN1.dll Base Address: 0x7FFB0FE40000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFB0F080000 Size: 364544
fwbase.dll Base Address: 0x7FFB0F040000 Size: 159744
FWPolicyIOMgr.dll Base Address: 0x7FFAFA260000 Size: 216064
wdmaud.drv Base Address: 0x7FFAB1560000 Size: 193024
msacm32.drv Base Address: 0x7FFAF4540000 Size: 17920
MSACM32.dll Base Address: 0x7FFABFFD0000 Size: 74240
midimap.dll Base Address: 0x7FFAF4280000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFAF6900000 Size: 42496
YimMenu.dll Base Address: 0x7FFAD8380000 Size: 3466240
D3DCOMPILER_47.dll Base Address: 0x7FFB0BF80000 Size: 3396608
xinput1_4.dll Base Address: 0x7FFAE8B20000 Size: 30208
Dumping registers:
RAX: 0x1A00B9EE140
RCX: 0x1A00B9861A8
RDX: 0x1A00B9EE140
RBX: 0x0
RSI: 0x7FF7F32807D0
RDI: 0x1A00B6DB830
RSP: 0x73A14FDE60
RBP: 0x73A14FDF59
R8:  0x0
R9:  0x2A
R10: 0x1A00B4FC6D0
R11: 0x1A00B9EE140
R12: 0x1
R13: 0x1
R14: 0x1A00C511C00
R15: 0x0
Dumping stacktrace:
[0]     YimMenu.dll+0xD7EAE 0x7FFAD8457EAE
[1]     GTA5.exe+0x11413AC 0x7FF7F1A613AC
[2]     GTA5.exe+0x1140D0A 0x7FF7F1A60D0A
[3]     GTA5.exe+0x1144C6D 0x7FF7F1A64C6D
[4]     GTA5.exe+0x1143DAE 0x7FF7F1A63DAE
[5]     GTA5.exe+0x11457CB 0x7FF7F1A657CB
[6]     GTA5.exe+0x16D04B3 0x7FF7F1FF04B3
[7]     GTA5.exe+0x16CF94B 0x7FF7F1FEF94B
[8]     GTA5.exe+0x11458C5 0x7FF7F1A658C5
[9]     GTA5.exe+0x10BAAA9 0x7FF7F19DAAA9
[10]    GTA5.exe+0x161A8E9 0x7FF7F1F3A8E9
[11]    GTA5.exe+0x161A11B 0x7FF7F1F3A11B
[12]    GTA5.exe+0x277F6 0x7FF7F09477F6
[13]    GTA5.exe+0x20E9B 0x7FF7F0940E9B
[14]    GTA5.exe+0x1619D24 0x7FF7F1F39D24
[15]    GTA5.exe+0x1494 0x7FF7F0921494
[16]    GTA5.exe+0x12F22C3 0x7FF7F1C122C3
[17]    GTA5.exe+0x180CE38 0x7FF7F212CE38
[18]    KERNEL32.DLL BaseThreadInitThunk
[19]    ntdll.dll RtlUserThreadStart
--------End of exception--------
`

**Comment by immoke** [comment]
[04:52:09.8941834][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7F0920000 Size: 67158528
ntdll.dll Base Address: 0x7FFB12DB0000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFB10EE0000 Size: 519168
KERNELBASE.dll Base Address: 0x7FFB10820000 Size: 1255424
USER32.dll Base Address: 0x7FFB11300000 Size: 581120
win32u.dll Base Address: 0x7FFB10540000 Size: 42496
GDI32.dll Base Address: 0x7FFB11110000 Size: 61952
gdi32full.dll Base Address: 0x7FFB10700000 Size: 669696
msvcp_win.dll Base Address: 0x7FFB10D70000 Size: 344064
ucrtbase.dll Base Address: 0x7FFB10600000 Size: 735744
PSAPI.DLL Base Address: 0x7FFB10ED0000 Size: 2048
WS2_32.dll Base Address: 0x7FFB118C0000 Size: 275456
RPCRT4.dll Base Address: 0x7FFB10FA0000 Size: 923136
CRYPT32.dll Base Address: 0x7FFB10C10000 Size: 1100288
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFAB4A60000 Size: 96256
DSOUND.dll Base Address: 0x7FFABFEA0000 Size: 380416
WINTRUST.dll Base Address: 0x7FFB10B50000 Size: 292864
msvcrt.dll Base Address: 0x7FFB11930000 Size: 477184
VERSION.dll Base Address: 0x7FFB09C40000 Size: 10752
IMM32.dll Base Address: 0x7FFB110E0000 Size: 122368
advapi32.dll Base Address: 0x7FFB117B0000 Size: 427520
bcrypt.dll Base Address: 0x7FFB10B20000 Size: 103424
sechost.dll Base Address: 0x7FFB10E30000 Size: 412672
SHLWAPI.dll Base Address: 0x7FFB115D0000 Size: 182784
bink2w64.dll Base Address: 0x7FFABFF40000 Size: 307712
combase.dll Base Address: 0x7FFB12540000 Size: 2327040
SHELL32.dll Base Address: 0x7FFB11D30000 Size: 5803520
ole32.dll Base Address: 0x7FFB114A0000 Size: 832000
OLEAUT32.dll Base Address: 0x7FFB11C60000 Size: 608256
WININET.dll Base Address: 0x7FFAF7250000 Size: 2026496
WINMM.dll Base Address: 0x7FFB05E20000 Size: 81408
MF.dll Base Address: 0x7FFACE000000 Size: 340992
msdmo.dll Base Address: 0x7FFAF3490000 Size: 13312
MFPlat.DLL Base Address: 0x7FFAE59D0000 Size: 1409536
PROPSYS.dll Base Address: 0x7FFB0B840000 Size: 631296
MFReadWrite.dll Base Address: 0x7FFAB4950000 Size: 918016
cfgmgr32.dll Base Address: 0x7FFB10BC0000 Size: 218624
WTSAPI32.dll Base Address: 0x7FFB0A9E0000 Size: 37888
d3d9.dll Base Address: 0x7FFAEC9A0000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFACBE10000 Size: 2423296
shcore.dll Base Address: 0x7FFB11140000 Size: 476672
DINPUT8.dll Base Address: 0x7FFB09E90000 Size: 169472
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFB09E70000 Size: 48128
XINPUT1_3.dll Base Address: 0x400000 Size: 85504
SETUPAPI.dll Base Address: 0x7FFB12900000 Size: 864768
IPHLPAPI.DLL Base Address: 0x7FFB0F860000 Size: 170496
powrprof.dll Base Address: 0x7FFB10300000 Size: 70656
winmmbase.dll Base Address: 0x7FFAE68C0000 Size: 95232
d3dx9_43.dll Base Address: 0x7FFAB46E0000 Size: 2280960
kernel.appcore.dll Base Address: 0x7FFB0ED30000 Size: 16384
dwmapi.dll Base Address: 0x7FFB0DC40000 Size: 99328
windows.storage.dll Base Address: 0x7FFB0E110000 Size: 5819904
OPENGL32.dll Base Address: 0x7FFACBC40000 Size: 909312
Wldp.dll Base Address: 0x7FFB0FE10000 Size: 94720
GLU32.dll Base Address: 0x7FFAE4400000 Size: 122880
MFCORE.DLL Base Address: 0x7FFAB4250000 Size: 3960832
ksuser.dll Base Address: 0x7FFB09C50000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFB0FD60000 Size: 10752
UMPDC.dll Base Address: 0x7FFB102E0000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFB10570000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFAE5990000 Size: 105472
MSASN1.dll Base Address: 0x7FFB0FFA0000 Size: 34816
inputhost.dll Base Address: 0x7FFB037D0000 Size: 976384
wintypes.dll Base Address: 0x7FFB0D180000 Size: 487424
CoreUIComponents.dll Base Address: 0x7FFB0D3E0000 Size: 1804800
CoreMessaging.dll Base Address: 0x7FFB0D770000 Size: 606720
ntmarta.dll Base Address: 0x7FFB0F5D0000 Size: 140288
dbghelp.dll Base Address: 0x7FFB0E970000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFAF82E0000 Size: 136704
CRYPTSP.dll Base Address: 0x7FFB0FD70000 Size: 46080
d3d12.dll Base Address: 0x7FFAF0A90000 Size: 73728
rsaenh.dll Base Address: 0x7FFB0F490000 Size: 142336
uxtheme.dll Base Address: 0x7FFB0DA40000 Size: 382464
imagehlp.dll Base Address: 0x7FFB10E10000 Size: 45056
clbcatq.dll Base Address: 0x7FFB12490000 Size: 437760
dxdiagn.dll Base Address: 0x7FFAF0A00000 Size: 395264
d3d11.dll Base Address: 0x7FFB0C9A0000 Size: 1853440
DEVOBJ.dll Base Address: 0x7FFB10160000 Size: 109056
dxgi.dll Base Address: 0x7FFB0ED50000 Size: 614912
WMICLNT.dll Base Address: 0x7FFB0B680000 Size: 31744
wbemprox.dll Base Address: 0x7FFB090B0000 Size: 27648
wbemcomn.dll Base Address: 0x7FFB07E80000 Size: 328704
gpapi.dll Base Address: 0x7FFB0ED00000 Size: 69120
wbemsvc.dll Base Address: 0x7FFB075C0000 Size: 7168
cryptnet.dll Base Address: 0x7FFB09B70000 Size: 135168
profapi.dll Base Address: 0x7FFB103D0000 Size: 68608
fastprox.dll Base Address: 0x7FFB07690000 Size: 708608
amsi.dll Base Address: 0x7FFB06D50000 Size: 62464
USERENV.dll Base Address: 0x7FFB10390000 Size: 108032
WINNSI.DLL Base Address: 0x7FFB09C30000 Size: 11776
NSI.dll Base Address: 0x7FFB12480000 Size: 7680
MpOav.dll Base Address: 0x7FFB06C20000 Size: 204800
EOSSDK-Win64-Shipping.dll Base Address: 0x7FFAB3830000 Size: 7229440
WLDAP32.dll Base Address: 0x7FFB11750000 Size: 240128
Normaliz.dll Base Address: 0x7FFB110D0000 Size: 512
WINHTTP.dll Base Address: 0x7FFB09D60000 Size: 845312
Secur32.dll Base Address: 0x7FFAF8680000 Size: 11264
MSVCP140.dll Base Address: 0x7FFAF4DF0000 Size: 346112
VCRUNTIME140.dll Base Address: 0x7FFAF4E80000 Size: 65024
SSPICLI.DLL Base Address: 0x7FFB10350000 Size: 123392
VCRUNTIME140_1.dll Base Address: 0x7FFAF4DA0000 Size: 15360
dhcpcsvc6.DLL Base Address: 0x7FFB09730000 Size: 23552
dhcpcsvc.DLL Base Address: 0x7FFB09800000 Size: 61440
PrxerDrv.dll Base Address: 0x7FFAEE140000 Size: 60416
mswsock.dll Base Address: 0x7FFB0FB70000 Size: 331776
PrxerNsp.dll Base Address: 0x7FFAE93B0000 Size: 46080
DNSAPI.dll Base Address: 0x7FFB0F8A0000 Size: 599040
napinsp.dll Base Address: 0x7FFAE8BE0000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFAE8BC0000 Size: 66048
wshbth.dll Base Address: 0x7FFAEC040000 Size: 43008
NLAapi.dll Base Address: 0x7FFB0BBF0000 Size: 68608
winrnr.dll Base Address: 0x7FFAE8BA0000 Size: 32768
nvapi64.dll Base Address: 0x7FFB07F30000 Size: 6356480
drvstore.dll Base Address: 0x7FFB09920000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFAF09C0000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFB04100000 Size: 7680
nvspcap64.dll Base Address: 0x7FFABFBC0000 Size: 2055680
MSCTF.dll Base Address: 0x7FFB11630000 Size: 864256
textinputframework.dll Base Address: 0x7FFB03970000 Size: 725504
QQPinyinTSF.dll Base Address: 0x7FFAF3FA0000 Size: 97792
QQPinyin.ime Base Address: 0x7FFAE1090000 Size: 6509568
USP10.dll Base Address: 0x7FFAF3F80000 Size: 512
MSIMG32.dll Base Address: 0x7FFB01570000 Size: 1536
rasadhlp.dll Base Address: 0x7FFB01160000 Size: 7168
fwpuclnt.dll Base Address: 0x7FFB02E20000 Size: 288768
TextShaping.dll Base Address: 0x7FFAF6C50000 Size: 304640
WINSTA.dll Base Address: 0x7FFB101C0000 Size: 219648
nvldumdx.dll Base Address: 0x7FFB01CA0000 Size: 597504
edputil.dll Base Address: 0x7FFAEE0A0000 Size: 85504
Windows.StateRepositoryPS.dll Base Address: 0x7FFAF3340000 Size: 29696
urlmon.dll Base Address: 0x7FFB00D50000 Size: 1279488
iertutil.dll Base Address: 0x7FFB01960000 Size: 549888
srvcli.dll Base Address: 0x7FFB00D20000 Size: 54272
netutils.dll Base Address: 0x7FFB0F970000 Size: 19456
virtdisk.dll Base Address: 0x7FFB0BEF0000 Size: 40960
FLTLIB.DLL Base Address: 0x7FFAF0400000 Size: 12800
appresolver.dll Base Address: 0x7FFAEE5F0000 Size: 414720
Bcp47Langs.dll Base Address: 0x7FFB066F0000 Size: 220160
SLC.dll Base Address: 0x7FFB0EFD0000 Size: 133120
sppc.dll Base Address: 0x7FFB0EFA0000 Size: 86528
OneCoreCommonProxyStub.dll Base Address: 0x7FFAF4360000 Size: 16384
OneCoreUAPCommonProxyStub.dll Base Address: 0x7FFB05F20000 Size: 98304
nvwgf2umx.dll Base Address: 0x7FFAFB890000 Size: 35051008
NvCamera64.dll Base Address: 0x7FFAB2FD0000 Size: 4093952
WindowsCodecs.dll Base Address: 0x7FFB071D0000 Size: 1328128
XINPUT9_1_0.dll Base Address: 0x7FFAF5BD0000 Size: 4096
HID.DLL Base Address: 0x7FFB0ECB0000 Size: 20480
MessageBus.dll Base Address: 0x7FFAFA2C0000 Size: 5349888
dxcore.dll Base Address: 0x7FFB0B6A0000 Size: 147968
d3dcompiler_47_64.dll Base Address: 0x7FFAB2BC0000 Size: 3922944
nvcuda64.dll Base Address: 0x7FFAB2220000 Size: 5683200
MMDevApi.dll Base Address: 0x7FFB0A320000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFAB2060000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFB0A3B0000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFB0DB40000 Size: 31744
Windows.UI.dll Base Address: 0x7FFB03B10000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFB075E0000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFB0AA20000 Size: 1449984
avrt.dll Base Address: 0x7FFB07CB0000 Size: 5632
MessageBus.dll Base Address: 0x7FFAF5470000 Size: 5349888
socialclub.dll Base Address: 0x7FFABEFD0000 Size: 5094912
chrome_elf.dll Base Address: 0x7FFABEEC0000 Size: 685568
libcef.dll Base Address: 0x7FFAB6E20000 Size: 109755392
COMDLG32.dll Base Address: 0x7FFB119D0000 Size: 684032
OLEACC.dll Base Address: 0x7FFB01500000 Size: 260608
UIAutomationCore.DLL Base Address: 0x7FFAE7790000 Size: 2041344
NETAPI32.dll Base Address: 0x7FFAFA240000 Size: 47616
COMCTL32.dll Base Address: 0x7FFAFB170000 Size: 560128
DWrite.dll Base Address: 0x7FFAFAEF0000 Size: 1601024
WINSPOOL.DRV Base Address: 0x7FFB012B0000 Size: 349184
dxva2.dll Base Address: 0x7FFAE9690000 Size: 96256
credui.dll Base Address: 0x7FFAF07A0000 Size: 61952
ncrypt.dll Base Address: 0x7FFB0FE80000 Size: 102400
CRYPTUI.dll Base Address: 0x7FFAF35E0000 Size: 246272
wevtapi.dll Base Address: 0x7FFB0A180000 Size: 296960
ESENT.dll Base Address: 0x7FFAFAA00000 Size: 2585088
WKSCLI.DLL Base Address: 0x7FFB0F5B0000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFB09670000 Size: 61440
NTASN1.dll Base Address: 0x7FFB0FE40000 Size: 81408
FirewallAPI.dll Base Address: 0x7FFB0F080000 Size: 364544
fwbase.dll Base Address: 0x7FFB0F040000 Size: 159744
FWPolicyIOMgr.dll Base Address: 0x7FFAFA260000 Size: 216064
wdmaud.drv Base Address: 0x7FFAB1560000 Size: 193024
msacm32.drv Base Address: 0x7FFAF4540000 Size: 17920
MSACM32.dll Base Address: 0x7FFABFFD0000 Size: 74240
midimap.dll Base Address: 0x7FFAF4280000 Size: 13312
ondemandconnroutehelper.dll Base Address: 0x7FFAF6900000 Size: 42496
YimMenu.dll Base Address: 0x7FFAD8380000 Size: 3466240
D3DCOMPILER_47.dll Base Address: 0x7FFB0BF80000 Size: 3396608
xinput1_4.dll Base Address: 0x7FFAE8B20000 Size: 30208
Dumping registers:
RAX: 0x1A00B9EE140
RCX: 0x1A00B9861A8
RDX: 0x1A00B9EE140
RBX: 0x0
RSI: 0x7FF7F32807D0
RDI: 0x1A00B6DB830
RSP: 0x73A14FDE60
RBP: 0x73A14FDF59
R8:  0x0
R9:  0x2A
R10: 0x1A00B4FC6D0
R11: 0x1A00B9EE140
R12: 0x1
R13: 0x1
R14: 0x1A00C511C00
R15: 0x0
Dumping stacktrace:
[0]     YimMenu.dll+0xD7EAE 0x7FFAD8457EAE
[1]     GTA5.exe+0x11413AC 0x7FF7F1A613AC
[2]     GTA5.exe+0x1140D0A 0x7FF7F1A60D0A
[3]     GTA5.exe+0x1144C6D 0x7FF7F1A64C6D
[4]     GTA5.exe+0x1143DAE 0x7FF7F1A63DAE
[5]     GTA5.exe+0x11457CB 0x7FF7F1A657CB
[6]     GTA5.exe+0x16D04B3 0x7FF7F1FF04B3
[7]     GTA5.exe+0x16CF94B 0x7FF7F1FEF94B
[8]     GTA5.exe+0x11458C5 0x7FF7F1A658C5
[9]     GTA5.exe+0x10BAAA9 0x7FF7F19DAAA9
[10]    GTA5.exe+0x161A8E9 0x7FF7F1F3A8E9
[11]    GTA5.exe+0x161A11B 0x7FF7F1F3A11B
[12]    GTA5.exe+0x277F6 0x7FF7F09477F6
[13]    GTA5.exe+0x20E9B 0x7FF7F0940E9B
[14]    GTA5.exe+0x1619D24 0x7FF7F1F39D24
[15]    GTA5.exe+0x1494 0x7FF7F0921494
[16]    GTA5.exe+0x12F22C3 0x7FF7F1C122C3
[17]    GTA5.exe+0x180CE38 0x7FF7F212CE38
[18]    KERNEL32.DLL BaseThreadInitThunk
[19]    ntdll.dll RtlUserThreadStart
--------End of exception--------

**Comment by CrazyZhang666** [comment]
崩溃的主要原因就是yim缓存和yim配置文件冲突，基本上每次yim更新，都要清理缓存，否则注入=崩溃
