### ISSUE TITLE
小助手传送问题！

### ISSUE THREAD

**Issue by Aotuman979** [CrazyZhang666/GTA5OnlineTools#715]
小助手更新到 v3.1.3.6 之后发现无法使用F5传送到导航点（标导航点后按F5无反应），不确定是否个例，希望大佬看看小助手是否有这个bug

**Comment by Aotuman979** [comment]
今天用1.3.5版本测试了一下，f5传送功能是正常的

**Comment by CrazyZhang666** [comment]
重新下载v3.1.3.6版本就可以了，后来重新上传了版本，版本号没变

**Comment by Aotuman979** [comment]
好的，谢谢大佬！
