### ISSUE TITLE
组队开启差事就闪退，单人可以开启

### ISSUE THREAD

**Issue by R6ddjw** [CrazyZhang666/GTA5OnlineTools#716]
[#Crash#20230630_00-10-58_5208.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/11909135/Crash.20230630_00-10-58_5208.log)
和两个好友开黑的，一个有开小助手，一个什么都没开

**Comment by CrazyZhang666** [comment]
杀毒拦截导致的，关闭杀毒就可以了

https://crazyzhang.cn/gta5/file.html

![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/d1f8a0e1-7b0b-4879-a12c-c94128d31945)

**Comment by R6ddjw** [comment]
> 杀毒拦截导致的，关闭杀毒就可以了
> 
> https://crazyzhang.cn/gta5/file.html
> 
> ![image](https://user-images.githubusercontent.com/28080853/250044217-d1f8a0e1-7b0b-4879-a12c-c94128d31945.png)

有开小助手的就要把杀毒关了吗

**Comment by CrazyZhang666** [comment]
如果有问题，建议关闭
