### ISSUE TITLE
希望开发者大大尽快修复

### ISSUE THREAD

**Issue by WAN271** [CrazyZhang666/GTA5OnlineTools#718]
开发者你好刷车的时候有点慢有时候还刷不出来比如那个拉能自行车 ，刚刷出来过，过一会儿，就没了。还有赌场抢劫那个任务太可使用。 还有就是更新之后之前的那个补充弹药快捷键消失了吗？希望开发者大大尽快修复。

**Comment by CrazyZhang666** [comment]
刚刚更新的版本已修复此bug
