### ISSUE TITLE
自定义STAT代码复制到小助手任务编辑器的代码框后无法执行代码

### ISSUE THREAD

**Issue by wangmiaowj** [CrazyZhang666/GTA5OnlineTools#722]
web自定义的佩里克岛抢劫任务代码复制到小助手的抢劫任务编辑器后，点击执行生成的STAT代码后提示STAT代码为空，另外一点是没修改次要目标时执行生成的代码会将次要目标全部抹除，这个BUG很严重，我只想改粉钻啊

**Comment by wangmiaowj** [comment]
> 勾选随机次要目标即可

那从web复制的自定义代码怎么执行呢？复制到代码框后点击执行，然后提示无STAT代码

**Comment by CrazyZhang666** [comment]
直接粘贴到gtahax导入代码里，然后点导入按钮，小助手抢劫任务编辑器已经脱离gtahax了

**Comment by wangmiaowj** [comment]
> 直接粘贴到gtahax导入代码里，然后点导入按钮，小助手抢劫任务编辑器已经脱离gtahax了

那抢劫任务编辑器每次执行STAT代码后左下连续弹出勋章解锁的提示，例如爆头杀手、深受好评啥的，铜、银、金解锁，这个正常吗

**Comment by CrazyZhang666** [comment]
这个是正常的

**Comment by wangmiaowj** [comment]
closed
