### ISSUE TITLE
赌场豪劫前置黑客百分比错误问题

### ISSUE THREAD

**Issue by jiatingdaikuan** [CrazyZhang666/GTA5OnlineTools#723]
赌场前置黑客百分比测试，百分之5的黑客应该是扣的百分之7的钱，请修复，谢谢！会不会是百分之5和百分之7位置对调了？

**Comment by CrazyZhang666** [comment]
这个是正确的，可以游戏面板一样的，我核对过
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/2a12845a-1059-4537-a63c-46c3092bd1f1)

**Comment by endokousuke** [comment]
大佬，实际上通过小助手的“抢劫任务编辑器”，中编辑赌场抢劫的黑客成员分红的时候，无法设置成0%或1%，写入数据后，点击读取数据，会发现黑客的分红会变成7%

**Comment by endokousuke** [comment]
补充：其他成员分红数值调整没问题，包括莱斯特、车手、枪手，都可以设置0%或1%

**Comment by CrazyZhang666** [comment]
> 大佬，实际上通过小助手的“抢劫任务编辑器”，中编辑赌场抢劫的黑客成员分红的时候，无法设置成0%或1%，写入数据后，点击读取数据，会发现黑客的分红会变成7%

收到反馈
