### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by yuan0807** [CrazyZhang666/GTA5OnlineTools#725]
v3.1.4.5版本赌场转盘功能还是无效

**Comment by CrazyZhang666** [comment]
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/28080853/8f4267ea-ff95-4d77-b2ca-f9e8a9758a16)

**Comment by CrazyZhang666** [comment]
已找到问题所在，下次更新修复

**Comment by han198892** [comment]
Yim Menu注入菜单无论是线上还是线下只要是更新缓存，就会出现游戏配置文件错误（已经清除过本地配置文件重新更新缓存）

**Comment by Lamanquer** [comment]
> 已找到问题所在，下次更新修复

<img width="666" alt="2" src="https://github.com/CrazyZhang666/GTA5OnlineTools/assets/139036102/b20128d2-9c2e-4d15-af23-d9c0c8a9d57e">

**Comment by Lamanquer** [comment]
> 已找到问题所在，下次更新修复
<img width="309" alt="1" src="https://github.com/CrazyZhang666/GTA5OnlineTools/assets/139036102/25b0eb63-ab52-473d-bf88-e66d18c39fe2">
