### ISSUE TITLE
关于小助手赌场黑客黑杰克问题

### ISSUE THREAD

**Issue by jiatingdaikuan** [CrazyZhang666/GTA5OnlineTools#728]
空中别墅21点我测试了一下，自己一个人玩，能准确看到庄家底牌，和朋友一起玩，实际识别的庄家底牌在玩家2手上的第一张牌，请修复一下，3个或者4个没有测试。谢谢！

**Comment by CrazyZhang666** [comment]
这是正常的，赌场黑客只适用单人使用
