### ISSUE TITLE
GTA5线上小助手-外置菜单中“战局聊天”的问题

### ISSUE THREAD

**Issue by endokousuke** [CrazyZhang666/GTA5OnlineTools#729]
在“输入文本”页面，输入中文，然后使用中英互译的功能转换为英文的效果很差，经常翻译出的英文和原意不同。
请问可以添加一个选择翻译的选项(功能)吗？比如可以选择Google翻译、DeepL或其他较为精准的翻译工具吗？

另外我发现我在使用过程中，我使用Google翻译的结果，复制粘贴到“输入文本”的位置，某些情况下无法粘贴，按Ctrl+V没有反应，有时重启外部菜单可以解决问题，有时就算重启小助手也无法解决问题。

这是上一个小助手版本遇到的问题，当时我是Kiddion外置+YimMenu双开状态，系统为Win11，另外我无法稳定复现这个问题，所以我不清楚是什么原因导致的，如果我发现在这个版本有同样的问题，我会在这个Issues下留言。

这个Issues主要还是希望可以添加其他翻译机，谢谢！

**Comment by endokousuke** [comment]
我发现了问题所在，因为在复制Google翻译的结果的时候，偶尔会复制到一个空格或者说是换行符，导致无法粘贴到小助手里面，只要不复制到换行符，就可以粘贴

**Comment by CrazyZhang666** [comment]
这个后续我会考虑加入更多是翻译接口
