### ISSUE TITLE
2.9.6.7跟新后为什么没有任务刷钱辅助了？

### ISSUE THREAD

**Issue by rosesilencen** [CrazyZhang666/GTA5OnlineTools#73]
2.9.6.7跟新后为什么没有任务刷钱了？
就是那个名叫 ShowMeThe Money 的公寓老抢劫任务的刷钱辅助没了？？？？

**Comment by CrazyZhang666** [comment]
我隐藏了，那个不是失效了吗？可用在菜单栏-释放目录里找的文件

**Comment by CrazyZhang666** [comment]
> 好的，前几天用着还没问题，这么快就失效了吗？ 期待能尽快跟新或修复此刷钱功能， 非常感谢。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年5月8日(星期六) 中午11:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [CrazyZhang666/GTA5OnlineTools] 2.9.6.7跟新后为什么没有任务刷钱辅助了？ (#73) 我隐藏了，那个不是失效了吗？可用在菜单栏-释放目录里找的文件 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我不清楚啊，我以为失效了，下次更新再加上，你可以从释放目录手动打开

**Comment by rosesilencen** [comment]
你好博主，我又用小号试了下老抢劫差事刷钱的，F4一次200万还能用，我这用着还有效，你这边回头是在试试吧，
就是不知道原作是否又跟新了，





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月8日(星期六) 中午11:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 2.9.6.7跟新后为什么没有任务刷钱辅助了？ (#73)





 
我隐藏了，那个不是失效了吗？可用在菜单栏-释放目录里找的文件

**Comment by rosesilencen** [comment]
好的，多谢，



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月8日(星期六) 晚上9:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 2.9.6.7跟新后为什么没有任务刷钱辅助了？ (#73)





 
好的，感谢帮忙测试，下次更新恢复差事刷钱
