### ISSUE TITLE
kiddion问题

### ISSUE THREAD

**Issue by ACS31** [CrazyZhang666/GTA5OnlineTools#730]
kiddion发生了一项错误，我在跑步的同时调出kiddion菜单，但它不受控制，一直向上选择功能，小键盘5 4 2 6 8控制键对它完全不起作用，我尝试重启小助手，但那样没有用，我把小助手删了重下，但依旧没有作用，希望作者早日修复

**Comment by ACS31** [comment]
补充 87键没有问题 104键会出现这样的错误，并且我已按照使用说明中关于问题解决的办法，但那貌似不起作用

**Comment by CrazyZhang666** [comment]
这个我也没有办法

**Comment by CrazyZhang666** [comment]
这个是玩家虚拟按键异常导致的，并不是bug，你可以尝试重新插拔键盘
