### ISSUE TITLE
YimMenu  注入菜单，出现BUG后，射击只有声音和效果，但是对玩家和NPC都无伤害

### ISSUE THREAD

**Issue by immoke** [CrazyZhang666/GTA5OnlineTools#732]
老大好，出现BUG后，然后射击就没有效果了。
不管是切换战局，还是切线下再切线上，都恢复不了。
只能重启游戏。

原本想截图，但是重启游戏后没出现过，出现过我再发出来吧。

**Comment by CrazyZhang666** [comment]
使用最新版本小助手看看，最新版本小助手yim版本是最新的
