### ISSUE TITLE
刷武器问题

### ISSUE THREAD

**Issue by skycooooold** [CrazyZhang666/GTA5OnlineTools#733]
武器有时候出现刷不出来的情况，就会导致不拿枪的时候视角不能自由转动，只能看左右，按s键就会自动回头并且原地打转，操作很别扭

**Comment by skycooooold** [comment]
> 用yim出现的问题吗？
并不是，就是小助手自带的外置菜单出现的问题，更准确来说，应该是我徒手情况下如果去修改武器的子弹和弹夹这些选项，就会出现这样的情况，只能看到左右，不能看到后面，并且按s就会原地打转，并且不能举起拳头和挥拳，拿着武器的时候就不会这样

**Comment by CrazyZhang666** [comment]
从未遇到过这种情况，我也不清楚怎么解决

**Comment by skycooooold** [comment]
> 从未遇到过这种情况，我也不清楚怎么解决

好的，明白了，感谢您的回复
