### ISSUE TITLE
為什麼我打開kiddon菜單，它顯示找不到kiddon.exe

### ISSUE THREAD

**Issue by Ericsupl** [CrazyZhang666/GTA5OnlineTools#738]
為什麼我開kiddon菜單，它顯示找不到kiddon.exe

![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/140988240/956407fd-eede-4a2d-a158-f35f67e1de84)

**Comment by CrazyZhang666** [comment]
被杀毒软件删除了，关闭杀毒就好了
