### ISSUE TITLE
您好,使用赌场豪杰跳过跳过前置任务的时候,操作失误,导致无法拍照

### ISSUE THREAD

**Issue by ghost** [CrazyZhang666/GTA5OnlineTools#74]
也就是说现在第一快面板一直提示需要先侦查,但是侦查大门都无法拍照, 就是拍完照后,不提示发给莱斯特,
后面按照文档上的复制代码,导入 ，再次侦查 还是不行

**Comment by 4858951** [comment]
一样

**Comment by CrazyZhang666** [comment]
https://www.yuque.com/crazyzhang666/docs/odhm5h#hdsGW

```
INT32
$MPx_H3OPT_BITSET1
0
$MPx_H3OPT_BITSET0
0
$MPx_H3OPT_POI
0
$MPx_H3OPT_ACCESSPOINTS
0
$MPx_CAS_HEIST_FLOW
0
```

这个导入成功了，切换战局，面板会恢复到初始状态（需要花费金额重新开始任务）（代码100%有效）
