### ISSUE TITLE
如何从内存中获取紫色导航路线数据

### ISSUE THREAD

**Issue by ywz978020607** [CrazyZhang666/GTA5OnlineTools#744]
请问如何实时获取游戏内导航路线的数据，例如起终点、转折点等信息；我希望能拿到数据然后调用三方voice软件，模拟现实开车的语音导航功能。因为是直接从内存拿数据，不太清楚应该怎么查，若能指点，万分感谢！！

**Comment by CrazyZhang666** [comment]
这个我也不太懂，这种功能一般是调用Native函数，你可以看看ScriptHookVDotNet（做mod的）有没有类似功能
https://github.com/scripthookvdotnet/scripthookvdotnet
