### ISSUE TITLE
能咨询一个技术问题吗，o(*￣︶￣*)o

### ISSUE THREAD

**Issue by oper1000** [CrazyZhang666/GTA5OnlineTools#745]
![image](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/993995/feb71025-640d-4ed6-8b2c-aa0190a36791)

大佬，你好，我最近也在研究WPF，觉得你这个界面酷炫极了

我看那个主界面里面有一段http的引用，但是这个地址打不开，请问这是怎么做到的，我也想实现一样的界面效果但是模仿不来。特请教！

**Comment by CrazyZhang666** [comment]
可以看看这个，利用程序集信息实现的，其实是库文件名称空间的别名
https://github.com/CrazyZhang666/GTA5OnlineTools/blob/main/MetroSkin/Properties/AssemblyInfo.cs
