### ISSUE TITLE
抢劫任务编辑器的赌场有bug 求帮助

### ISSUE THREAD

**Issue by XsavierN** [CrazyZhang666/GTA5OnlineTools#747]
情况是：用了编辑器直接生成了赌场的分红关，设定是目标黄金、车手抢手5%、解锁所有兴趣点和侦查点，面具选动物，然后进任务走到金库门前的隧道时会直接弹出任务看天再进公开战局。已经试了四次了，一进隧道就掉出任务看天。请问大佬有没有什么破解方法。

**Comment by CrazyZhang666** [comment]
使用kiddion里的alice脚本跳过试试看

**Comment by XsavierN** [comment]
哥，我看着小助手网站研究了两晚上实在是搞不明白小助手里的脚本怎么使用，我想跳过赌场前置任务具体应该怎么操作

**Comment by XsavierN** [comment]
终于研究明白了感谢老哥帮助。现在没事了
