### ISSUE TITLE
[建议]：可以通过GitHub API来动态更新YimMenu，这可以避免频繁的更新

### ISSUE THREAD

**Issue by Aigio1064** [CrazyZhang666/GTA5OnlineTools#749]
是 [`REST API`](https://docs.github.com/zh/rest) 的一部分，可以获取`Release Latest`的信息，通过在本地保存当前`name`的值，在每次打开的时候请求这个接口，如果对不上就把旧文件重命名然后下载新的。

[Apipost](https://console-docs.apipost.cn/preview/91480c861e01b05c/63a2f7956f5ff75a?target_id=2cd1f1f8-5c6c-402b-851e-23415308c56a)

#### 接口URL
> https://api.github.com/repos/:OWNER/:REPO/releases/latest

#### 请求方式
> GET

#### 请求Header参数
参数名 | 示例值 | 参数类型 | 是否必填 | 参数描述
--- | --- | --- | --- | ---
Accept | application/vnd.github+json | String | 是 | -
#### 路径变量
参数名 | 示例值 | 参数描述
--- | --- | ---
OWNER | YimMenu | 仓库所有者
REPO | YimMenu | 仓库名

**Comment by sch-lda** [comment]
已有自动构建方案，在discord群组发布。
示例如下

带有最新汉化版本 YimMenu 的小助手构建成功！
提交信息：Merge pull request #748 from sch-lda/main (4d4e2c5a76)
下载链接：https://dl.b-f.fun/GTA5OnlineTools-YimMenu （如果你不确定要下载哪个文件，请下载这个）

为确保稳定性，正式版本的发布一般是经过人工测试的。有尝鲜需求的可以使用自动构建版
