### ISSUE TITLE
Kiddion外置辅助无法使用

### ISSUE THREAD

**Issue by kkc446** [CrazyZhang666/GTA5OnlineTools#75]
以前用着没事现在我开一下就会弹出,kiddion v.8.11.1 crazyzhang/mask 汉化,怎么办在线等！！

**Comment by luotianyi107** [comment]
同样的问题

**Comment by CrazyZhang666** [comment]
关闭杀毒软件

**Comment by kkc446** [comment]
删了游戏重新下就可以用了我在epic上验证了一下版本好像降低了所以不能用昨天重新下了一下游戏今天什么事没有

**Comment by zyxzchxyf** [comment]
杀毒然间我关了，没用

> 关闭杀毒软件

**Comment by qazxswerfv** [comment]
我也是关了杀毒软件没用
