### ISSUE TITLE
YimMenu注入式菜单崩溃

### ISSUE THREAD

**Issue by handsome-cut** [CrazyZhang666/GTA5OnlineTools#750]
在战局内注入YimMenu后游戏过一会会崩溃，未进入战局前注入在进入战局后会卡在加载界面，卸载后进入新战局可解决此问题，未进入战局注入也有概率崩溃

**Comment by FengXiaoSkidGod** [comment]
同问，没有任何log，估摸着R星偷摸更新了点啥东西

**Comment by asbndiasd** [comment]
[2023-10-05.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/12818616/2023-10-05.log)

**Comment by CrazyZhang666** [comment]
已更新yim
