### ISSUE TITLE
打开小助手的Kiddion时会弹出错误

### ISSUE THREAD

**Issue by CFAAAAA** [CrazyZhang666/GTA5OnlineTools#753]
![93980e782c72bf52de746011cc2798b](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/146957224/861bba0f-ac60-44f3-b280-d5595a38bab2)
![5292dbc992a0e3ac53dc732b994efca](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/146957224/b8472ed4-e13f-473b-b275-7a09d121d532)

**Comment by CrazyZhang666** [comment]
这个无视弹窗即可，gta5这次更新改变了build版本号，但是功能没啥变化，kid可以用
