### ISSUE TITLE
使用YimMenu遊玩沒多久就會閃退只要不使用輔助遊戲就不會閃退

### ISSUE THREAD

**Issue by ZheWeiiiii** [CrazyZhang666/GTA5OnlineTools#756]
使用YimMenu遊玩沒多久就會閃退只要不使用輔助遊戲就不會閃退

**Comment by CrazyZhang666** [comment]
已更新yim版本，重新下载最新版本小助手即可

**Comment by 1410575794** [comment]
更新后还是同样情况，玩不了多久就闪退

**Comment by Matoliet** [comment]
> 已更新yim版本，重新下载最新版本小助手即可

到底是Yim的问题还是Kiddion的问题，每次差事要启动游戏就崩溃无响应。

**Comment by SDF552** [comment]
> 已更新yim版本，重新下载最新版本小助手即可

还是闪退
