### ISSUE TITLE
关于刷个人载具超跑的

### ISSUE THREAD

**Issue by showyi** [CrazyZhang666/GTA5OnlineTools#76]
刷个人载具超跑，刷了后，然后退出游戏之后那车子就没了，按照那个您说得那个保存数据得方法试过了也不行，这个能解决下吗大佬？

**Comment by CrazyZhang666** [comment]
这个不建议保存，如果想保存使用kid刷个人载具，地图有图标的，但是后果未知

**Comment by showyi** [comment]
谢谢您的回复，哈哈哈保存了但是喜提一个月套餐




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 中午11:49
***@***.***&gt;;
抄送:&nbsp;"〆丶Show oneself ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76)



 这个不建议保存，如果想保存使用kid刷个人载具，地图有图标的，但是后果未知

**Comment by showyi** [comment]
可能是我刷那个个人载具封的一个月，关闭76号什么意思啊，大佬，我刚玩不懂，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 中午12:11
***@***.***&gt;;
抄送:&nbsp;"〆丶Show oneself ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76)





 
Closed #76.

**Comment by CrazyZhang666** [comment]
这个问题已经解决了，我关闭了帖子




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月21日(星期五) 中午12:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76)





 可能是我刷那个个人载具封的一个月，关闭76号什么意思啊，大佬，我刚玩不懂， 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年5月21日(星期五) 中午12:11 
 ***@***.***&amp;gt;; 
 抄送:&amp;nbsp;"〆丶Show oneself ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76) 
 
 
 
 
 
   
 Closed #76.

**Comment by showyi** [comment]
就是说刷个人超跑载具可以保存了下线再上可以在了 但是风险未知是吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 中午12:13
***@***.***&gt;;
抄送:&nbsp;"〆丶Show oneself ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76)





 这个问题已经解决了，我关闭了帖子 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年5月21日(星期五) 中午12:12 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76) 
 
 
 
 
 
  可能是我刷那个个人载具封的一个月，关闭76号什么意思啊，大佬，我刚玩不懂，  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年5月21日(星期五) 中午12:11  
  ***@***.***&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"〆丶Show oneself ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76)  
   
   
   
   
   
     
  Closed #76.

**Comment by CrazyZhang666** [comment]
不清楚，我没保存过，我都是商店购买的，刷出来的黑车我是不敢保存的，也没必要保存

**Comment by showyi** [comment]
用无敌 和无限弹药 奔跑速度 和超级跳跃&nbsp; 传送这些功能等会被封吗？？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CrazyZhang666/GTA5OnlineTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月21日(星期五) 中午12:16
***@***.***&gt;;
抄送:&nbsp;"〆丶Show oneself ***@***.******@***.***&gt;;
主题:&nbsp;Re: [CrazyZhang666/GTA5OnlineTools] 关于刷个人载具超跑的 (#76)





 
不清楚，我没保存过，我都是商店购买的，刷出来的黑车我是不敢保存的，也没必要保存
