### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by luoysuan** [CrazyZhang666/GTA5OnlineTools#760]
大佬 你的网站是用什么搭建的，很炫酷 也想自己弄一个

**Comment by CrazyZhang666** [comment]
我那个是hexo博客，纯静态页面，你百度搜索 hexo 就有相关内容

**Comment by CrazyZhang666** [comment]
纯新手还是别用hexo吧，这个大部分都是控制台操作，没有图形化界面
新手可以使用WordPress，这个是图形化的，比较简单些，

WordPress直接到B战搜索教程，有很多
https://search.bilibili.com/all?keyword=WordPress&from_source=webtop_search&spm_id_from=333.1007&search_source=5
