### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by sk0177** [CrazyZhang666/GTA5OnlineTools#77]
![图片2](https://user-images.githubusercontent.com/84986603/120019082-949e0a00-c01a-11eb-8e34-13169ba20ddf.png)
![图片1](https://user-images.githubusercontent.com/84986603/120019099-9bc51800-c01a-11eb-9a09-114eb0ccc3da.png)
i can’t open it    我打不开他

**Comment by CrazyZhang666** [comment]
关闭杀毒软件或者添加信任，杀毒拦截了
