### ISSUE TITLE
更新了之后小助手打不开了

### ISSUE THREAD

**Issue by cjxhcf** [CrazyZhang666/GTA5OnlineTools#772]
刚才更新，更新了之后，小助手就打不开了，他就一直在那个界面
![Uploading Desktop Screenshot 2023.12.12 - 19.48.29.81.png…]()

**Comment by sourlemon615111** [comment]
还真是

**Comment by cjxhcf** [comment]
大佬，这咋办！！！&nbsp;


大大怪
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月12日(星期二) 晚上7:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 更新了之后小助手打不开了 (Issue #772)






还真是

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.***和&gt;
