### ISSUE TITLE
关于GTA线上小助手的bug

### ISSUE THREAD

**Issue by chenUSA** [CrazyZhang666/GTA5OnlineTools#775]
自GTA更新了冬季DLC之后小助手的外置菜单等功能使用时内存模块初始化就卡在《GTA5》TimePTR 0xA上没动过，目前只能使用第三方作品。全部进程如下
开始初始化《GTA5》内存模块
《GTA5》进程数量 1
《GTA5》取第一个进程实例成功
《GTA5》程序窗口句柄 3345798
《GTA5》程序窗口标题 Grand Theft Auto V
《GTA5》程序进程ID 29228
《GTA5》程序主模块基址 0x7FF619C20000
《GTA5》程序进程句柄 3048
开始初始化《GTA5》特征码模块
《GTA5》WorldPTR 0x7FF61C1B3320
《GTA5》BlipPTR 0x7FF61BC22FA0
《GTA5》GlobalPTR 0x7FF61CB159A0
《GTA5》ReplayInterfacePTR 0x7FF61BB78B58
《GTA5》NetworkPlayerMgrPTR 0x7FF61BA67938
《GTA5》NetworkInfoPTR 0x7FF61C583538
《GTA5》ViewPortPTR 0x7FF61BC219E0
《GTA5》CCameraPTR 0x7FF61BC22000
《GTA5》AimingPedPTR 0x7FF61BC2FA10
《GTA5》WeatherPTR 0x7FF61C19BECC
《GTA5》TimePTR 0xA
还请开发者尽快解决问题，感谢！

**Comment by 1762971208** [comment]
+1

**Comment by Colexd** [comment]
+1

**Comment by LYxiangyu** [comment]
+1

**Comment by mengbo-w** [comment]
一模一样

**Comment by jkghkj** [comment]
+1

**Comment by citizengao** [comment]
同样，而且Yimmenu注入时崩溃，尽快更新
![2023-12-14](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/134982007/d8b836fc-1a4b-47b2-a186-213bf298fb01)

**Comment by yaximomo** [comment]
+1
