### ISSUE TITLE
内存模块初始化有问题了

### ISSUE THREAD

**Issue by mdx15532523178** [CrazyZhang666/GTA5OnlineTools#781]
内存模块初始化执行到最后一行就会卡住[](url)
![图片_20231213194143](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/79036213/4de330e2-de4a-4d6b-9660-e5076d8f8a09)

**Comment by waterdoubi** [comment]
俺也一样

**Comment by Jack123644** [comment]
俺也一样

**Comment by wujiaqimeima** [comment]
俺也一样

**Comment by PIYAN57** [comment]
俺也一样

**Comment by Yunwanjia006** [comment]
一样gta5大更新反作弊更新，挂加载不进去吧，希望作者快点更新
3.12.9版本能开挂但是刷不出来载具

**Comment by mdx15532523178** [comment]
我回退到游戏上个版本先玩着了，功能什么的都可以用

**Comment by Yunwanjia006** [comment]
有教程吗？怎么退回上个版本



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月14日 19:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CrazyZhang666/GTA5OnlineTools] 内存模块初始化有问题了 (Issue #781) |

我回退到游戏上个版本先玩着了，功能什么的都可以用

**Comment by mdx15532523178** [comment]
教程在discord
