### ISSUE TITLE
无法打开小助手的功能

### ISSUE THREAD

**Issue by NANYUNShigure** [CrazyZhang666/GTA5OnlineTools#783]
![屏幕截图 2023-12-13 223532](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/153746653/983904d3-0e13-4149-a11d-ac8236b40771)
如图

**Comment by wujiaqimeima** [comment]
我也是这样

**Comment by susu25105505** [comment]
第三方注入菜单尽快更新 github更新了修复错误了 小助手还没有

**Comment by susu25105505** [comment]
第三方注入菜单 现在注入崩溃 我看原作者貌似已经更新了 ，希望小助手尽快更新
