### ISSUE TITLE
小助手第三方YimMenu注入DLL之后会闪退

### ISSUE THREAD

**Issue by BatWaiGit** [CrazyZhang666/GTA5OnlineTools#788]
[cout.log](https://github.com/CrazyZhang666/GTA5OnlineTools/files/13670701/cout.log)

**Comment by pzy2000** [comment]
这是根据最新版的YimMenu编译的dll，自己用xenos64注入器注入一下。
[YimMenu.zip](https://github.com/CrazyZhang666/GTA5OnlineTools/files/13672796/YimMenu.zip)

**Comment by susu25105505** [comment]
好的 我试试

**Comment by susu25105505** [comment]
> 这是根据最新版本的YimMenu编译的dll，自己用xenos64注入器注入一下。 [YimMenu.zip](https://github.com/CrazyZhang666/GTA5OnlineTools/files/13672796/YimMenu.zip)

这个dll注入后依旧是崩溃

**Comment by pzy2000** [comment]
清除一下缓存试试呢？C:\Users\[username]\AppData\Roaming\YimMenu下面的东西删光

--------------原始邮件--------------
发件人："susu25105505 ***@***.***&gt;;
发送时间：2023年12月14日(星期四) 晚上10:20
收件人："CrazyZhang666/GTA5OnlineTools" ***@***.***&gt;;
抄送："彭志远 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [CrazyZhang666/GTA5OnlineTools] 小助手第三方YimMenu注入DLL之后会闪退 (Issue #788)
-----------------------------------

 

  
这是根据最新版本的YimMenu编译的dll，自己用xenos64注入器注入一下。 YimMenu.zip
  
这个dll注入后依旧是崩溃
