### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by rfong2001** [CrazyZhang666/GTA5OnlineTools#795]
![Screenshot 2023-12-14 232522](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/153843623/623ab5ae-6817-4363-a018-45a56f0f2fa3)

**Comment by susu25105505** [comment]
内注入菜单也是不好使 我尝试了使用最新源码编译的dll注入依旧是崩溃

**Comment by laihei** [comment]
我也是这样 咋办啊
