### ISSUE TITLE
关于gtahax无法在Windows10上正常运行

### ISSUE THREAD

**Issue by Blue-hong** [CrazyZhang666/GTA5OnlineTools#8]
处理器	Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz   2.81 GHz
机带 RAM	8.00 GB
系统类型	64 位操作系统, 基于 x64 的处理器
版本	Windows 10 家庭中文版
版本号	20H2
安装日期	‎2019/‎12/‎15
操作系统内部版本	19042.804
体验	Windows Feature Experience Pack 120.2212.2020.0

**Comment by CrazyZhang666** [comment]
gtahax win7/win10均可正常运行，你打开看是什么错误提示，一般是缺少运行库导致的
