### ISSUE TITLE
YimMenu内置菜单注入后游戏崩溃闪退问题

### ISSUE THREAD

**Issue by 3061959685** [CrazyZhang666/GTA5OnlineTools#829]
今天游戏更新了一下，更新后就发现YimMenu内置菜单注入后游戏会出现崩溃闪退问题，尝试了很多办法依旧没用，希望尽快修复

**Comment by wasdewf** [comment]
这个可以先用小助手yim菜单每夜版，但缺点是需要一个注入器而且翻译不全部分功能缺失，并且有概率注入不进去

**Comment by user57752** [comment]
同问,蹲
