### ISSUE TITLE
DLL问题

### ISSUE THREAD

**Issue by ooHollssss** [CrazyZhang666/GTA5OnlineTools#849]
现在注入DLL会闪退

**Comment by SDF552** [comment]
注入dll会游戏卡顿加闪退

**Comment by inauua** [comment]
我也是，游戏里线下线上注入就闪退，然后闪退过程我再点击注入时显示
![2024-04-18](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/110888728/06bf6492-7d4e-49f6-bfff-2960ec25415e)
