### ISSUE TITLE
YimMeun注入崩溃

### ISSUE THREAD

**Issue by Jue41** [CrazyZhang666/GTA5OnlineTools#850]
新下载的gta5游戏，一注入就崩溃，教程里的各种方法都试了还是一直崩溃。
![{385242D4-D539-431b-B62E-5A29B686196B}](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/67794342/8e0a51d0-cdd6-456a-8002-260e0b901ac8)

**Comment by SDF552** [comment]
昨天晚上已经发电子邮件给作者了不知道什么时候能解决

**Comment by SDF552** [comment]
连外置的也用不了

**Comment by wushan2010** [comment]
一样，注入就卡住崩溃退出，就是前几天gta更新了就用不起来了，脚本全删还是不可以用，等作者大佬以后慢慢更新吧

**Comment by QWEOVO123** [comment]
在作者没更新之前，可以去yimmenu仓库下载官方dll注入即可，可以用process hacker注入yimmenu.dll进入GTA5主程序，翻译完美存在，并且yimmenu更新了，不会崩毁

**Comment by wushan2010** [comment]
> 在作者没更新之前，可以去yimmenu仓库下载官方dll注入即可，可以用process hacker注入yimmenu.dll进入GTA5主程序，翻译完美存在，并且yimmenu更新了，不会崩毁

感谢，我已经解决了
