### ISSUE TITLE
YIM助手使用崩溃情况

### ISSUE THREAD

**Issue by TIMBERGL1NG** [CrazyZhang666/GTA5OnlineTools#852]
当gtaol运行时将yim助手载入游戏游戏则直接崩溃无法进入
，不久后自动退出游戏

**Comment by sch-lda** [comment]
从官网加入小助手discord群组查看公告


GTA5已更新至3179，小助手可能暂不可用，详情稍后添加

没提到的功能请自行测试，遇到失效的功能请反馈(只接受小助手本体功能反馈，例如stat编辑器/抢劫任务编辑器。不要反馈第三方页面的任何问题，例如yim/kiddion)

**小助手外置菜单 **: 
多数功能可用
传送、无敌、刷载具、刷武器等功能可用

Kiddion : 部分功能不可用,出现警告弹窗点一下确定即可

Yimmenu :
不可用,且不要尝试注入
~~yim官方已开始解决问题~~
4月17更新：yim官方已发布新版，可以从GitHub频道获取集成此yim版本的小助手测试版 
[点此下载](https://redirect.host3650.live/res1) 
 [备用](https://dl.host3650.live/GTA5OnlineTools.exe)
需要注意，注入菜单始终存在被检测风险

## 小助手本体虽然部分功能能用，但也建议等等，GTA存在一些变更，等下一个版本

gta封号存在延迟，如果你需要确定是否真的安全，需要等1-2月才能确定
