### ISSUE TITLE
传送问题

### ISSUE THREAD

**Issue by ooHollssss** [CrazyZhang666/GTA5OnlineTools#858]
每次传送都会卡地下

**Comment by MiaoZM62** [comment]
更新之后传送功能全是bug，任务载具卡没了，人还会到处飞

**Comment by lyz123321** [comment]
哎呀，那，这是r星的问题？那能不能修复，估计悬了












恋笙
***@***.***

广州航海学院
财务管理

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月22日(周一) 晚上10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CrazyZhang666/GTA5OnlineTools] 传送问题 (Issue #858)




 
更新之后传送功能全是bug，任务载具卡没了，人还会到处飞

**Comment by ooHollssss** [comment]
不像是R星问题，以前传送都能用好好的，就这次更新之后传送就变怪了

**Comment by looksky-rabbit1** [comment]
我也是，现在改装铺已经不敢TP送货了，不过这BUG只存在开车TP，如果是人物TP的话，倒是没有问题
