### ISSUE TITLE
新版外置菜单的ESP功能自瞄锁定有问题

### ISSUE THREAD

**Issue by DoedKr** [CrazyZhang666/GTA5OnlineTools#86]
新版本外置菜单里边自带的那个ESP功能的自瞄，貌似一直都是以人的某一个点向下偏移一个固定的距离。导致离得近的是瞄腿，离的远的瞄地上了。

**Comment by CrazyZhang666** [comment]
你按住右键，然后再瞄准，我测试没问题

**Comment by jinshilin35** [comment]
> 你按住右键，然后再瞄准，我测试没问题

能不能把瞄准腰部加回来，打头有点难，尤其是跑动时候，加上枪的后坐力，

**Comment by CrazyZhang666** [comment]
> > 你按住右键，然后再瞄准，我测试没问题
> 
> 能不能把瞄准腰部加回来，打头有点难，尤其是跑动时候，加上枪的后坐力，

我会加个选择瞄准位置的
