### ISSUE TITLE
希望可以支持linux

### ISSUE THREAD

**Issue by PlaidMrdeer** [CrazyZhang666/GTA5OnlineTools#874]
什么时候可以支持linux呢

**Comment by sch-lda** [comment]
不需要额外支持，本来就可以直接在wine/proton环境运行。如果gta在wine里面运行，小助手在外面，那即使运行了也没有任何意义

**Comment by PlaidMrdeer** [comment]
> 不需要额外的支持，本来就可以直接在wine/proton环境运行。你需要保证gya和小助手运行在同一个wine容器。如果gta在wine里面运行，小助手在外面，那运行了也没有任何意义

我把小助手添加进steam 然后强制使用proton 然后又把.net也添加进去，装上是装上了 但是运行小助手却检测不到.net

**Comment by sch-lda** [comment]
@PlaidMrdeer discord群组里面有人在steam deck上运行成功过。你也可以去https://github.com/sch-lda/yctest2/actions 下载自带运行库的版本
![Screenshot_2024-05-12-14-13-12-65_984e1414ae90666a90f12ff17ec14a7f](https://github.com/CrazyZhang666/GTA5OnlineTools/assets/54973190/b6cf3cdd-dbae-4f74-b177-0d0d1042a5bb)
