### ISSUE TITLE
gta 賭場黑客、搶劫編輯器都已失效

### ISSUE THREAD

**Issue by Obndder** [CrazyZhang666/GTA5OnlineTools#884]

**Comment by ZZS20** [comment]
6月25号更新的新DLC之后不管是抽奖还是抢劫编辑器都已失效
先说赌场黑客,如果想要抽展台想要的载具选择之后也会失效根本抽不到选择的东西,如想要抽老虎机编辑了想要抽的倍数之后游戏会直接卡死,人物不能起身只能退出游戏.
抢劫编辑器,在佩里科岛那里试了一下只解锁了各种的兴趣点但是前置任务还是需要做应该也算失效了吧.

**Comment by sch-lda** [comment]
公告，转自小助手discord群组

游戏已更新至1.69-3258
### 一、 小助手
小助手外置菜单 部分功能可用
已验证可用的功能:生命值修改、无敌、武器和弹药修改、传送
本次DLC更新多数globals地址都改变了，再修改旧的地址，可能导致不可预测的问题
小助手抢劫任务编辑器、stats编辑器、速度表、赌场黑客均无法使用
### 二、 第三方
Yimmenu 不要注入
yimmenu官方已开始更新，已经能在线上模式运行且多数功能重新生效但仍需进一步修复
本次游戏有较大变更，菜单更新可能需要比以往更多的时间

Kiddion 无法运行。 bincohax lschax 可能可用，gtahax不完全可用(原作者已上传至[uc论坛](https://www.unknowncheats.me/forum/downloads.php?do=file&id=45707)，等待汉化和集成)

Yimmenu、Kiddion、gtahax、bincohax、lschax不是由小助手的开发者开发的，需要等待他们的作者更新

### 三、 其他资讯
小助手测试版已在#GitHub <#1127779071720427520> 频道 发布，也可在 https://github.com/sch-lda/yctest2/releases/download/CI/GTA5OnlineTools.exe 下载，测试版已修复:
通缉等级，奔跑速度，stats读写，载具生成 随身技工，战局切换，刷出武器
抢劫任务、合约 分红和杂项
大部分自由模式活动选项(幽灵组织、移除冷却、设置ceo特殊货物等)
传送方法2，玩家列表等级和金钱，幸运轮盘修改
（我只更新这些了，去外地进行学术考察。剩下的等其他贡献者更新吧。测试版 stat编辑器、抢劫任务编辑器除了一键完成和单人开任务应该都能用了，外置菜单功能多数也恢复了。但没有新载具和新武器。yim新代码的合并和处理基本也完成了,少数汉化缺失）

**请不要询问什么时候更新、什么功能能用这种没有意义的问题，私聊我这种问题 = 封禁到小助手更新结束 ！！
新成员到 https://discord.com/channels/388227343862464513/1254956902308122664 完成验证后方可访问其他频道**

### 四、TODO (开发人员参考，用户不必阅读)
速度表
新载具和新武器
赌场黑客除幸运轮盘外的功能
抢劫任务编辑器 一键完成、单人开任务
小助手外置菜单 临时解锁地堡研究 需要修复
某些globals例如是否是脚本主机，过期不只一个版本
yimmenu代码处理/汉化可能不完整，且需要进一步测试
