### ISSUE TITLE
关于使用问题

### ISSUE THREAD

**Issue by YuHan02** [CrazyZhang666/GTA5OnlineTools#9]
用这个小助手会封号吗请问？

**Comment by CrazyZhang666** [comment]
【使用小助手安不安全】
----------------
1.我觉得这个和个人使用习惯有关，如果你自己一个人玩或者只和好友玩，不去公共战局，有路人玩家低调使用（避免被举报），不乱用刷钱，让自己数据看起来和正常玩家一样，不撕逼不斗法，而且只使用小助手外置辅助，不和其他注入式辅助混用，这样风险就比较低
2.但是如果你开在小助手在公共战局到处搞事，惹一大堆麻烦，网上随便找的注入式辅助和小助手一起开，刷钱没有限度，还有什么全解锁、8000级、几万亿、被封了也是正常的

**Comment by bobstarsky** [comment]
> ## 【使用小助手安不安全】
> 1.我觉得这个和个人使用习惯有关，如果你自己一个人玩或者只和好友玩，不去公共战局，有路人玩家低调使用（避免被举报），不乱用刷钱，让自己数据看起来和正常玩家一样，不撕逼不斗法，而且只使用小助手外置辅助，不和其他注入式辅助混用，这样风险就比较低
> 2.但是如果你开在小助手在公共战局到处搞事，惹一大堆麻烦，网上随便找的注入式辅助和小助手一起开，刷钱没有限度，还有什么全解锁、8000级、几万亿、被封了也是正常的



> ## 【使用小助手安不安全】
> 1.我觉得这个和个人使用习惯有关，如果你自己一个人玩或者只和好友玩，不去公共战局，有路人玩家低调使用（避免被举报），不乱用刷钱，让自己数据看起来和正常玩家一样，不撕逼不斗法，而且只使用小助手外置辅助，不和其他注入式辅助混用，这样风险就比较低
> 2.但是如果你开在小助手在公共战局到处搞事，惹一大堆麻烦，网上随便找的注入式辅助和小助手一起开，刷钱没有限度，还有什么全解锁、8000级、几万亿、被封了也是正常的

我没搞事额 我用加速器卡的单人战局（公共战局就我一人）刷的钱 都没杀过玩家

**Comment by bobstarsky** [comment]
> ## 【使用小助手安不安全】
> 1.我觉得这个和个人使用习惯有关，如果你自己一个人玩或者只和好友玩，不去公共战局，有路人玩家低调使用（避免被举报），不乱用刷钱，让自己数据看起来和正常玩家一样，不撕逼不斗法，而且只使用小助手外置辅助，不和其他注入式辅助混用，这样风险就比较低
> 2.但是如果你开在小助手在公共战局到处搞事，惹一大堆麻烦，网上随便找的注入式辅助和小助手一起开，刷钱没有限度，还有什么全解锁、8000级、几万亿、被封了也是正常的

我没搞事额 我用加速器卡的单人战局（公共战局就我一人）刷的钱 都没杀过玩家
