### ISSUE TITLE
赌场

### ISSUE THREAD

**Issue by 1459368331** [CrazyZhang666/GTA5OnlineTools#909]
更新了后你们赌场还能抽到载具吗

**Comment by dangerous8** [comment]
> 更新了后你们赌场还能抽到载具吗

上次游戏更新之后就不能了，而且，如果转盘你自己恰好也转到车了会卡成其他奖励，气死了哈哈哈哈。今天更新后又试了一下，还是不行。不过还是非常感谢作者的小助手，我都已经跟着用了很多年了

**Comment by wcz1-ux** [comment]
抽不到了
