### ISSUE TITLE
赌场黑客的bug反馈>_<

### ISSUE THREAD

**Issue by tkw666** [CrazyZhang666/GTA5OnlineTools#915]
现在的赌场黑客，刷不了车，并且用老虎机注入后，游戏就会死机不动，只有切战局才能解决这个问题，还有赌马也是没用，希望可以修复一下。感谢！

**Comment by Te826** [comment]
我也是，你的解决了吗，我朋友说他可以，我到现在还没搞懂问题所在处，一直显示交易中，要么就卡死

**Comment by tkw666** [comment]
还没有，还在一直交易中，应该是小助手的代码让gta5报错了，只能等修复，不过我听说网上有人用小助手代码可以刷老虎机，我也不知道是真的还是假的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月11日(星期四) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CrazyZhang666/GTA5OnlineTools] 赌场黑客的bug反馈&gt;_< (Issue #915)














 
我也是，你的解决了吗，我朋友说他可以，我到现在还没搞懂问题所在处，一直显示交易中，要么就卡死
