### ISSUE TITLE
小助手外置菜单页面打开时任务栏图标状态与配置相反

### ISSUE THREAD

**Issue by lxcoo** [CrazyZhang666/GTA5OnlineTools#919]
是不是应该从这个地方取反一下？
![image](https://github.com/user-attachments/assets/f231e8f0-dde3-47a1-99ec-a2e0a1c51c0a)

**Comment by sch-lda** [comment]
确实，IsShowInTaskbar对应的中文是隐藏任务栏图标，变量名造成了混淆
