### ISSUE TITLE
I INSTALLED WINDOWS DESKTOP RUNTIME 6.0.28 BUT ITS NOT RUNNING!!!

### ISSUE THREAD

**Issue by SonaliBendre** [CrazyZhang666/GTA5OnlineTools#925]

**Comment by Todp6e5exqzhodi65bObyrne** [comment]
我也是，一直都是弹出这个界面，runtime 下了安装了，卸载了重装都不行。

![image](https://github.com/user-attachments/assets/f782afac-dacf-408e-b41d-903f692a9769)

自己编译了一个，可以用

**Comment by Given2001** [comment]
我也是一直弹出这个界面，运行时装了也没用。
![image](https://github.com/user-attachments/assets/f455d6e5-2302-4c0c-93f3-5f4d015b4b9e)
自己用编译了一个倒是可以用
