### ISSUE TITLE
選項變黑

### ISSUE THREAD

**Issue by nkkejj** [CrazyZhang666/GTA5OnlineTools#932]
![螢幕擷取畫面 2024-09-08 191443](https://github.com/user-attachments/assets/a1751a45-8200-4421-b060-39f8f480b2c1)
求如何解決

**Comment by sch-lda** [comment]
关闭性能监测工具，他们可能会干扰小助手的显示

**Comment by nkkejj** [comment]
解決了，需把hdr給關閉，期待後續優化

**Comment by sch-lda** [comment]
> 解決了，需把hdr給關閉，期待後續優化

这个还真没法优化，小助手没有渲染相关的代码，界面渲染是微软的C# WPF框架负责的，需要WPF或者显卡厂商解决兼容性问题
