### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Dylanchen6** [CrazyZhang666/GTA5OnlineTools#94]
你好,你看方便的话吧小助手的源码给我可以吗.可以私聊.qq928278927

**Comment by CrazyZhang666** [comment]
你为啥要源码？

**Comment by Dylanchen6** [comment]
What original code, GTA5?




Dylan
***@***.***




------------------ Original ------------------
From: 穗乃果 ***@***.***&gt;
Date: Fri,Jul 30,2021 10:25 AM
To: CrazyZhang666/GTA5OnlineTools ***@***.***&gt;
Cc: Dylanchen6 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [CrazyZhang666/GTA5OnlineTools] . (#94)





 
你为啥要源码？
