### ISSUE TITLE
佩里克岛前置导入

### ISSUE THREAD

**Issue by 231564651324** [CrazyZhang666/GTA5OnlineTools#97]
导入黄金的时候，室内外全是黄金，直接1000多w次要目标，一看就是假的
应该出一个可以控制黄金数量，并且次要目标可以混杂的代码

**Comment by 231564651324** [comment]
2386464734@qq.com

**Comment by CrazyZhang666** [comment]
有个自定义佩里科岛的代码生成器

https://crazyzhang.cn/gta5/20210727162947.html
